using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Client._Stalker.PersistentCrafting.UI;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftRecipeToolbar : Control
{
    private static readonly Color Background = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color Border = PersistentCraftUiTheme.BorderSoft;

    public LineEdit SearchInput => SearchBar;
    public Button CraftableToggleButton => CraftableButton;

    public PersistentCraftRecipeToolbar()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string placeholder, string searchText, string toggleText, bool craftableOnly, Color accent)
    {
        SearchBar.PlaceHolder = placeholder;
        SearchBar.Text = searchText;

        CraftableButton.Text = toggleText;
        CraftableButton.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = craftableOnly ? accent.WithAlpha(0.14f) : Background,
            BorderColor = craftableOnly ? accent.WithAlpha(0.75f) : Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 5,
            ContentMarginBottomOverride = 5,
        };
    }
}
