using System;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftProgressBlock : Control
{
    private static readonly Color Background = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color Border = PersistentCraftUiTheme.Border;
    private static readonly Color TitleColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color FooterColor = PersistentCraftUiTheme.TextSecondary;

    public PersistentCraftProgressBlock()
    {
        RobustXamlLoader.Load(this);

        RootPanel.PanelOverride = PersistentCraftUiTheme.Panel(Background, Border, 1, 12, 12, 10, 10);
        RootPanel.RectClipContent = true;
        Body.RectClipContent = true;
    }

    public void SetData(string title, string mainText, float progressValue, Color accent, string? footerText = null)
    {
        if (RootPanel.PanelOverride is StyleBoxFlat style)
            style.BorderColor = accent;

        TitleLabel.Text = title;
        TitleLabel.FontColorOverride = TitleColor;

        MainTextLabel.Text = mainText;
        MainTextLabel.FontColorOverride = accent;
        MainTextLabel.ClipText = true;

        ProgressBar.SetAsRatio(Math.Clamp(progressValue, 0f, 1f));
        ProgressBar.BackgroundStyleBoxOverride = PersistentCraftUiTheme.ProgressBackground();
        ProgressBar.ForegroundStyleBoxOverride = PersistentCraftUiTheme.ProgressForeground(accent);

        var hasFooter = !string.IsNullOrWhiteSpace(footerText);
        FooterSpacer.Visible = hasFooter;
        FooterLabel.Visible = hasFooter;
        FooterLabel.Text = footerText ?? string.Empty;
        FooterLabel.FontColorOverride = FooterColor;
        FooterLabel.ClipText = true;
    }
}
