using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftInfoStrip : Control
{
    private static readonly Color Background = Color.FromHex("#1e222b");
    private static readonly Color Border = Color.FromHex("#485060");
    private static readonly Color TextColor = Color.FromHex("#d7dce4");

    public PersistentCraftInfoStrip()
    {
        RobustXamlLoader.Load(this);

        RootPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Background,
            BorderColor = Border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 7,
            ContentMarginBottomOverride = 7,
        };

        MinSize = new Vector2(0, 34);
        VerticalExpand = false;
        TextLabel.FontColorOverride = TextColor;
        TextLabel.ClipText = true;
    }

    public void SetData(string text, Color borderColor, Color? textColor = null)
    {
        if (RootPanel.PanelOverride is StyleBoxFlat style)
            style.BorderColor = borderColor;

        TextLabel.Text = text;
        TextLabel.FontColorOverride = textColor ?? TextColor;
    }
}
