using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftRecipeCard : Control
{
    public ContainerButton Button => RootButton;
    public PanelContainer IconHost => IconPanel;
    public BoxContainer StatusContainer => StatusHost;

    public PersistentCraftRecipeCard()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string title, string secondary, Color titleColor, Color secondaryColor)
    {
        TitleLabel.Text = title;
        TitleLabel.FontColorOverride = titleColor;
        TitleLabel.ClipText = true;

        SecondaryLabel.Text = secondary;
        SecondaryLabel.FontColorOverride = secondaryColor;
        SecondaryLabel.ClipText = true;
    }
}
