using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Client._Stalker.PersistentCrafting.UI;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftCollapsibleHeader : Control
{
    public ContainerButton Button => RootButton;

    public PersistentCraftCollapsibleHeader()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string text, int count, bool collapsed, Color foreground, Color background, Color border, Thickness margin, int verticalPadding)
    {
        RootButton.Margin = margin;
        RootButton.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = verticalPadding,
            ContentMarginBottomOverride = verticalPadding,
        };

        TitleLabel.Text = $"{(collapsed ? "▶" : "▼")} {text}";
        TitleLabel.FontColorOverride = foreground;
        TitleLabel.ClipText = true;

        CountLabel.Text = count.ToString();
        CountLabel.FontColorOverride = PersistentCraftUiTheme.TextMuted;
    }
}
