using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftRecipeDetailHeader : Control
{
    public PanelContainer IconHost => IconPanel;
    public Button ActionButton => CraftButton;
    public BoxContainer MetaContainer => MetaHost;
    public RichTextLabel InfoText => InfoLabel;

    public PersistentCraftRecipeDetailHeader()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string title, Color titleColor, string actionText, bool actionDisabled)
    {
        TitleLabel.Text = title;
        TitleLabel.FontColorOverride = titleColor;
        TitleLabel.ClipText = true;

        CraftButton.Text = actionText;
        CraftButton.Disabled = actionDisabled;
        InfoLabel.SetMessage(FormattedMessage.Empty);
    }
}
