using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using Content.Client._Stalker.PersistentCrafting.UI;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftTextSection : Control
{
    private const float DefaultTextMaxWidth = 620f;
    private static readonly Color Background = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color Border = PersistentCraftUiTheme.BorderSoft;
    private static readonly Color TitleColor = PersistentCraftUiTheme.TextPrimary;

    public PersistentCraftTextSection()
    {
        RobustXamlLoader.Load(this);

        RootPanel.PanelOverride = PersistentCraftUiTheme.Panel(Background, Border, 1, 12, 12, 10, 10);
        RootPanel.RectClipContent = true;
        Body.RectClipContent = true;
        TitleLabel.RectClipContent = true;
        ContentLabel.RectClipContent = true;

        TitleLabel.MaxWidth = DefaultTextMaxWidth;
        ContentLabel.MaxWidth = DefaultTextMaxWidth;
    }

    public void SetData(string? title, string markup, Color borderColor, int padding = 12)
    {
        if (RootPanel.PanelOverride is StyleBoxFlat style)
        {
            style.BorderColor = borderColor;
            style.ContentMarginLeftOverride = padding;
            style.ContentMarginRightOverride = padding;
            style.ContentMarginTopOverride = padding;
            style.ContentMarginBottomOverride = padding;
        }

        var hasTitle = !string.IsNullOrWhiteSpace(title);
        TitleLabel.Visible = hasTitle;
        TitleSpacer.Visible = hasTitle;
        TitleLabel.Text = title ?? string.Empty;
        TitleLabel.FontColorOverride = TitleColor;

        ContentLabel.SetMessage(FormattedMessage.FromMarkupPermissive(markup));
    }
}
