using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Client._Stalker.PersistentCrafting.UI;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftTierHeader : Control
{
    private static readonly Color Background = PersistentCraftUiTheme.SurfacePanelAlt;

    public PersistentCraftTierHeader()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string title, Color accent)
    {
        RootPanel.PanelOverride = PersistentCraftUiTheme.Panel(
            Background,
            accent.WithAlpha(0.5f),
            1,
            10,
            10,
            7,
            7);

        TitleLabel.Text = title;
        TitleLabel.FontColorOverride = accent;
    }
}
