using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Client._Stalker.PersistentCrafting.UI;

namespace Content.Client._Stalker.PersistentCrafting.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftRecipeWorkspace : Control
{
    private static readonly Color DefaultBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color DefaultPanelBackground = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color DefaultBorder = PersistentCraftUiTheme.Border;

    public BoxContainer FilterContainer => FilterHost;
    public BoxContainer TierFilterContainer => TierFilterHost;
    public BoxContainer SummaryContainer => SummaryHost;
    public BoxContainer ListContainer => ListHost;
    public BoxContainer DetailContainer => DetailHost;
    public ScrollContainer RecipeListScroll => ListScroll;
    public ScrollContainer RecipeDetailScroll => DetailScroll;

    public PersistentCraftRecipeWorkspace()
    {
        RobustXamlLoader.Load(this);

        ContentSplit.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
        SetAccent(DefaultBorder);
    }

    public void SetAccent(Color accent)
    {
        ListPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = DefaultPanelBackground,
            BorderColor = accent.WithAlpha(0.55f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 14,
            ContentMarginRightOverride = 14,
            ContentMarginTopOverride = 14,
            ContentMarginBottomOverride = 14,
        };

        DetailPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = DefaultPanelBackground,
            BorderColor = PersistentCraftUiTheme.BorderSoft,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 14,
            ContentMarginRightOverride = 14,
            ContentMarginTopOverride = 14,
            ContentMarginBottomOverride = 14,
        };
    }
}
