using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Data;

namespace Content.Client._Stalker.TopographyMap.Ui;



[GenerateTypedNameReferences]
public sealed partial class TopographyMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SpriteSystem _spriteSystem = default!;
    public event Action<BaseButton.ButtonEventArgs, string>? OnMapButtonPressed;


    public TopographyMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();

        var vScrollBar = MapContainer.GetChild(1);
        var hScrollBar = MapContainer.GetChild(2);

        vScrollBar.ModulateSelfOverride = Color.Black;
        hScrollBar.ModulateSelfOverride = Color.Black;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        MapContainer.MouseFilter = MouseFilterMode.Ignore;

        if (MapBackground.Texture == null) return;

        MapContainer.SetSize = MainWindow.Size - new Vector2(160,0);
        
        var texture = MapBackground.Texture;
        var scaleTarget = MapBackground.TextureScale + new Vector2(args.Delta.Y / 10);
        var textureMaxScale = MapContainer.Size/texture.Size;

        if (scaleTarget.X <= 0) return;
        if (scaleTarget.Y <= 0) return;
        if (scaleTarget.X <= textureMaxScale.X)
        {
            MapBackground.TextureScale = new Vector2(textureMaxScale.X,textureMaxScale.X*texture.Size.Y/texture.Size.X);
            MapBackground.SetSize = texture.Size*MapBackground.TextureScale;

            return;
        }

        MapBackground.TextureScale = scaleTarget;
        MapBackground.SetSize = texture.Size*MapBackground.TextureScale;
    }

    #region Public API

    public void UpdateBackground(string path)
    {
        var texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new(path)));

        MapContainer.SetSize = MainWindow.Size - new Vector2(160,0);
        MapBackground.Texture = texture;
        MapBackground.TextureScale = SetSize / texture.Size;
        MapBackground.SetSize = MapContainer.SetSize;
    }

    public void UpdateMapButtons(List<String> TextureNames, List<String> TexturePaths)
    {
        ButtonContainer.Children.Clear();

        for (int i = 0; i < TextureNames.Count; i++)
        {
            var MapButton = new MapButton
            {
                Text = Loc.GetString(TextureNames[i]),
                MinWidth = 160,
                MaxHeight = 48,
                TexturePath = TexturePaths[i]
            };
            MapButton.OnPressed += args => OnMapButtonPressed?.Invoke(args, MapButton.TexturePath);
            ButtonContainer.AddChild(MapButton);
        }
    }

    public sealed class MapButton : Button
    {
        public string TexturePath = "";
    }

    #endregion
}