using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Inventory;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared._Stalker_EN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Stalker_EN.Loadout;

[GenerateTypedNameReferences]
public sealed partial class LoadoutPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private HumanoidAppearanceSystem? _humanoid;
    private ClientInventorySystem? _inventory;
    private EntityUid? _previewDummy;
    private Direction _previewRotation = Direction.South;
    private SpriteView? _currentSpriteView;

    public LoadoutPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _humanoid = _entManager.System<HumanoidAppearanceSystem>();
        _inventory = _entManager.System<ClientInventorySystem>();

        RotateLeftButton.OnPressed += _ => RotatePreview(clockwise: false);
        RotateRightButton.OnPressed += _ => RotatePreview(clockwise: true);
    }

    private void RotatePreview(bool clockwise)
    {
        // Rotate through cardinal directions (South -> East -> North -> West)
        _previewRotation = clockwise
            ? (Direction)(((int)_previewRotation + 2) % 8)
            : (Direction)(((int)_previewRotation + 6) % 8);

        if (_currentSpriteView != null)
            _currentSpriteView.OverrideDirection = _previewRotation;
    }

    public void UpdatePreview(PlayerLoadout? loadout)
    {
        ClearPreview();

        if (loadout == null)
        {
            PreviewLabel.Text = Loc.GetString("loadout-preview-select");
            return;
        }

        // Get the player's current appearance if possible
        string speciesId = SharedHumanoidAppearanceSystem.DefaultSpecies;

        var player = _playerManager.LocalEntity;
        if (player != null && _entManager.TryGetComponent<HumanoidAppearanceComponent>(player, out var appearance))
        {
            speciesId = appearance.Species;
        }

        // Spawn dummy entity from species
        if (!_prototypeManager.TryIndex<SpeciesPrototype>(speciesId, out var speciesProto))
        {
            speciesProto = _prototypeManager.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies);
        }

        _previewDummy = _entManager.SpawnEntity(speciesProto.DollPrototype, MapCoordinates.Nullspace);

        // Copy appearance from player if possible
        if (player != null && _entManager.TryGetComponent<HumanoidAppearanceComponent>(player, out var playerAppearance))
        {
            if (_entManager.TryGetComponent<HumanoidAppearanceComponent>(_previewDummy.Value, out var dummyAppearance))
            {
                // Copy basic appearance properties
                _humanoid?.SetSkinColor(_previewDummy.Value, playerAppearance.SkinColor, false);
                _humanoid?.SetBaseLayerColor(_previewDummy.Value, HumanoidVisualLayers.Eyes, playerAppearance.EyeColor, false);
            }
        }

        // Equip loadout items to slots
        EquipLoadoutItems(_previewDummy.Value, loadout);

        // Create and configure SpriteView
        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = _previewRotation,
            Scale = new Vector2(5.5f, 5.5f),
            MaxSize = new Vector2(180, 180),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(_previewDummy.Value);
        ViewBox.AddChild(spriteView);
        _currentSpriteView = spriteView;

        PreviewLabel.Text = loadout.Name;
    }

    private void EquipLoadoutItems(EntityUid dummy, PlayerLoadout loadout)
    {
        if (_inventory == null)
            return;

        // Equip slot items
        foreach (var slotItem in loadout.SlotItems)
        {
            if (!_prototypeManager.HasIndex<EntityPrototype>(slotItem.PrototypeId))
                continue;

            var item = _entManager.SpawnEntity(slotItem.PrototypeId, MapCoordinates.Nullspace);
            if (!_inventory.TryEquip(dummy, item, slotItem.SlotName, true, true))
            {
                _entManager.DeleteEntity(item);
            }
        }

        // Note: Hand items are not displayed in preview since dummy doesn't have hands component setup
    }

    private void ClearPreview()
    {
        ViewBox.DisposeAllChildren();

        if (_previewDummy != null)
        {
            // Delete the dummy entity - this will also clean up any equipped items
            _entManager.DeleteEntity(_previewDummy.Value);
            _previewDummy = null;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        ClearPreview();
    }
}
