using System.Linq;
using Content.Shared._Stalker_EN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Loadout;

[GenerateTypedNameReferences]
public sealed partial class LoadoutItemControl : Control
{
    public PlayerLoadout Loadout { get; }

    public event Action<int>? OnLoadPressed;
    public event Action<int>? OnDeletePressed;
    public event Action<PlayerLoadout>? OnSelected;

    private const int MaxNameLength = 24;
    private bool _detailsExpanded;

    public LoadoutItemControl(PlayerLoadout loadout)
    {
        RobustXamlLoader.Load(this);
        Loadout = loadout;

        var name = loadout.Name;
        if (name.Length > MaxNameLength)
            name = name[..MaxNameLength] + "..";

        // Style quick save differently
        if (loadout.Id == 0)
        {
            LoadoutName.Text = $"[Quick Save]";
            LoadoutName.FontColorOverride = Color.FromHex("#FFD700");
            if (Panel.PanelOverride is StyleBoxFlat styleBox)
            {
                styleBox.BackgroundColor = Color.FromHex("#2A2A00");
                styleBox.BorderColor = Color.FromHex("#5A5A00");
            }
        }
        else
        {
            LoadoutName.Text = name;
        }

        var itemCount = loadout.GetTotalItemCount();
        LoadoutInfo.Text = Loc.GetString("loadout-item-count", ("count", itemCount));

        if (loadout.MissingCount > 0)
        {
            MissingLabel.Text = Loc.GetString("loadout-missing-items", ("count", loadout.MissingCount));
            MissingLabel.Visible = true;
            ToggleMissingDetails.Visible = true;

            // Build the missing items list with hierarchical display
            MissingDetailsContainer.AddChild(new Label
            {
                Text = Loc.GetString("loadout-missing-header"),
                FontColorOverride = Color.FromHex("#FF6B6B")
            });
            AddMissingItemsRecursive(loadout.MissingItems, 0);

            ToggleMissingDetails.OnPressed += _ =>
            {
                _detailsExpanded = !_detailsExpanded;
                MissingDetailsContainer.Visible = _detailsExpanded;
                ToggleMissingDetails.Text = _detailsExpanded ? "-" : "+";
            };
        }

        PreviewButton.OnPressed += _ => OnSelected?.Invoke(loadout);
        LoadButton.OnPressed += _ =>
        {
            OnSelected?.Invoke(loadout);
            OnLoadPressed?.Invoke(loadout.Id);
        };
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(loadout.Id);
    }

    /// <summary>
    /// Recursively adds missing items to the display with proper indentation for hierarchy.
    /// </summary>
    private void AddMissingItemsRecursive(List<MissingLoadoutItem> items, int depth)
    {
        foreach (var item in items)
        {
            var indent = new string(' ', depth * 4);  // 4 spaces per level
            var prefix = depth > 0 ? "└ " : "- ";

            var displayText = item.Count > 1
                ? $"  {indent}{prefix}{item.Count}x {item.Name}"
                : $"  {indent}{prefix}{item.Name}";

            MissingDetailsContainer.AddChild(new Label
            {
                Text = displayText,
                FontColorOverride = Color.FromHex("#FF6B6B")
            });

            // Recursively add children
            if (item.Children.Count > 0)
            {
                AddMissingItemsRecursive(item.Children, depth + 1);
            }
        }
    }
}
