using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Loadout;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Stalker_EN.Loadout;

[GenerateTypedNameReferences]
public sealed partial class LoadoutMenu : FancyWindow
{
    public event Action<string, bool>? OnSave;
    public event Action<int>? OnLoad;
    public event Action<int>? OnDelete;
    public event Action? OnQuickSave;
    public event Action? OnQuickLoad;

    private List<PlayerLoadout> _loadouts = new();
    private string _searchFilter = "";
    private PlayerLoadout? _selectedLoadout;

    public LoadoutMenu()
    {
        RobustXamlLoader.Load(this);

        HelpGuidebookIds = new List<ProtoId<GuideEntryPrototype>> { "STLoadout" };

        QuickSaveButton.OnPressed += _ => OnQuickSave?.Invoke();
        QuickLoadButton.OnPressed += _ =>
        {
            // Update preview to quick save loadout before loading
            var quickSave = _loadouts.FirstOrDefault(l => l.Id == 0);
            if (quickSave != null)
                OnLoadoutSelected(quickSave);
            OnQuickLoad?.Invoke();
        };

        SearchEdit.OnTextChanged += OnSearchChanged;

        SaveButton.OnPressed += _ =>
        {
            var name = LoadoutNameEdit.Text.Trim();
            if (!string.IsNullOrEmpty(name))
            {
                OnSave?.Invoke(name, false);
                LoadoutNameEdit.SetText(string.Empty, false);
            }
        };

        LoadoutNameEdit.OnTextEntered += args =>
        {
            var name = args.Text.Trim();
            if (!string.IsNullOrEmpty(name))
            {
                OnSave?.Invoke(name, false);
                LoadoutNameEdit.SetText(string.Empty, false);
            }
        };

        UpdateQuickLoadButtonState();
    }

    public void UpdateLoadouts(List<PlayerLoadout> loadouts)
    {
        _loadouts = loadouts;
        RefreshLoadoutList();

        // If we had a selected loadout, try to keep it selected
        if (_selectedLoadout != null)
        {
            var stillExists = loadouts.FirstOrDefault(l => l.Id == _selectedLoadout.Id);
            if (stillExists != null)
            {
                _selectedLoadout = stillExists;
                PreviewPanel.UpdatePreview(_selectedLoadout);
            }
        }
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _searchFilter = args.Text.Trim().ToLowerInvariant();
        RefreshLoadoutList();
    }

    private void RefreshLoadoutList()
    {
        LoadoutList.RemoveAllChildren();

        var filtered = string.IsNullOrEmpty(_searchFilter)
            ? _loadouts
            : _loadouts.Where(l => l.Name.ToLowerInvariant().Contains(_searchFilter));

        foreach (var loadout in filtered)
        {
            var control = new LoadoutItemControl(loadout);
            control.OnLoadPressed += id => OnLoad?.Invoke(id);
            control.OnDeletePressed += id => OnDelete?.Invoke(id);
            control.OnSelected += OnLoadoutSelected;
            LoadoutList.AddChild(control);
        }

        UpdateQuickLoadButtonState();
    }

    private void OnLoadoutSelected(PlayerLoadout loadout)
    {
        _selectedLoadout = loadout;
        PreviewPanel.UpdatePreview(loadout);
    }

    private void UpdateQuickLoadButtonState()
    {
        var hasQuickSave = _loadouts.Any(l => l.Id == 0);
        QuickLoadButton.Disabled = !hasQuickSave;
    }
}
