using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting.UI.Controls;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IClyde _clyde = default!;

    private static readonly Color WeaponAccent = PersistentCraftUiTheme.WeaponAccent;
    private static readonly Color ArmorAccent = PersistentCraftUiTheme.ArmorAccent;
    private static readonly Color AnomalyAccent = PersistentCraftUiTheme.AnomalyAccent;
    private static readonly Color PanelBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardBackground = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color CardUnlockedBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardLockedBackground = PersistentCraftUiTheme.SurfacePanelSoft;
    private static readonly Color CardAvailableBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color AvailableBorder = PersistentCraftUiTheme.BorderStrong;
    private static readonly Color UnlockedBorder = PersistentCraftUiTheme.Success;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color HeaderTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color MutedTextColor = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private const float TierTreeNodeWidth = 176f;
    private const float TierTreeNodeHeight = 178f;
    private const float TierTreeHorizontalGap = 56f;
    private const float TierTreeVerticalGap = 36f;
    private const float TierTreePadding = 24f;
    private const float TierTreeLineThickness = 3f;
    private const float NodeDetailsWindowWidth = 860f;
    private const float NodeDetailsWindowHeight = 720f;
    private const float NodeDetailsWindowMinWidth = 700f;
    private const float NodeDetailsWindowMinHeight = 560f;
    private const float NodeDetailsWindowMargin = 16f;

    private readonly Dictionary<PersistentCraftBranch, string> _selectedNodeByBranch = new();
    private bool _selectPreferredBranchOnNextUpdate = true;

    private PersistentCraftState? _state;
    private List<PersistentCraftNodePrototype> _nodes = new();
    private List<PersistentCraftRecipePrototype> _recipes = new();
    private Action<string>? _onUnlock;
    private DefaultWindow? _nodeDetailsWindow;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        Branches.SetTabTitle(0, Loc.GetString("persistent-craft-branch-weapon"));
        Branches.SetTabTitle(1, Loc.GetString("persistent-craft-branch-armor"));
        Branches.SetTabTitle(2, Loc.GetString("persistent-craft-branch-anomaly"));
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-skill-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        Branches.OnTabChanged += _ =>
        {
            CloseNodeDetailsWindow();
            RenderBranch(GetCurrentBranch());
        };
    }

    public override void Close()
    {
        CloseNodeDetailsWindow();
        base.Close();
    }

    public void UpdateState(
        PersistentCraftState state,
        IEnumerable<PersistentCraftNodePrototype> nodes,
        IEnumerable<PersistentCraftRecipePrototype> recipes,
        Action<string> onUnlock)
    {
        _state = state;
        _nodes = nodes
            .OrderBy(node => node.Branch)
            .ThenBy(node => node.TreeRow >= 0 ? node.TreeRow : int.MaxValue)
            .ThenBy(node => node.TreeColumn >= 0 ? node.TreeColumn : int.MaxValue)
            .ThenBy(node => node.ID)
            .ToList();
        _recipes = recipes
            .OrderBy(recipe => recipe.Branch)
            .ThenBy(recipe => recipe.Tier)
            .ThenBy(recipe => recipe.ID)
            .ToList();
        _onUnlock = onUnlock;

        if (state.Loaded && _selectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _selectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _selectPreferredBranchOnNextUpdate = true;
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderBranch(GetCurrentBranch());
    }

    private void RenderBranch(PersistentCraftBranch branch)
    {
        var subNodeHost = GetBranchHost(branch);
        subNodeHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchNodes = _nodes.Where(node => node.Branch == branch).ToList();
        var branchSubNodes = branchNodes
            .OrderBy(node => node.TreeRow >= 0 ? node.TreeRow : int.MaxValue)
            .ThenBy(node => node.TreeColumn >= 0 ? node.TreeColumn : int.MaxValue)
            .ThenBy(node => node.ID)
            .ToList();

        if (branchSubNodes.Count == 0)
        {
            CloseNodeDetailsWindow();
            return;
        }

        var branchState = GetBranchState(_state, branch);
        var selectedNode = ResolveSelectedNode(branch, branchSubNodes);

        subNodeHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-tree-label")));
        subNodeHost.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}",
            FontColorOverride = GetBranchAccent(branch),
        });
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        if (branchSubNodes.Count == 0)
        {
            subNodeHost.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedTextColor,
            });
        }
        else
        {
            subNodeHost.AddChild(CreateSubNodeTree(branch, branchSubNodes, selectedNode?.ID));
        }

        if (selectedNode == null)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_nodeDetailsWindow != null &&
            !_nodeDetailsWindow.Disposed &&
            _nodeDetailsWindow.IsOpen)
        {
            ShowNodeDetailsWindow(branchState, selectedNode);
        }
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private BoxContainer CreateSubNodeTree(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes,
        string? selectedNodeId)
    {
        var accent = GetBranchAccent(branch);
        var positions = subNodes.ToDictionary(node => node.ID, GetNodeTreePosition);
        var maxColumn = positions.Values.Max(position => position.X);
        var maxRow = positions.Values.Max(position => position.Y);

        var layout = new LayoutContainer
        {
            MinSize = new Vector2(
                TierTreePadding * 2 + (maxColumn + 1) * TierTreeNodeWidth + maxColumn * TierTreeHorizontalGap,
                TierTreePadding * 2 + (maxRow + 1) * TierTreeNodeHeight + maxRow * TierTreeVerticalGap + 20),
            HorizontalAlignment = HAlignment.Center,
        };

        foreach (var node in subNodes)
        {
            var childPosition = GetNodeCanvasPosition(positions[node.ID]);
            var childCenter = GetNodeCenter(childPosition);

            var visualParents = GetVisualPrerequisiteIds(
                node,
                subNodes,
                allowImplicitFallback: node.TreeColumn < 0 || node.TreeRow < 0).ToList();
            foreach (var prerequisiteId in visualParents)
            {
                if (!positions.TryGetValue(prerequisiteId, out var parentGridPosition))
                    continue;

                var parentPosition = GetNodeCanvasPosition(parentGridPosition);
                var parentCenter = GetNodeCenter(parentPosition);
                AddConnector(layout, parentCenter, childCenter, accent);
            }

        }

        foreach (var node in subNodes)
        {
            var control = CreateSubNodeEntry(branch, node, selectedNodeId == node.ID);
            control.MinSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight);
            control.MaxSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight);
            LayoutContainer.SetPosition(control, GetNodeCanvasPosition(positions[node.ID]));
            layout.AddChild(control);
        }

        var wrapper = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };
        wrapper.AddChild(layout);
        return wrapper;
    }

    private Vector2i GetNodeTreePosition(PersistentCraftNodePrototype node)
    {
        if (node.TreeColumn >= 0 && node.TreeRow >= 0)
            return new Vector2i(node.TreeColumn, node.TreeRow);

        // Fallback placement for legacy nodes without explicit tree coordinates.
        var hashSeed = node.ID.Aggregate(0, (acc, ch) => acc + ch);
        var localColumn = Math.Abs(hashSeed % 8);
        var localRow = Math.Abs((hashSeed / 3) % 3);
        return new Vector2i(localColumn, localRow);
    }

    private static IEnumerable<string> GetVisualPrerequisiteIds(
        PersistentCraftNodePrototype node,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes,
        bool allowImplicitFallback = true)
    {
        var subNodeIds = subNodes.Select(item => item.ID).ToHashSet();
        _ = allowImplicitFallback;
        return node.Prerequisites.Where(subNodeIds.Contains).ToList();
    }

    private static Vector2 GetNodeCanvasPosition(Vector2i gridPosition)
    {
        return new Vector2(
            TierTreePadding + gridPosition.X * (TierTreeNodeWidth + TierTreeHorizontalGap),
            TierTreePadding + gridPosition.Y * (TierTreeNodeHeight + TierTreeVerticalGap));
    }

    private static Vector2 GetNodeCenter(Vector2 canvasPosition)
    {
        return new Vector2(
            canvasPosition.X + TierTreeNodeWidth / 2f,
            canvasPosition.Y + TierTreeNodeHeight / 2f);
    }

    private static void AddConnector(LayoutContainer layout, Vector2 parentCenter, Vector2 childCenter, Color accent)
    {
        var connectorColor = accent.WithAlpha(0.35f);
        var parentBottom = parentCenter.Y + TierTreeNodeHeight / 2f;
        var childTop = childCenter.Y - TierTreeNodeHeight / 2f;
        var midY = parentBottom + (childTop - parentBottom) / 2f;

        AddLine(layout, parentCenter.X, parentBottom, parentCenter.X, midY, connectorColor);
        AddLine(layout, Math.Min(parentCenter.X, childCenter.X), midY, Math.Max(parentCenter.X, childCenter.X), midY, connectorColor);
        AddLine(layout, childCenter.X, midY, childCenter.X, childTop, connectorColor);
    }

    private static void AddLine(LayoutContainer layout, float startX, float startY, float endX, float endY, Color color)
    {
        var isVertical = Math.Abs(startX - endX) < 0.01f;
        var minX = isVertical
            ? startX - TierTreeLineThickness / 2f
            : Math.Min(startX, endX);
        var minY = isVertical
            ? Math.Min(startY, endY)
            : startY - TierTreeLineThickness / 2f;
        var width = isVertical
            ? TierTreeLineThickness
            : Math.Max(Math.Abs(endX - startX), TierTreeLineThickness);
        var height = isVertical
            ? Math.Max(Math.Abs(endY - startY), TierTreeLineThickness)
            : TierTreeLineThickness;

        var line = new PanelContainer
        {
            MinSize = new Vector2(width, height),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
            }
        };

        LayoutContainer.SetPosition(line, new Vector2(minX, minY));
        layout.AddChild(line);
    }

    private ContainerButton CreateSubNodeEntry(PersistentCraftBranch branch, PersistentCraftNodePrototype node, bool selected)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var branchState = GetBranchState(state, branch);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var canUnlock = state.Loaded && !unlocked && prerequisitesMet && branchState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(branch);

        var button = new ContainerButton
        {
            MinSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight),
            MaxSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight),
            HorizontalExpand = false,
            VerticalExpand = false,
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = unlocked ? CardUnlockedBackground : canUnlock ? CardAvailableBackground : CardLockedBackground,
                BorderColor = selected ? SelectedBorder : unlocked ? UnlockedBorder : canUnlock ? accent.WithAlpha(0.6f) : CardBorder,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 12,
                ContentMarginRightOverride = 12,
                ContentMarginTopOverride = 12,
                ContentMarginBottomOverride = 12,
            }
        };
        button.OnPressed += _ => SelectNode(branch, node.ID);

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.AddChild(CreateNodeIcon(node, selected ? SelectedBorder : accent, new Vector2(64, 64)));
        body.AddChild(new Control { MinSize = new Vector2(1, 8) });

        var namePlate = new PanelContainer
        {
            HorizontalExpand = true,
            MinSize = new Vector2(0, 26),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground.WithAlpha(0.45f),
                BorderColor = CardBorder.WithAlpha(0.55f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            }
        };

        var nameLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        nameLabel.SetMarkup($"[color={HeaderTextColor.ToHex()}]{FormattedMessage.EscapeText(ResolveNodeCardCaption(node))}[/color]");
        namePlate.AddChild(nameLabel);
        body.AddChild(namePlate);
        body.AddChild(new Control { VerticalExpand = true });

        button.AddChild(body);
        return button;
    }

    private PanelContainer CreateDetailsPanel(
        PersistentCraftBranchState branchState,
        PersistentCraftNodePrototype node)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var canUnlock = state.Loaded &&
                        !unlocked &&
                        prerequisitesMet &&
                        branchState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(node.Branch);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = false,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PanelBackground,
                BorderColor = accent.WithAlpha(0.5f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 18,
                ContentMarginRightOverride = 18,
                ContentMarginTopOverride = 18,
                ContentMarginBottomOverride = 18,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var headerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var canAttemptUnlock = state.Loaded && !unlocked;

        var headerLeft = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            MinSize = new Vector2(136, 0),
        };

        headerLeft.AddChild(CreateNodeIcon(node, accent, new Vector2(120, 120)));
        headerLeft.AddChild(new Control { MinSize = new Vector2(1, 8) });
        headerLeft.AddChild(new Label
        {
            Text = Loc.GetString("persistent-craft-node-branch-points", ("points", branchState.AvailablePoints)),
            FontColorOverride = MutedTextColor,
            HorizontalAlignment = HAlignment.Center,
        });
        headerLeft.AddChild(new Control { MinSize = new Vector2(1, 8) });

        var unlockButton = new Button
        {
            Text = GetActionText(unlocked),
            Disabled = !canAttemptUnlock,
            MinSize = new Vector2(0, 42),
            HorizontalExpand = true,
        };
        unlockButton.OnPressed += _ => _onUnlock?.Invoke(node.ID);
        headerLeft.AddChild(unlockButton);

        headerRow.AddChild(headerLeft);
        headerRow.AddChild(new Control { MinSize = new Vector2(18, 1) });

        var headerText = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        headerText.AddChild(new Label
        {
            Text = ResolveNodeName(node),
            FontColorOverride = HeaderTextColor,
            ClipText = true,
        });
        headerText.AddChild(new Control { MinSize = new Vector2(1, 8) });

        var meta = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        meta.SetMarkup(
            $"[color={MutedTextColor.ToHex()}]{Loc.GetString("persistent-craft-selected-branch", ("branch", Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(node.Branch))))}\n" +
            $"{Loc.GetString("persistent-craft-spent-points-label")}: {branchState.SpentPoints}\n" +
            $"{Loc.GetString("persistent-craft-node-cost", ("cost", node.Cost))} | " +
            $"{Loc.GetString(GetDetailStatusKey(unlocked, prerequisitesMet, canUnlock))}[/color]");
        headerText.AddChild(meta);
        headerRow.AddChild(headerText);

        body.AddChild(headerRow);
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-rewards-label"),
            BuildRewardMarkup(node)));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });
        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-requirements-label"),
            BuildRequirementMarkup(node)));
        panel.AddChild(body);
        return panel;
    }

    private void ShowNodeDetailsWindow(PersistentCraftBranchState branchState, PersistentCraftNodePrototype node)
    {
        if (_nodeDetailsWindow == null || _nodeDetailsWindow.Disposed)
        {
            _nodeDetailsWindow = new DefaultWindow
            {
                SetSize = new Vector2(NodeDetailsWindowWidth, NodeDetailsWindowHeight),
                MinSize = new Vector2(NodeDetailsWindowMinWidth, NodeDetailsWindowMinHeight),
                Resizable = true,
            };
            _nodeDetailsWindow.OnClose += () => _nodeDetailsWindow = null;
        }

        _nodeDetailsWindow.Title = ResolveNodeName(node);
        _nodeDetailsWindow.RemoveAllChildren();

        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            HorizontalExpand = true,
            VerticalExpand = false,
        };
        root.AddChild(CreateDetailsPanel(branchState, node));

        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false,
            VScrollEnabled = true,
        };
        scroll.AddChild(root);

        _nodeDetailsWindow.AddChild(scroll);
        if (!_nodeDetailsWindow.IsOpen)
            _nodeDetailsWindow.Open();

        PositionNodeDetailsWindowTopRight();
        _nodeDetailsWindow.MoveToFront();
    }

    private void PositionNodeDetailsWindowTopRight()
    {
        if (_nodeDetailsWindow == null || _nodeDetailsWindow.Disposed)
            return;

        var screen = _clyde.ScreenSize;
        var windowWidth = _nodeDetailsWindow.Width > 0 ? _nodeDetailsWindow.Width : (int)NodeDetailsWindowWidth;
        var x = Math.Max(NodeDetailsWindowMargin, screen.X - windowWidth - NodeDetailsWindowMargin);
        var y = NodeDetailsWindowMargin;
        LayoutContainer.SetPosition(_nodeDetailsWindow, new Vector2(x, y));
    }

    private void CloseNodeDetailsWindow()
    {
        if (_nodeDetailsWindow == null || _nodeDetailsWindow.Disposed)
            return;

        _nodeDetailsWindow.Close();
        _nodeDetailsWindow = null;
    }

    private Control CreateDetailSection(string title, string contentMarkup)
    {
        var section = new PersistentCraftTextSection();
        section.SetData(title, contentMarkup, CardBorder, 12);
        return section;
    }

    private PanelContainer CreateNodeIcon(PersistentCraftNodePrototype node, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            VerticalExpand = false,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Top,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            }
        };

        if (TryGetNodeTexture(node, out var texture))
        {
            panel.AddChild(new TextureRect
            {
                Texture = texture,
                TextureScale = size.X >= 100 ? new Vector2(2.1f, 2.1f) : new Vector2(1.25f, 1.25f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            panel.AddChild(new Label
            {
                Text = ResolveNodeName(node),
                FontColorOverride = HeaderTextColor,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            });
        }

        return panel;
    }

    private string BuildRewardMarkup(PersistentCraftNodePrototype node)
    {
        var recipes = FindRecipesForNode(node).ToList();
        if (recipes.Count == 0)
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

        return string.Join("\n", recipes.Select(recipe =>
            $"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveRecipeName(recipe))}[/color]"));
    }

    private string BuildRequirementMarkup(PersistentCraftNodePrototype node)
    {
        var lines = new List<string>();

        foreach (var prerequisiteId in node.Prerequisites)
        {
            var prerequisite = _nodes.FirstOrDefault(item => item.ID == prerequisiteId);
            if (prerequisite == null)
            {
                lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(prerequisiteId)}[/color]");
                continue;
            }

            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(prerequisite))}[/color]");
        }

        if (lines.Count == 0)
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

        return string.Join("\n", lines);
    }

    private PersistentCraftNodePrototype? ResolveSelectedNode(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        if (_selectedNodeByBranch.TryGetValue(branch, out var selectedId))
        {
            var existing = subNodes.FirstOrDefault(node => node.ID == selectedId);
            if (existing != null)
                return existing;

            _selectedNodeByBranch.Remove(branch);
        }

        return null;
    }

    private void SelectNode(PersistentCraftBranch branch, string nodeId)
    {
        if (_selectedNodeByBranch.TryGetValue(branch, out var selectedId) &&
            selectedId == nodeId &&
            _nodeDetailsWindow != null &&
            !_nodeDetailsWindow.Disposed &&
            _nodeDetailsWindow.IsOpen)
        {
            _selectedNodeByBranch.Remove(branch);
            CloseNodeDetailsWindow();
            return;
        }

        _selectedNodeByBranch[branch] = nodeId;

        if (_state == null)
            return;

        var node = _nodes.FirstOrDefault(item => item.Branch == branch && item.ID == nodeId);
        if (node == null)
            return;

        var branchState = GetBranchState(_state, branch);
        ShowNodeDetailsWindow(branchState, node);
    }

    private IEnumerable<PersistentCraftRecipePrototype> FindRecipesForNode(PersistentCraftNodePrototype node)
    {
        return _recipes.Where(recipe => recipe.RequiredNode == node.ID);
    }

    private bool TryGetNodeTexture(PersistentCraftNodePrototype node, out Texture? texture)
    {
        texture = null;

        var displayProto = node.DisplayProto;
        if (string.IsNullOrWhiteSpace(displayProto))
        {
            var recipe = FindRecipesForNode(node).FirstOrDefault();
            displayProto = recipe == null ? null : PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        }

        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            if (Loc.TryGetString(node.Name, out var localizedNodeName) &&
                !string.IsNullOrWhiteSpace(localizedNodeName))
            {
                return localizedNodeName;
            }

            if (!string.IsNullOrWhiteSpace(node.Name))
                return node.Name;
        }

        if (!string.IsNullOrWhiteSpace(node.DisplayProto) &&
            _prototype.TryIndex<EntityPrototype>(node.DisplayProto, out var prototype))
        {
            if (!string.IsNullOrWhiteSpace(prototype.Name))
            {
                return prototype.Name;
            }

            if (Loc.TryGetString($"ent-{prototype.ID}", out var localizedPrototypeName) &&
                !string.IsNullOrWhiteSpace(localizedPrototypeName))
            {
                return localizedPrototypeName;
            }

            return prototype.ID;
        }

        if (!string.IsNullOrWhiteSpace(node.DisplayProto))
            return node.DisplayProto;

        return node.ID;
    }

    private string ResolveNodeCardCaption(PersistentCraftNodePrototype node)
    {
        var resolved = ResolveNodeName(node).Trim();
        if (!string.IsNullOrWhiteSpace(resolved))
            return resolved;

        if (!string.IsNullOrWhiteSpace(node.DisplayProto))
            return node.DisplayProto;

        return node.ID;
    }

    private string GetDetailStatusKey(
        bool unlocked,
        bool prerequisitesMet,
        bool canUnlock)
    {
        if (_state?.Loaded != true)
            return "persistent-craft-node-status-loading";

        if (unlocked)
            return "persistent-craft-node-status-unlocked";

        if (canUnlock)
            return "persistent-craft-node-status-available";

        if (!prerequisitesMet)
            return "persistent-craft-node-status-locked";

        return "persistent-craft-node-status-locked";
    }

    private string GetActionText(bool unlocked)
    {
        if (_state?.Loaded != true)
            return Loc.GetString("persistent-craft-node-status-loading");

        if (unlocked)
            return Loc.GetString("persistent-craft-node-status-unlocked");

        return Loc.GetString("persistent-craft-node-action-unlock");
    }

    private void SelectPreferredBranchTab()
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        var preferred = PersistentCraftingHelper.EnumerateBranches()
            .Select(branch => new
            {
                Branch = branch,
                Points = GetBranchState(state, branch).AvailablePoints,
            })
            .OrderByDescending(entry => entry.Points)
            .FirstOrDefault(entry => entry.Points > 0);

        if (preferred != null)
            Branches.CurrentTab = GetBranchTabIndex(preferred.Branch);
    }

    private static int GetBranchTabIndex(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => 0,
            PersistentCraftBranch.Armor => 1,
            PersistentCraftBranch.Anomaly => 2,
            _ => 0,
        };
    }

    private PersistentCraftBranch GetCurrentBranch()
    {
        return Branches.CurrentTab switch
        {
            1 => PersistentCraftBranch.Armor,
            2 => PersistentCraftBranch.Anomaly,
            _ => PersistentCraftBranch.Weapon,
        };
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId)
    {
        if (_state == null)
            return false;

        return HasNodeUnlockedOrAutoAvailable(nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId, HashSet<string> path)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
            return false;

        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (node.Cost > 0)
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private BoxContainer GetBranchHost(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => WeaponSubNodeHost,
            PersistentCraftBranch.Armor => ArmorSubNodeHost,
            PersistentCraftBranch.Anomaly => AnomalySubNodeHost,
            _ => WeaponSubNodeHost,
        };
    }

    private PersistentCraftBranchState GetBranchState(PersistentCraftState state, PersistentCraftBranch branch)
    {
        return state.BranchStates.FirstOrDefault(item => item.Branch == branch) ??
               new PersistentCraftBranchState(
                   branch,
                   0,
                   0);
    }

    private static Color GetBranchAccent(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => WeaponAccent,
            PersistentCraftBranch.Armor => ArmorAccent,
            PersistentCraftBranch.Anomaly => AnomalyAccent,
            _ => CardBorder,
        };
    }
}
