using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using Content.Client._Stalker.PersistentCrafting;
using Content.Client._Stalker.PersistentCrafting.UI.Coordinators;
using Content.Client._Stalker.PersistentCrafting.UI.Indexes;
using Content.Client._Stalker.PersistentCrafting.UI.Controls;
using Content.Client._Stalker.PersistentCrafting.UI.ViewModels;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftStationWindow : DefaultWindow
{
    private sealed record RecipeEntryControls(ContainerButton Button, PanelContainer IconPanel);

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    private readonly TagSystem _tag;

    private static readonly Color WindowBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color CardMutedBorder = PersistentCraftUiTheme.BorderSoft;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private static readonly Color MutedText = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionText = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color EnoughColor = PersistentCraftUiTheme.Success;
    private static readonly Color MissingColor = PersistentCraftUiTheme.Danger;

    private readonly Dictionary<string, BoxContainer> _branchContainers = new();
    private readonly Dictionary<string, ScrollContainer> _activeListScrollByBranch = new();
    private readonly Dictionary<string, ScrollContainer> _activeDetailScrollByBranch = new();
    private readonly Dictionary<string, Dictionary<string, RecipeEntryControls>> _recipeEntryControlsByBranch = new();
    private readonly Dictionary<string, BoxContainer> _detailContentHostsByBranch = new();
    private readonly Dictionary<string, PersistentCraftBranchState> _visibleBranchStatesByBranch = new();
    private readonly Dictionary<string, bool> _recipeCraftabilityById = new();
    private readonly HashSet<string> _pendingScrollRestoreBranches = new();
    private readonly PersistentCraftStationViewModel _viewModel = new();
    private readonly PersistentCraftStationBranchCoordinator _branchCoordinator;

    private PersistentCraftRecipeIndex? _recipeIndex;
    private PersistentCraftRecipeMetadataIndex _recipeMetadataIndex = PersistentCraftRecipeMetadataIndex.Empty;
    private PersistentCraftInventorySnapshot _inventorySnapshot = PersistentCraftInventorySnapshot.Empty;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private PersistentCraftState? _state;
    private IReadOnlyList<PersistentCraftRecipePrototype> _recipes = Array.Empty<PersistentCraftRecipePrototype>();

    public event Action<string>? OnCraftPressed;
    public event Action<string, int>? OnCraftBatchPressed;
    public event Action? OnOpenSkillsPressed;

    public PersistentCraftStationWindow()
    {
        IoCManager.InjectDependencies(this);
        _tag = _entityManager.EntitySysManager.GetEntitySystem<TagSystem>();
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);
        _branchCoordinator = new PersistentCraftStationBranchCoordinator(_branchRegistry, _branchContainers);

        RobustXamlLoader.Load(this);

        InitializeBranchContainers();
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-menu-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        OpenSkillsButton.OnPressed += _ => OnOpenSkillsPressed?.Invoke();

        Branches.OnTabChanged += _ =>
        {
            if (_state == null)
                return;
            RememberBranchScroll(_viewModel.LastVisibleBranch);
            var branch = GetCurrentBranch();
            PopulateBranch(GetBranchContainer(branch), branch);
            _viewModel.LastVisibleBranch = branch;
        };
    }

    public void UpdateState(PersistentCraftState state, PersistentCraftClientPrototypeCache prototypeCache)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _recipeIndex = PersistentCraftRecipeIndex.Create(prototypeCache);
            _branchRegistry = prototypeCache.BranchRegistry;
            _branchCoordinator.SetBranchRegistry(_branchRegistry);
            _recipeMetadataIndex = PersistentCraftRecipeMetadataIndex.Build(
                prototypeCache.AllRecipes,
                ResolveRecipeNameCore,
                ResolveRecipeDescriptionCore,
                ComputeRecipeCategoryId,
                ComputeRecipeSubCategoryId,
                ResolveCategoryPath,
                PersistentCraftingHelper.GetTierDisplayLabel);
            InitializeBranchContainers();
        }

        _state = state;
        _recipes = prototypeCache.AllRecipes;
        _branchCoordinator.RebuildBranchStateIndex(state);
        _inventorySnapshot = BuildInventorySnapshot(_recipes);

        if (state.Loaded && _viewModel.SelectPreferredBranchOnNextUpdate)
        {
            _branchCoordinator.SelectPreferredBranchTab(Branches, branch => GetAvailableRecipeCount(state, branch));
            _viewModel.SelectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _viewModel.SelectPreferredBranchOnNextUpdate = true;
    }

    public void RefreshLocalInventory()
    {
        if (_state == null)
            return;

        var newSnapshot = BuildInventorySnapshot(_recipes);
        if (newSnapshot.Signature == _inventorySnapshot.Signature)
            return;

        _inventorySnapshot = newSnapshot;

        // Rebuild only the currently visible branch to avoid flickering
        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
        _viewModel.LastVisibleBranch = branch;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_pendingScrollRestoreBranches.Count == 0)
            return;

        var branches = new string[_pendingScrollRestoreBranches.Count];
        _pendingScrollRestoreBranches.CopyTo(branches);
        _pendingScrollRestoreBranches.Clear();

        for (var i = 0; i < branches.Length; i++)
        {
            var branch = branches[i];

            if (_activeListScrollByBranch.TryGetValue(branch, out var listScroll) &&
                _viewModel.ListScrollByBranch.TryGetValue(branch, out var listScrollValue))
            {
                listScroll.SetScrollValue(listScrollValue);
            }

            if (_activeDetailScrollByBranch.TryGetValue(branch, out var detailScroll) &&
                _viewModel.DetailScrollByBranch.TryGetValue(branch, out var detailScrollValue))
            {
                detailScroll.SetScrollValue(detailScrollValue);
            }
        }
    }

    private void Render()
    {
        if (_state == null)
            return;

        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
        _viewModel.LastVisibleBranch = branch;
    }

    private void PopulateBranch(BoxContainer container, string branch)
    {
        RememberBranchScroll(branch);
        container.RemoveAllChildren();

        if (_state == null)
            return;

        var branchRecipes = GetRecipesForBranch(branch);

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var branchState = GetBranchState(branch);
        _visibleBranchStatesByBranch[branch] = branchState;
        _recipeEntryControlsByBranch[branch] = new Dictionary<string, RecipeEntryControls>();
        var unlockedRecipes = _state.Loaded
            ? FilterUnlockedRecipes(_state, branchRecipes)
            : new List<PersistentCraftRecipePrototype>();

        container.AddChild(CreateBranchHeader(branch, branchState, unlockedRecipes.Count, branchRecipes.Count));
        container.AddChild(new Control { MinSize = new Vector2(1, 12) });

        if (!_state.Loaded)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-window-loading-points"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (unlockedRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var selectedTier = GetSelectedTierFilter(branch, unlockedRecipes);

        var filteredRecipes = selectedTier > 0
            ? FilterRecipesByTier(unlockedRecipes, selectedTier)
            : unlockedRecipes;
        var searchText = GetSearchText(branch);
        filteredRecipes = ApplyRecipeSearch(filteredRecipes, searchText);
        var craftableOnly = GetCraftableOnly(branch);
        _recipeCraftabilityById.Clear();
        var craftableCount = IndexRecipeCraftability(filteredRecipes);
        filteredRecipes = ApplyCraftableFilter(filteredRecipes, craftableOnly, _recipeCraftabilityById);

        var workspace = new PersistentCraftRecipeWorkspace();
        workspace.SetAccent(GetAccent(branch));
        workspace.FilterContainer.AddChild(CreateFilterToolbar(branch, searchText, craftableOnly));
        workspace.TierFilterContainer.AddChild(CreateTierFilterRow(branch, unlockedRecipes, selectedTier, GetAccent(branch)));
        workspace.SummaryContainer.AddChild(CreateRecipeListSummary(selectedTier, filteredRecipes.Count, craftableCount, craftableOnly, GetAccent(branch)));
        var listScroll = workspace.RecipeListScroll;

        if (filteredRecipes.Count > 0)
        {
            var selected = ResolveSelectedRecipe(branch, filteredRecipes);
            workspace.ListContainer.AddChild(CreateRecipeList(branch, filteredRecipes, selected, GetAccent(branch)));
            workspace.DetailContainer.AddChild(CreateRecipeDetailsPanel(selected, branchState));
            _detailContentHostsByBranch[branch] = workspace.DetailContainer;
        }
        else
        {
            workspace.ListContainer.AddChild(CreateEmptyRecipeListMessage(searchText, craftableOnly));
            workspace.DetailContainer.AddChild(CreateEmptyDetailPanel(searchText, craftableOnly));
            _detailContentHostsByBranch[branch] = workspace.DetailContainer;
        }

        _activeListScrollByBranch[branch] = listScroll;
        _activeDetailScrollByBranch[branch] = workspace.RecipeDetailScroll;
        container.AddChild(workspace);
        RestoreBranchScroll(branch, listScroll, workspace.RecipeDetailScroll);
    }

    private bool TryGetRecipeTexture(PersistentCraftRecipePrototype recipe, out Texture? texture)
    {
        texture = null;
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private bool HasRequirement(PersistentCraftState state, PersistentCraftRecipePrototype recipe)
    {
        return HasNodeUnlockedOrAutoAvailable(state, recipe.RequiredNode);
    }

    private string GetRequirementText(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            return ResolveNodeName(node);
        }

        return $"{ResolveBranchTitle(recipe.Branch)} {PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier)}";
    }

    private bool CanViewRecipe(PersistentCraftRecipePrototype recipe)
    {
        return _state != null && HasRequirement(_state, recipe);
    }

    private Color GetRecipeMetaColor(PersistentCraftRecipePrototype recipe)
    {
        var loaded = _state?.Loaded == true;
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var hasMaterials = GetHasLocalMaterials(recipe);
        var canCraft = loaded && requirementMet && hasMaterials;
        var accent = GetAccent(recipe.Branch);

        return !requirementMet
            ? MissingColor
            : canCraft
                ? accent
                : hasMaterials
                    ? MutedText
                    : MissingColor;
    }

    private string BuildRecipeSecondaryLine(PersistentCraftRecipePrototype recipe)
    {
        var category = GetSubCategoryName(GetRecipeSubCategoryId(recipe));
        if (string.IsNullOrWhiteSpace(category))
            category = GetCategoryName(GetRecipeCategoryId(recipe));

        return $"{PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier)} | {category}";
    }

    private Control CreateRecipeStatusBadge(PersistentCraftRecipePrototype recipe)
    {
        var statusKey = GetStatusKey(_state?.Loaded == true, _state != null && HasRequirement(_state, recipe), GetHasLocalMaterials(recipe));
        var foreground = GetRecipeMetaColor(recipe);
        var background = foreground.WithAlpha(0.16f);

        var badge = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = background.WithAlpha(0.9f),
                BorderColor = foreground.WithAlpha(0.45f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            }
        };
        badge.AddChild(new Label
        {
            Text = Loc.GetString(statusKey),
            FontColorOverride = foreground,
            ClipText = true,
        });

        return badge;
    }

    private void ApplyRecipeEntryVisuals(
        ContainerButton button,
        PanelContainer iconPanel,
        PersistentCraftRecipePrototype recipe,
        bool selected)
    {
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var accent = GetAccent(recipe.Branch);
        var background = requirementMet ? PersistentCraftUiTheme.SurfacePanel : PersistentCraftUiTheme.SurfacePanelSoft;
        var border = selected ? SelectedBorder : requirementMet ? accent.WithAlpha(0.55f) : CardBorder;

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(selected ? 2 : 1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 10,
            ContentMarginBottomOverride = 10,
        };

        iconPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = IconBackground,
            BorderColor = selected ? SelectedBorder : accent.WithAlpha(0.65f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    private string BuildRecipeMasteryBadge(PersistentCraftRecipePrototype recipe)
    {
        if (_state == null)
            return Loc.GetString("persistent-craft-node-branch-points", ("points", 0));

        var branchState = GetBranchState(recipe.Branch);
        return Loc.GetString("persistent-craft-node-branch-points", ("points", branchState.AvailablePoints));
    }

    private string BuildHeaderInfoMarkup(PersistentCraftRecipePrototype recipe)
    {
        var resultText = recipe.Results.Count == 0
            ? Loc.GetString("persistent-craft-none")
            : FormatResult(recipe.Results[0]);

        return $"[color={DescriptionText.ToHex()}]{FormattedMessage.EscapeText(resultText)}[/color]\n" +
               $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-time")}: {GetEffectiveCraftTime(recipe):0.#} {Loc.GetString("persistent-craft-recipe-seconds")}[/color]";
    }

    private string BuildRequirementMarkup(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            var lines = new List<string>
            {
                $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(node))}[/color]"
            };

            return string.Join("\n", lines);
        }

        return $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(GetRequirementText(recipe))}[/color]";
    }


    private bool TryResolveRequirementNode(PersistentCraftRecipePrototype recipe, out PersistentCraftNodePrototype node)
    {
        if (TryGetNodePrototype(recipe.RequiredNode, out var resolvedNode))
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private int GetAvailableRecipeCount(PersistentCraftState state, string branch)
    {
        var recipes = GetRecipesForBranch(branch);
        var availableRecipeCount = 0;

        for (var i = 0; i < recipes.Count; i++)
        {
            if (HasRequirement(state, recipes[i]))
                availableRecipeCount++;
        }

        return availableRecipeCount;
    }

    private string GetRecipeCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeMetadataIndex.TryGetCategoryId(recipe.ID, out var categoryId))
            return categoryId;

        return ComputeRecipeCategoryId(recipe);
    }

    private string GetRecipeSubCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeMetadataIndex.TryGetSubCategoryId(recipe.ID, out var subCategoryId))
            return subCategoryId;

        return ComputeRecipeSubCategoryId(recipe);
    }

    private string ComputeRecipeCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.Category))
            return recipe.Category!;

        return _branchRegistry.TryGetBranchDefinition(recipe.Branch, out var definition)
            ? definition.DefaultCategory
            : string.Empty;
    }

    private string ComputeRecipeSubCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.SubCategory))
            return recipe.SubCategory!;

        return _branchRegistry.TryGetBranchDefinition(recipe.Branch, out var definition) &&
               definition.UseTierSubcategories
            ? $"tier-{recipe.Tier}"
            : string.Empty;
    }

    private string ResolveCategoryPath(string categoryId, string subCategoryId)
    {
        var categoryName = GetCategoryName(categoryId);
        var subCategoryName = GetSubCategoryName(subCategoryId);
        return string.IsNullOrWhiteSpace(subCategoryName)
            ? categoryName
            : $"{categoryName} / {subCategoryName}";
    }

    private PersistentCraftCategoryPrototype? GetCategoryPrototype(string categoryId)
    {
        return _prototype.TryIndex<PersistentCraftCategoryPrototype>(categoryId, out var prototype)
            ? prototype
            : null;
    }

    private PersistentCraftSubCategoryPrototype? GetSubCategoryPrototype(string subCategoryId)
    {
        return _prototype.TryIndex<PersistentCraftSubCategoryPrototype>(subCategoryId, out var prototype)
            ? prototype
            : null;
    }

    private string GetCategoryName(string categoryId)
    {
        if (GetCategoryPrototype(categoryId) is { } category)
            return TryLoc(category.Name) ?? category.Name;

        var locKey = $"persistent-craft-category-{categoryId}";
        return TryLoc(locKey) ?? HumanizeIdentifier(categoryId);
    }

    private string GetSubCategoryName(string subCategoryId)
    {
        if (string.IsNullOrWhiteSpace(subCategoryId))
            return string.Empty;

        if (GetSubCategoryPrototype(subCategoryId) is { } subCategory)
            return TryLoc(subCategory.Name) ?? subCategory.Name;

        if (subCategoryId.StartsWith("tier-") &&
            subCategoryId.Length > "tier-".Length &&
            int.TryParse(subCategoryId.Substring("tier-".Length), out var tier))
            return $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(tier)}";

        var locKey = $"persistent-craft-subcategory-{subCategoryId}";
        return TryLoc(locKey) ?? HumanizeIdentifier(subCategoryId);
    }

    private int GetCategoryOrder(string categoryId)
    {
        return GetCategoryPrototype(categoryId)?.Order ?? 99;
    }

    private int GetSubCategoryOrder(string subCategoryId)
    {
        return GetSubCategoryPrototype(subCategoryId)?.Order
               ?? (subCategoryId.StartsWith("tier-") &&
                   subCategoryId.Length > "tier-".Length &&
                   int.TryParse(subCategoryId.Substring("tier-".Length), out var tier)
                   ? tier
                   : 99);
    }

    private static string? TryLoc(string locKey)
    {
        try
        {
            return Loc.GetString(locKey);
        }
        catch
        {
            return null;
        }
    }

    private static string HumanizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var spaced = value.Replace('-', ' ').Replace('_', ' ').Trim();
        if (string.IsNullOrWhiteSpace(spaced))
            return string.Empty;

        return string.Concat(char.ToUpperInvariant(spaced[0]).ToString(), spaced.Substring(1));
    }

    private string GetRecipeCategoryPath(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeMetadataIndex.TryGetCategoryPath(recipe.ID, out var categoryPath))
            return categoryPath;

        return ResolveCategoryPath(GetRecipeCategoryId(recipe), GetRecipeSubCategoryId(recipe));
    }

    private bool HasNodeUnlockedOrAutoAvailable(PersistentCraftState state, string nodeId)
    {
        return PersistentCraftNodeAvailabilityResolver.HasNodeUnlockedOrAutoAvailable(
            state,
            nodeId,
            ResolveNodePrototypeOrNull);
    }

    private string BuildIngredientMarkup(PersistentCraftRecipePrototype recipe)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < recipe.Ingredients.Count; i++)
        {
            if (i > 0)
                builder.Append('\n');

            builder.Append(FormatIngredientLine(recipe, recipe.Ingredients[i]));
        }

        return builder.ToString();
    }

    private string BuildResultMarkup(PersistentCraftRecipePrototype recipe)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < recipe.Results.Count; i++)
        {
            if (i > 0)
                builder.Append('\n');

            var result = recipe.Results[i];
            builder.Append($"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(FormatResult(result))}[/color]");
        }

        return builder.ToString();
    }

    private string FormatIngredient(PersistentCraftIngredient ingredient)
    {
        var name = ingredient.GetSelectorKind() switch
        {
            PersistentCraftIngredientSelectorKind.Proto => ResolveEntityName(ingredient.Proto!),
            PersistentCraftIngredientSelectorKind.StackType => ingredient.StackType!,
            PersistentCraftIngredientSelectorKind.Tag => FormatTagIngredientName(ingredient.Tag!),
            _ => "?",
        };

        return $"{name} x{ingredient.Amount}";
    }

    private string FormatResult(PersistentCraftResult result)
    {
        return $"{ResolveEntityName(result.Proto)} x{result.Amount}";
    }

    private string FormatIngredientLine(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var requiredAmount = GetEffectiveIngredientAmount(recipe, ingredient);
        if (!IsLocallyVerifiableIngredient(ingredient))
        {
            return $"[color={MutedText.ToHex()}]- {FormattedMessage.EscapeText(FormatIngredient(ingredient))} (?/{requiredAmount})[/color]";
        }

        var owned = GetOwnedAmount(ingredient);
        var enough = owned >= requiredAmount;
        var color = enough ? EnoughColor : MissingColor;
        return $"[color={color.ToHex()}]- {FormattedMessage.EscapeText(FormatIngredient(ingredient))} ({owned}/{requiredAmount})[/color]";
    }

    private bool GetHasLocalMaterials(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeCraftabilityById.TryGetValue(recipe.ID, out var cached))
            return cached;

        var hasMaterials = HasLocalMaterials(recipe);
        _recipeCraftabilityById[recipe.ID] = hasMaterials;
        return hasMaterials;
    }

    private bool HasLocalMaterials(PersistentCraftRecipePrototype recipe)
    {
        for (var i = 0; i < recipe.Ingredients.Count; i++)
        {
            var ingredient = recipe.Ingredients[i];
            if (!IsLocallyVerifiableIngredient(ingredient))
                continue;

            if (GetOwnedAmount(ingredient) < GetEffectiveIngredientAmount(recipe, ingredient))
                return false;
        }

        return true;
    }

    private static bool IsLocallyVerifiableIngredient(PersistentCraftIngredient ingredient)
    {
        return ingredient.GetSelectorKind() != PersistentCraftIngredientSelectorKind.None &&
               ingredient.GetSelectorKind() != PersistentCraftIngredientSelectorKind.InvalidMultiple;
    }

    private static string FormatTagIngredientName(string tag)
    {
        if (tag.StartsWith("STArtifactTier", StringComparison.Ordinal) &&
            int.TryParse(tag["STArtifactTier".Length..], out var tier))
        {
            return $"Артефакт T{tier}";
        }

        return $"#{tag}";
    }

    private int GetOwnedAmount(PersistentCraftIngredient ingredient)
    {
        return _inventorySnapshot.GetAmount(ingredient);
    }

    private string ResolveEntityName(string prototypeId)
    {
        return _prototype.TryIndex<EntityPrototype>(prototypeId, out var prototype)
            ? prototype.Name
            : prototypeId;
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeMetadataIndex.TryGetName(recipe.ID, out var cached))
            return cached;

        return ResolveRecipeNameCore(recipe);
    }

    private string ResolveRecipeNameCore(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype) &&
            !string.IsNullOrWhiteSpace(prototype.Name))
        {
            return prototype.Name;
        }

        return TryLoc(recipe.Name) ?? recipe.Name;
    }

    private string ResolveRecipeDescription(PersistentCraftRecipePrototype recipe)
    {
        if (_recipeMetadataIndex.TryGetDescription(recipe.ID, out var cached))
            return cached;

        return ResolveRecipeDescriptionCore(recipe);
    }

    private string ResolveRecipeDescriptionCore(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype) &&
            !string.IsNullOrWhiteSpace(prototype.Description))
        {
            return prototype.Description;
        }

        return TryLoc(recipe.Description) ?? recipe.Description;
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Name))
            return TryLoc(node.Name) ?? node.Name;

        if (!string.IsNullOrWhiteSpace(node.DisplayProto) &&
            _prototype.TryIndex<EntityPrototype>(node.DisplayProto, out var prototype) &&
            !string.IsNullOrWhiteSpace(prototype.Name))
        {
            return prototype.Name;
        }

        return TryLoc("persistent-craft-node-sub-recipe-name") ?? node.ID;
    }

    private PersistentCraftBranchState GetBranchState(string branch)
    {
        return _branchCoordinator.GetBranchState(branch);
    }


    private static string GetStatusKey(bool loaded, bool requirementMet, bool hasMaterials)
    {
        if (!loaded)
            return "persistent-craft-station-status-loading";

        if (!requirementMet)
            return "persistent-craft-station-status-locked";

        return hasMaterials
            ? "persistent-craft-station-status-available"
            : "persistent-craft-station-status-missing-materials";
    }

    private Color GetAccent(string branch)
    {
        return _branchRegistry.TryGetBranchDefinition(branch, out var definition)
            ? definition.AccentColor
            : Color.White;
    }

    private string ResolveBranchTitle(string branchId)
    {
        return _branchRegistry.TryGetBranchDefinition(branchId, out var definition)
            ? ResolveBranchTitle(definition)
            : branchId;
    }

    private static string ResolveBranchTitle(PersistentCraftBranchPrototype definition)
    {
        return TryLoc(definition.Name) ?? definition.Name;
    }

    private void InitializeBranchContainers()
    {
        Branches.RemoveAllChildren();
        _branchContainers.Clear();

        for (var index = 0; index < _branchRegistry.OrderedBranches.Count; index++)
        {
            var definition = _branchRegistry.OrderedBranches[index];
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(12, 12, 12, 12),
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            Branches.AddChild(container);
            _branchContainers[definition.ID] = container;
            Branches.SetTabTitle(index, ResolveBranchTitle(definition));
        }

        _viewModel.LastVisibleBranch = _branchRegistry.FirstBranchId;
    }

    private IReadOnlyList<PersistentCraftRecipePrototype> GetRecipesForBranch(string branch)
    {
        if (_recipeIndex != null)
        {
            return _recipeIndex.GetByBranch(branch);
        }

        var recipes = new List<PersistentCraftRecipePrototype>();
        for (var i = 0; i < _recipes.Count; i++)
        {
            var recipe = _recipes[i];
            if (recipe.Branch == branch)
                recipes.Add(recipe);
        }

        return recipes;
    }

    private bool TryGetRecipeById(string recipeId, out PersistentCraftRecipePrototype recipe)
    {
        if (_recipeIndex != null &&
            _recipeIndex.TryGetById(recipeId, out recipe))
        {
            return true;
        }

        for (var i = 0; i < _recipes.Count; i++)
        {
            var item = _recipes[i];
            if (item.ID != recipeId)
                continue;

            recipe = item;
            return true;
        }

        recipe = default!;
        return false;
    }

    private bool TryGetNodePrototype(string nodeId, out PersistentCraftNodePrototype node)
    {
        if (_prototypeCache != null &&
            _prototypeCache.TryGetNode(nodeId, out node))
        {
            return true;
        }

        if (_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var resolvedNode) &&
            resolvedNode != null)
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private PersistentCraftNodePrototype? ResolveNodePrototypeOrNull(string nodeId)
    {
        return TryGetNodePrototype(nodeId, out var node)
            ? node
            : null;
    }

    private PersistentCraftInventorySnapshot BuildInventorySnapshot(IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return PersistentCraftInventorySnapshot.Empty;

        var trackedIngredients = CollectTrackedIngredients(recipes);
        return PersistentCraftInventorySnapshot.Build(
            _entityManager,
            _tag,
            user,
            trackedIngredients);
    }

    private static List<PersistentCraftIngredient> CollectTrackedIngredients(IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        var tracked = new List<PersistentCraftIngredient>();
        var seen = new HashSet<string>();

        for (var i = 0; i < recipes.Count; i++)
        {
            var recipe = recipes[i];
            for (var j = 0; j < recipe.Ingredients.Count; j++)
            {
                var ingredient = recipe.Ingredients[j];
                var key = $"{(int) ingredient.GetSelectorKind()}|{ingredient.GetSelectorValue()}";
                if (seen.Add(key))
                    tracked.Add(ingredient);
            }
        }

        return tracked;
    }

    private float GetEffectiveCraftTime(PersistentCraftRecipePrototype recipe)
    {
        return MathF.Max(0.25f, recipe.CraftTime);
    }

    private int GetEffectiveIngredientAmount(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        _ = recipe;
        return Math.Max(1, ingredient.Amount);
    }

    private int GetMaxCraftCount(PersistentCraftRecipePrototype recipe)
    {
        var maxCount = int.MaxValue;

        for (var i = 0; i < recipe.Ingredients.Count; i++)
        {
            var ingredient = recipe.Ingredients[i];
            if (!IsLocallyVerifiableIngredient(ingredient))
                return 1;

            var requiredAmount = GetEffectiveIngredientAmount(recipe, ingredient);
            if (requiredAmount <= 0)
                continue;

            var ownedAmount = GetOwnedAmount(ingredient);
            var craftsByIngredient = ownedAmount / requiredAmount;
            if (craftsByIngredient < maxCount)
                maxCount = craftsByIngredient;
        }

        if (maxCount == int.MaxValue)
            return 1;

        return Math.Max(0, maxCount);
    }
}
