using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting.UI.Controls;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

    private static readonly Color WeaponAccent = PersistentCraftUiTheme.WeaponAccent;
    private static readonly Color ArmorAccent = PersistentCraftUiTheme.ArmorAccent;
    private static readonly Color AnomalyAccent = PersistentCraftUiTheme.AnomalyAccent;
    private static readonly Color PanelBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardBackground = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color CardUnlockedBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardLockedBackground = PersistentCraftUiTheme.SurfacePanelSoft;
    private static readonly Color CardAvailableBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color AvailableBorder = PersistentCraftUiTheme.BorderStrong;
    private static readonly Color UnlockedBorder = PersistentCraftUiTheme.Success;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color HeaderTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color MutedTextColor = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private const float TierTreeNodeWidth = 156f;
    private const float TierTreeNodeHeight = 118f;
    private const float TierTreeHorizontalGap = 28f;
    private const float TierTreeVerticalGap = 22f;
    private const float TierTreePadding = 18f;
    private const float TierTreeLineThickness = 3f;

    private readonly Dictionary<PersistentCraftBranch, string> _selectedTierByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, string> _selectedNodeByBranch = new();
    private bool _selectPreferredBranchOnNextUpdate = true;

    private PersistentCraftState? _state;
    private List<PersistentCraftNodePrototype> _nodes = new();
    private List<PersistentCraftRecipePrototype> _recipes = new();
    private Action<string>? _onUnlock;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        Branches.SetTabTitle(0, Loc.GetString("persistent-craft-branch-weapon"));
        Branches.SetTabTitle(1, Loc.GetString("persistent-craft-branch-armor"));
        Branches.SetTabTitle(2, Loc.GetString("persistent-craft-branch-anomaly"));
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-skill-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        Branches.OnTabChanged += _ => RenderBranch(GetCurrentBranch());
    }

    public void UpdateState(
        PersistentCraftState state,
        IEnumerable<PersistentCraftNodePrototype> nodes,
        IEnumerable<PersistentCraftRecipePrototype> recipes,
        Action<string> onUnlock)
    {
        _state = state;
        _nodes = nodes
            .OrderBy(node => node.Branch)
            .ThenBy(node => node.Tier)
            .ThenBy(node => node.SubTier)
            .ThenBy(node => node.ID)
            .ToList();
        _recipes = recipes
            .OrderBy(recipe => recipe.Branch)
            .ThenBy(recipe => recipe.Tier)
            .ThenBy(recipe => recipe.SubTier)
            .ThenBy(recipe => recipe.ID)
            .ToList();
        _onUnlock = onUnlock;

        if (state.Loaded && _selectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _selectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _selectPreferredBranchOnNextUpdate = true;
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderBranch(GetCurrentBranch());
    }

    private void RenderBranch(PersistentCraftBranch branch)
    {
        var (tierHost, subNodeHost, detailHost) = GetBranchHosts(branch);
        tierHost.RemoveAllChildren();
        subNodeHost.RemoveAllChildren();
        detailHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchNodes = _nodes.Where(node => node.Branch == branch).ToList();
        var mainTiers = branchNodes
            .Where(PersistentCraftingHelper.IsMainTierNode)
            .OrderBy(node => node.Tier)
            .ToList();

        if (mainTiers.Count == 0)
            return;

        var branchState = GetBranchState(_state, branch);
        var selectedTier = ResolveSelectedTier(branch, mainTiers);
        var subNodes = branchNodes
            .Where(node => !PersistentCraftingHelper.IsMainTierNode(node) && node.Tier == selectedTier.Tier)
            .OrderBy(node => node.SubTier)
            .ToList();
        var selectedNode = ResolveSelectedNode(branch, selectedTier, subNodes);

        tierHost.AddChild(CreateBranchSummary(branch, branchState));
        tierHost.AddChild(new Control { MinSize = new Vector2(1, 10) });
        tierHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-main-tier-label")));
        tierHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        tierHost.AddChild(CreateMainTierList(branch, mainTiers, selectedTier));

        subNodeHost.AddChild(CreateTierSummary(branchState, selectedTier, subNodes));
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 10) });
        subNodeHost.AddChild(CreateSectionHeader(
            $"{Loc.GetString("persistent-craft-subnodes-label")} {PersistentCraftingHelper.GetTierDisplayLabel(selectedTier.Tier)}"));
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        if (subNodes.Count == 0)
        {
            subNodeHost.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedTextColor,
            });
        }
        else
        {
            subNodeHost.AddChild(CreateSubNodeTree(branch, subNodes, selectedNode));
        }

        detailHost.AddChild(CreateDetailsPanel(branchState, selectedNode, subNodes));
    }

    private Control CreateBranchSummary(PersistentCraftBranch branch, PersistentCraftBranchState branchState)
    {
        var accent = GetBranchAccent(branch);
        var xpProgress = PersistentCraftingHelper.GetProgressRatio(
            branchState.Experience,
            branchState.ExperienceForNextLevel);
        var control = new PersistentCraftBranchSummaryBlock();
        control.SetData(
            Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch)),
            $"{Loc.GetString("persistent-craft-branch-level-label")}: {FormatBranchLevel(branchState)}",
            $"{Loc.GetString("persistent-craft-experience-label")}: {FormatBranchExperience(branchState)}",
            xpProgress,
            accent,
            null);
        return control;
    }

    private Control CreateTierSummary(
        PersistentCraftBranchState branchState,
        PersistentCraftNodePrototype selectedTier,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var accent = GetBranchAccent(selectedTier.Branch);
        var tierState = GetTierState(state, selectedTier.Branch, selectedTier.Tier) ??
                        CreateDefaultTierState(selectedTier.Branch, selectedTier.Tier);
        var unlockedSubNodes = subNodes.Count(node => HasNodeUnlockedOrAutoAvailable(node.ID));
        var completed = IsTierDisplayComplete(subNodes);

        var control = new PersistentCraftProgressBlock();
        control.SetData(
            $"{ResolveNodeName(selectedTier)} [{PersistentCraftingHelper.GetTierDisplayLabel(selectedTier.Tier)}]",
            BuildTierProgressCompactText(selectedTier.Branch, selectedTier.Tier, tierState, completed),
            GetTierProgress(tierState, completed),
            accent,
            $"{Loc.GetString("persistent-craft-tier-unlocked-summary", ("unlocked", unlockedSubNodes), ("total", subNodes.Count))} | {Loc.GetString("persistent-craft-tier-points-label")}: {tierState.AvailablePoints}");
        return control;
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private BoxContainer CreateMainTierList(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> tierNodes,
        PersistentCraftNodePrototype selectedTier)
    {
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        foreach (var node in tierNodes)
        {
            list.AddChild(CreateMainTierEntry(branch, node, selectedTier.ID == node.ID));
        }

        return list;
    }

    private ContainerButton CreateMainTierEntry(PersistentCraftBranch branch, PersistentCraftNodePrototype node, bool selected)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var branchState = GetBranchState(state, branch);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var accent = GetBranchAccent(branch);

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinSize = new Vector2(0, 88),
            Margin = new Thickness(0, 0, 0, 8),
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = unlocked ? CardUnlockedBackground : branchLevelMet ? CardAvailableBackground : CardLockedBackground,
                BorderColor = selected ? SelectedBorder : unlocked ? UnlockedBorder : branchLevelMet ? accent.WithAlpha(0.55f) : CardBorder,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 14,
                ContentMarginRightOverride = 14,
                ContentMarginTopOverride = 13,
                ContentMarginBottomOverride = 13,
            }
        };
        button.OnPressed += _ => SelectTier(branch, node.ID);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(CreateNodeIcon(node, selected ? SelectedBorder : accent, new Vector2(60, 60)));
        row.AddChild(new Control { MinSize = new Vector2(12, 1) });

        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        textColumn.AddChild(new Label
        {
            Text = $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]",
            FontColorOverride = HeaderTextColor,
        });
        textColumn.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.GetNodeRequiredBranchLevel(node)} | {Loc.GetString(GetMainTierStatusKey(unlocked, branchLevelMet))}",
            FontColorOverride = unlocked ? UnlockedBorder : branchLevelMet ? accent : MutedTextColor,
        });

        row.AddChild(textColumn);
        button.AddChild(row);
        return button;
    }

    private BoxContainer CreateSubNodeTree(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes,
        PersistentCraftNodePrototype selectedNode)
    {
        var accent = GetBranchAccent(branch);
        var positions = subNodes.ToDictionary(node => node.ID, GetNodeTreePosition);
        var maxColumn = positions.Values.Max(position => position.X);
        var maxRow = positions.Values.Max(position => position.Y);

        var layout = new LayoutContainer
        {
            MinSize = new Vector2(
                TierTreePadding * 2 + (maxColumn + 1) * TierTreeNodeWidth + maxColumn * TierTreeHorizontalGap,
                TierTreePadding * 2 + (maxRow + 1) * TierTreeNodeHeight + maxRow * TierTreeVerticalGap + 20),
            HorizontalAlignment = HAlignment.Center,
        };

        foreach (var node in subNodes)
        {
            var childPosition = GetNodeCanvasPosition(positions[node.ID]);
            var childCenter = GetNodeCenter(childPosition);

            var visualParents = GetVisualPrerequisiteIds(node, subNodes).ToList();
            foreach (var prerequisiteId in visualParents)
            {
                if (!positions.TryGetValue(prerequisiteId, out var parentGridPosition))
                    continue;

                var parentPosition = GetNodeCanvasPosition(parentGridPosition);
                var parentCenter = GetNodeCenter(parentPosition);
                AddConnector(layout, parentCenter, childCenter, accent);
            }

        }

        foreach (var node in subNodes)
        {
            var control = CreateSubNodeEntry(branch, node, selectedNode.ID == node.ID);
            control.MinSize = new Vector2(TierTreeNodeWidth, TierTreeNodeHeight);
            LayoutContainer.SetPosition(control, GetNodeCanvasPosition(positions[node.ID]));
            layout.AddChild(control);
        }

        var wrapper = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };
        wrapper.AddChild(layout);
        return wrapper;
    }

    private Vector2i GetNodeTreePosition(PersistentCraftNodePrototype node)
    {
        if (node.TreeColumn >= 0 && node.TreeRow >= 0)
            return new Vector2i(node.TreeColumn, node.TreeRow);

        return node.SubTier switch
        {
            1 => new Vector2i(1, 0),
            2 => new Vector2i(0, 1),
            3 => new Vector2i(2, 1),
            4 => new Vector2i(1, 2),
            5 => new Vector2i(0, 2),
            6 => new Vector2i(2, 2),
            7 => new Vector2i(1, 3),
            _ => new Vector2i((node.SubTier - 1) % 3, 1 + (node.SubTier - 1) / 3),
        };
    }

    private static IEnumerable<string> GetVisualPrerequisiteIds(
        PersistentCraftNodePrototype node,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        var subNodeIds = subNodes.Select(item => item.ID).ToHashSet();
        var explicitParents = node.Prerequisites.Where(subNodeIds.Contains).ToList();
        if (explicitParents.Count > 0)
            return explicitParents;

        string? TierNode(int subTier) => subNodes.FirstOrDefault(item => item.SubTier == subTier)?.ID;
        var visualParents = new List<string>();

        void AddParent(int subTier)
        {
            var parentId = TierNode(subTier);
            if (!string.IsNullOrWhiteSpace(parentId))
                visualParents.Add(parentId);
        }

        switch (node.SubTier)
        {
            case 2:
            case 3:
                AddParent(1);
                break;
            case 4:
                AddParent(2);
                AddParent(3);
                break;
            case 5:
                AddParent(2);
                AddParent(4);
                break;
            case 6:
                AddParent(3);
                AddParent(4);
                break;
            case 7:
                AddParent(5);
                AddParent(6);
                break;
        }

        return visualParents;
    }

    private static Vector2 GetNodeCanvasPosition(Vector2i gridPosition)
    {
        return new Vector2(
            TierTreePadding + gridPosition.X * (TierTreeNodeWidth + TierTreeHorizontalGap),
            TierTreePadding + gridPosition.Y * (TierTreeNodeHeight + TierTreeVerticalGap));
    }

    private static Vector2 GetNodeCenter(Vector2 canvasPosition)
    {
        return new Vector2(
            canvasPosition.X + TierTreeNodeWidth / 2f,
            canvasPosition.Y + TierTreeNodeHeight / 2f);
    }

    private static void AddConnector(LayoutContainer layout, Vector2 parentCenter, Vector2 childCenter, Color accent)
    {
        var connectorColor = accent.WithAlpha(0.35f);
        var parentBottom = parentCenter.Y + TierTreeNodeHeight / 2f;
        var childTop = childCenter.Y - TierTreeNodeHeight / 2f;
        var midY = parentBottom + (childTop - parentBottom) / 2f;

        AddLine(layout, parentCenter.X, parentBottom, parentCenter.X, midY, connectorColor);
        AddLine(layout, Math.Min(parentCenter.X, childCenter.X), midY, Math.Max(parentCenter.X, childCenter.X), midY, connectorColor);
        AddLine(layout, childCenter.X, midY, childCenter.X, childTop, connectorColor);
    }

    private static void AddLine(LayoutContainer layout, float startX, float startY, float endX, float endY, Color color)
    {
        var isVertical = Math.Abs(startX - endX) < 0.01f;
        var minX = isVertical
            ? startX - TierTreeLineThickness / 2f
            : Math.Min(startX, endX);
        var minY = isVertical
            ? Math.Min(startY, endY)
            : startY - TierTreeLineThickness / 2f;
        var width = isVertical
            ? TierTreeLineThickness
            : Math.Max(Math.Abs(endX - startX), TierTreeLineThickness);
        var height = isVertical
            ? Math.Max(Math.Abs(endY - startY), TierTreeLineThickness)
            : TierTreeLineThickness;

        var line = new PanelContainer
        {
            MinSize = new Vector2(width, height),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
            }
        };

        LayoutContainer.SetPosition(line, new Vector2(minX, minY));
        layout.AddChild(line);
    }

    private ContainerButton CreateSubNodeEntry(PersistentCraftBranch branch, PersistentCraftNodePrototype node, bool selected)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var branchState = GetBranchState(state, branch);
        var tierState = GetTierState(state, branch, node.Tier) ?? CreateDefaultTierState(branch, node.Tier);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var tierProgressMet = IsTierProgressRequirementMet(node, tierState);
        var canUnlock = state.Loaded && !unlocked && prerequisitesMet && branchLevelMet && tierProgressMet && tierState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(branch);

        var button = new ContainerButton
        {
            MinSize = new Vector2(0, 132),
            HorizontalExpand = true,
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = unlocked ? CardUnlockedBackground : canUnlock ? CardAvailableBackground : CardLockedBackground,
                BorderColor = selected ? SelectedBorder : unlocked ? UnlockedBorder : canUnlock ? accent.WithAlpha(0.6f) : CardBorder,
                BorderThickness = new Thickness(selected ? 2 : 1),
                ContentMarginLeftOverride = 12,
                ContentMarginRightOverride = 12,
                ContentMarginTopOverride = 12,
                ContentMarginBottomOverride = 12,
            }
        };
        button.OnPressed += _ => SelectNode(branch, node.ID);

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.AddChild(CreateNodeIcon(node, selected ? SelectedBorder : accent, new Vector2(64, 64)));
        body.AddChild(new Control { MinSize = new Vector2(1, 8) });
        body.AddChild(new Label
        {
            Text = PersistentCraftingHelper.GetNodeLevelText(node),
            FontColorOverride = accent,
            HorizontalAlignment = HAlignment.Center,
        });
        body.AddChild(new Label
        {
            Text = BuildNodeCardTitle(node),
            FontColorOverride = HeaderTextColor,
            HorizontalAlignment = HAlignment.Center,
            ClipText = true,
        });
        body.AddChild(new Control { VerticalExpand = true });
        body.AddChild(new Label
        {
            Text = BuildNodeCardFooter(node, tierState, unlocked, canUnlock, branchLevelMet, prerequisitesMet, tierProgressMet),
            FontColorOverride = unlocked ? UnlockedBorder : canUnlock ? accent : MutedTextColor,
            HorizontalAlignment = HAlignment.Center,
            ClipText = true,
        });

        button.AddChild(body);
        return button;
    }

    private PanelContainer CreateDetailsPanel(
        PersistentCraftBranchState branchState,
        PersistentCraftNodePrototype node,
        IReadOnlyList<PersistentCraftNodePrototype> tierSubNodes)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");
        var tierState = GetTierState(state, node.Branch, node.Tier) ?? CreateDefaultTierState(node.Branch, node.Tier);
        var unlocked = HasNodeUnlockedOrAutoAvailable(node.ID);
        var prerequisitesMet = node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable);
        var branchLevelMet = branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node);
        var tierProgressMet = IsTierProgressRequirementMet(node, tierState);
        var canUnlock = state.Loaded &&
                        !PersistentCraftingHelper.IsMainTierNode(node) &&
                        !unlocked &&
                        prerequisitesMet &&
                        branchLevelMet &&
                        tierProgressMet &&
                        tierState.AvailablePoints >= node.Cost;
        var accent = GetBranchAccent(node.Branch);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PanelBackground,
                BorderColor = accent.WithAlpha(0.5f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 18,
                ContentMarginRightOverride = 18,
                ContentMarginTopOverride = 18,
                ContentMarginBottomOverride = 18,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var headerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        headerRow.AddChild(CreateNodeIcon(node, accent, new Vector2(120, 120)));
        headerRow.AddChild(new Control { MinSize = new Vector2(18, 1) });

        var headerText = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        headerText.AddChild(new Label
        {
            Text = $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]",
            FontColorOverride = HeaderTextColor,
            ClipText = true,
        });
        headerText.AddChild(new Control { MinSize = new Vector2(1, 8) });

        var meta = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        meta.SetMarkup(
            $"[color={MutedTextColor.ToHex()}]{Loc.GetString("persistent-craft-selected-branch", ("branch", Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(node.Branch))))}\n" +
            $"{Loc.GetString("persistent-craft-branch-level-label")}: {FormatBranchLevel(branchState)} | " +
            $"{Loc.GetString("persistent-craft-tier-points-label")}: {tierState.AvailablePoints}\n" +
            $"{Loc.GetString("persistent-craft-node-cost", ("cost", node.Cost))} | " +
            $"{Loc.GetString(GetDetailStatusKey(node, unlocked, branchLevelMet, prerequisitesMet, canUnlock))}[/color]");
        headerText.AddChild(meta);
        headerRow.AddChild(headerText);

        body.AddChild(headerRow);
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        var description = new PersistentCraftTextSection();
        description.SetData(
            Loc.GetString("persistent-craft-description-label"),
            $"[color={DescriptionTextColor.ToHex()}]{FormattedMessage.EscapeText(ResolveNodeDescription(node))}[/color]",
            CardBorder,
            12);
        body.AddChild(description);
        body.AddChild(new Control { MinSize = new Vector2(1, 12) });

        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-node-mastery-label"),
            BuildTierProgressMarkup(node.Branch, node.Tier, tierState, unlocked, IsTierDisplayComplete(tierSubNodes))));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });
        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-rewards-label"),
            BuildRewardMarkup(node, tierState, tierSubNodes)));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });
        body.AddChild(CreateDetailSection(
            Loc.GetString("persistent-craft-requirements-label"),
            BuildRequirementMarkup(node)));
        body.AddChild(new Control { VerticalExpand = true });

        var canAttemptUnlock = state.Loaded &&
                               !PersistentCraftingHelper.IsMainTierNode(node) &&
                               !unlocked;

        var unlockButton = new Button
        {
            Text = GetActionText(node, unlocked, canUnlock),
            Disabled = !canAttemptUnlock,
            MinSize = new Vector2(0, 46),
            HorizontalExpand = true,
        };
        unlockButton.OnPressed += _ => _onUnlock?.Invoke(node.ID);

        body.AddChild(unlockButton);
        panel.AddChild(body);
        return panel;
    }

    private Control CreateDetailSection(string title, string contentMarkup)
    {
        var section = new PersistentCraftTextSection();
        section.SetData(title, contentMarkup, CardBorder, 12);
        return section;
    }

    private string BuildNodeCardTitle(PersistentCraftNodePrototype node)
    {
        if (PersistentCraftingHelper.IsStarterSubTierNode(node))
            return Loc.GetString("persistent-craft-node-sub-starter-name");

        return node.NodeType switch
        {
            PersistentCraftNodeType.RecipeUnlock => Loc.GetString("persistent-craft-node-sub-recipe-name"),
            PersistentCraftNodeType.MaterialEfficiency => Loc.GetString("persistent-craft-node-sub-material-name"),
            PersistentCraftNodeType.CraftSpeed => Loc.GetString("persistent-craft-node-sub-speed-name"),
            _ => ResolveNodeName(node),
        };
    }

    private string BuildNodeCardFooter(
        PersistentCraftNodePrototype node,
        PersistentCraftTierState tierState,
        bool unlocked,
        bool canUnlock,
        bool branchLevelMet,
        bool prerequisitesMet,
        bool tierProgressMet)
    {
        if (PersistentCraftingHelper.IsStarterSubTierNode(node))
            return Loc.GetString("persistent-craft-auto-unlock-label");

        if (unlocked)
            return Loc.GetString("persistent-craft-node-status-unlocked");

        if (!branchLevelMet)
        {
            return Loc.GetString(
                "persistent-craft-node-status-branch-level",
                ("level", PersistentCraftingHelper.GetNodeRequiredBranchLevel(node)));
        }

        if (!prerequisitesMet)
            return Loc.GetString("persistent-craft-node-status-chain");

        if (!tierProgressMet)
        {
            return Loc.GetString(
                "persistent-craft-node-status-tier-progress",
                ("subLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(node.Tier, PersistentCraftingHelper.GetNodeRequiredTierProgressLevel(node))));
        }

        var status = Loc.GetString(canUnlock
            ? "persistent-craft-node-status-available"
            : "persistent-craft-node-status-locked");

        if (node.Cost <= 0)
            return status;

        return $"{Loc.GetString("persistent-craft-tier-points-short")}: {tierState.AvailablePoints} | {Loc.GetString("persistent-craft-node-cost", ("cost", node.Cost))}";
    }

    private PanelContainer CreateNodeIcon(PersistentCraftNodePrototype node, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            HorizontalAlignment = HAlignment.Center,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            }
        };

        if (TryGetNodeTexture(node, out var texture))
        {
            panel.AddChild(new TextureRect
            {
                Texture = texture,
                TextureScale = size.X >= 100 ? new Vector2(2.1f, 2.1f) : new Vector2(1.25f, 1.25f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }
        else
        {
            panel.AddChild(new Label
            {
                Text = PersistentCraftingHelper.GetNodeLevelText(node),
                FontColorOverride = HeaderTextColor,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            });
        }

        return panel;
    }

    private string BuildRewardMarkup(
        PersistentCraftNodePrototype node,
        PersistentCraftTierState? tierState,
        IReadOnlyList<PersistentCraftNodePrototype> tierSubNodes)
    {
        var lines = new List<string>();

        if (PersistentCraftingHelper.IsMainTierNode(node))
        {
            lines.Add($"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-main-tier", ("tier", node.Tier))}[/color]");

            foreach (var subNode in tierSubNodes.OrderBy(item => item.SubTier))
            {
                lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(subNode))} ({PersistentCraftingHelper.GetNodeLevelText(subNode)})[/color]");
            }

            return string.Join("\n", lines);
        }

        if (node.NodeType == PersistentCraftNodeType.RecipeUnlock)
        {
            var recipes = FindRecipesForNode(node).ToList();
            if (recipes.Count == 0)
                return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

            return string.Join("\n", recipes.Select(recipe =>
                $"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveRecipeName(recipe))} ({PersistentCraftingHelper.GetRecipeLevelText(recipe)})[/color]"));
        }

        if (node.NodeType == PersistentCraftNodeType.MaterialEfficiency)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-materials", ("tier", PersistentCraftingHelper.GetAffectedTier(node)), ("percent", GetCurrentTierEffectValue(tierState, node.MaterialCostReductionPercent)))}[/color]";
        }

        if (node.NodeType == PersistentCraftNodeType.CraftSpeed)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-effect-speed", ("tier", PersistentCraftingHelper.GetAffectedTier(node)), ("percent", GetCurrentTierEffectValue(tierState, node.CraftTimeReductionPercent)))}[/color]";
        }

        return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";
    }

    private string BuildRequirementMarkup(PersistentCraftNodePrototype node)
    {
        var lines = new List<string>();

        if (PersistentCraftingHelper.GetNodeRequiredBranchLevel(node) > 1)
        {
            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {Loc.GetString("persistent-craft-level-label")}: {PersistentCraftingHelper.GetNodeRequiredBranchLevel(node)}[/color]");
        }

        foreach (var prerequisiteId in node.Prerequisites)
        {
            var prerequisite = _nodes.FirstOrDefault(item => item.ID == prerequisiteId);
            if (prerequisite == null)
            {
                lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(prerequisiteId)}[/color]");
                continue;
            }

            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(prerequisite))} ({PersistentCraftingHelper.GetNodeLevelText(prerequisite)})[/color]");
        }

        var requiredTierProgress = PersistentCraftingHelper.GetNodeRequiredTierProgressLevel(node);
        if (!PersistentCraftingHelper.IsMainTierNode(node) &&
            requiredTierProgress > PersistentCraftingHelper.InitialTierProgressLevel)
        {
            lines.Add($"[color={DescriptionTextColor.ToHex()}]- {Loc.GetString("persistent-craft-tier-progress-required", ("subLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(node.Tier, requiredTierProgress)))}[/color]");
        }

        if (lines.Count == 0)
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-none")}[/color]";

        return string.Join("\n", lines);
    }

    private string BuildTierProgressMarkup(
        PersistentCraftBranch branch,
        int tier,
        PersistentCraftTierState? tierState,
        bool unlocked,
        bool completed)
    {
        if (!unlocked)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-locked")}[/color]";
        }

        var state = tierState ?? CreateDefaultTierState(branch, tier);
        var maxProgressLevel = Math.Max(PersistentCraftingHelper.InitialTierProgressLevel, state.MaxProgressLevel);
        var level = completed
            ? maxProgressLevel
            : Math.Clamp(state.ProgressLevel, PersistentCraftingHelper.InitialTierProgressLevel, maxProgressLevel);
        var next = completed ? 0 : state.ExperienceForNextLevel;

        if (next <= 0 || level >= maxProgressLevel)
        {
            return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-max", ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, level)), ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, maxProgressLevel)))}[/color]";
        }

        return $"[color={DescriptionTextColor.ToHex()}]{Loc.GetString("persistent-craft-node-mastery-progress", ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, level)), ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, maxProgressLevel)), ("experience", state.Experience), ("next", next))}[/color]";
    }

    private PersistentCraftNodePrototype ResolveSelectedTier(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftNodePrototype> tierNodes)
    {
        if (_selectedTierByBranch.TryGetValue(branch, out var selectedId))
        {
            var existing = tierNodes.FirstOrDefault(node => node.ID == selectedId);
            if (existing != null)
                return existing;
        }

        var fallback = tierNodes
                           .Where(node => HasNodeUnlockedOrAutoAvailable(node.ID))
                           .OrderByDescending(node => node.Tier)
                           .FirstOrDefault()
                       ?? tierNodes[0];

        _selectedTierByBranch[branch] = fallback.ID;
        return fallback;
    }

    private PersistentCraftNodePrototype ResolveSelectedNode(
        PersistentCraftBranch branch,
        PersistentCraftNodePrototype selectedTier,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (_selectedNodeByBranch.TryGetValue(branch, out var selectedId))
        {
            var existing = subNodes.FirstOrDefault(node => node.ID == selectedId) ??
                           (selectedTier.ID == selectedId ? selectedTier : null);
            if (existing != null)
                return existing;
        }

        var branchState = GetBranchState(state, branch);
        var fallback = subNodes
                           .Where(node => !state.UnlockedNodes.Contains(node.ID) &&
                                          node.Prerequisites.All(HasNodeUnlockedOrAutoAvailable) &&
                                          branchState.Level >= PersistentCraftingHelper.GetNodeRequiredBranchLevel(node) &&
                                          IsTierProgressRequirementMet(node, GetTierState(state, branch, node.Tier) ?? CreateDefaultTierState(branch, node.Tier)) &&
                                          (GetTierState(state, branch, node.Tier)?.AvailablePoints ?? 0) >= node.Cost)
                           .OrderBy(node => node.SubTier)
                           .FirstOrDefault()
                       ?? subNodes
                           .Where(node => HasNodeUnlockedOrAutoAvailable(node.ID))
                           .OrderByDescending(node => node.SubTier)
                           .FirstOrDefault()
                       ?? subNodes.FirstOrDefault()
                       ?? selectedTier;

        _selectedNodeByBranch[branch] = fallback.ID;
        return fallback;
    }

    private void SelectTier(PersistentCraftBranch branch, string nodeId)
    {
        _selectedTierByBranch[branch] = nodeId;

        var tierNode = _nodes.FirstOrDefault(item => item.ID == nodeId);
        if (tierNode == null)
        {
            _selectedNodeByBranch[branch] = nodeId;
            RenderBranch(branch);
            return;
        }

        var subNodes = _nodes
            .Where(item => item.Branch == branch &&
                           !PersistentCraftingHelper.IsMainTierNode(item) &&
                           item.Tier == tierNode.Tier)
            .OrderBy(item => item.SubTier)
            .ToList();

        _selectedNodeByBranch[branch] = ResolveSelectedNode(branch, tierNode, subNodes).ID;
        RenderBranch(branch);
    }

    private void SelectNode(PersistentCraftBranch branch, string nodeId)
    {
        _selectedNodeByBranch[branch] = nodeId;

        var node = _nodes.FirstOrDefault(item => item.ID == nodeId);
        if (node != null)
            _selectedTierByBranch[branch] = PersistentCraftingHelper.BuildMainTierNodeId(node.Branch, node.Tier);

        RenderBranch(branch);
    }

    private IEnumerable<PersistentCraftRecipePrototype> FindRecipesForNode(PersistentCraftNodePrototype node)
    {
        return _recipes.Where(recipe =>
        {
            if (!string.IsNullOrWhiteSpace(recipe.RequiredNode))
                return recipe.RequiredNode == node.ID;

            return recipe.Branch == node.Branch &&
                   recipe.Tier == node.Tier &&
                   recipe.SubTier == node.SubTier;
        });
    }

    private bool TryGetNodeTexture(PersistentCraftNodePrototype node, out Texture? texture)
    {
        texture = null;

        var displayProto = node.DisplayProto;
        if (string.IsNullOrWhiteSpace(displayProto))
        {
            var recipe = FindRecipesForNode(node).FirstOrDefault();
            displayProto = recipe == null ? null : PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        }

        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Name))
            return Loc.GetString(node.Name);

        return node.NodeType switch
        {
            PersistentCraftNodeType.MainTier =>
                $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(node.Branch))} {PersistentCraftingHelper.GetTierDisplayLabel(node.Tier)}",
            PersistentCraftNodeType.RecipeUnlock => Loc.GetString("persistent-craft-node-sub-recipe-name"),
            PersistentCraftNodeType.MaterialEfficiency => Loc.GetString("persistent-craft-node-sub-material-name"),
            PersistentCraftNodeType.CraftSpeed => Loc.GetString("persistent-craft-node-sub-speed-name"),
            _ => PersistentCraftingHelper.GetNodeLevelText(node),
        };
    }

    private string ResolveNodeDescription(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Description))
            return Loc.GetString(node.Description);

        return node.NodeType switch
        {
            PersistentCraftNodeType.MainTier =>
                Loc.GetString("persistent-craft-node-effect-main-tier", ("tier", node.Tier)),
            PersistentCraftNodeType.RecipeUnlock => Loc.GetString("persistent-craft-node-sub-recipe-desc"),
            PersistentCraftNodeType.MaterialEfficiency => Loc.GetString("persistent-craft-node-sub-material-desc"),
            PersistentCraftNodeType.CraftSpeed => Loc.GetString("persistent-craft-node-sub-speed-desc"),
            _ => PersistentCraftingHelper.GetNodeLevelText(node),
        };
    }

    private string GetMainTierStatusKey(bool unlocked, bool branchLevelMet)
    {
        if (_state?.Loaded != true)
            return "persistent-craft-node-status-loading";

        if (unlocked)
            return "persistent-craft-node-status-unlocked";

        return branchLevelMet
            ? "persistent-craft-auto-unlock-label"
            : "persistent-craft-node-status-locked";
    }

    private string GetDetailStatusKey(
        PersistentCraftNodePrototype node,
        bool unlocked,
        bool branchLevelMet,
        bool prerequisitesMet,
        bool canUnlock)
    {
        if (_state?.Loaded != true)
            return "persistent-craft-node-status-loading";

        if (PersistentCraftingHelper.IsMainTierNode(node))
            return GetMainTierStatusKey(unlocked, branchLevelMet);

        if (unlocked)
            return "persistent-craft-node-status-unlocked";

        if (canUnlock)
            return "persistent-craft-node-status-available";

        if (!branchLevelMet || !prerequisitesMet)
            return "persistent-craft-node-status-locked";

        return "persistent-craft-node-status-locked";
    }

    private string GetActionText(PersistentCraftNodePrototype node, bool unlocked, bool canUnlock)
    {
        if (_state?.Loaded != true)
            return Loc.GetString("persistent-craft-node-status-loading");

        if (PersistentCraftingHelper.IsMainTierNode(node))
            return Loc.GetString("persistent-craft-auto-unlock-label");

        if (unlocked)
            return Loc.GetString("persistent-craft-node-status-unlocked");

        return Loc.GetString("persistent-craft-node-action-unlock");
    }

    private void SelectPreferredBranchTab()
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        var preferred = PersistentCraftingHelper.EnumerateBranches()
            .Select(branch => new
            {
                Branch = branch,
                Points = GetBranchState(state, branch).AvailablePoints,
            })
            .OrderByDescending(entry => entry.Points)
            .FirstOrDefault(entry => entry.Points > 0);

        if (preferred != null)
            Branches.CurrentTab = GetBranchTabIndex(preferred.Branch);
    }

    private static int GetBranchTabIndex(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => 0,
            PersistentCraftBranch.Armor => 1,
            PersistentCraftBranch.Anomaly => 2,
            _ => 0,
        };
    }

    private PersistentCraftBranch GetCurrentBranch()
    {
        return Branches.CurrentTab switch
        {
            1 => PersistentCraftBranch.Armor,
            2 => PersistentCraftBranch.Anomaly,
            _ => PersistentCraftBranch.Weapon,
        };
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId)
    {
        if (_state == null)
            return false;

        return HasNodeUnlockedOrAutoAvailable(nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId, HashSet<string> path)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
            return false;

        if (!PersistentCraftingHelper.IsStarterSubTierNode(node) && node.Cost > 0)
            return false;

        var branchState = GetBranchState(state, node.Branch);
        if (branchState.Level < PersistentCraftingHelper.GetNodeRequiredBranchLevel(node))
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private (BoxContainer tierHost, BoxContainer subNodeHost, BoxContainer detailHost) GetBranchHosts(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => (WeaponTierHost, WeaponSubNodeHost, WeaponDetailHost),
            PersistentCraftBranch.Armor => (ArmorTierHost, ArmorSubNodeHost, ArmorDetailHost),
            PersistentCraftBranch.Anomaly => (AnomalyTierHost, AnomalySubNodeHost, AnomalyDetailHost),
            _ => (WeaponTierHost, WeaponSubNodeHost, WeaponDetailHost),
        };
    }

    private PersistentCraftBranchState GetBranchState(PersistentCraftState state, PersistentCraftBranch branch)
    {
        return state.BranchStates.FirstOrDefault(item => item.Branch == branch) ??
               new PersistentCraftBranchState(
                   branch,
                   GetBranchMaxLevel(branch),
                   0,
                   0,
                   PersistentCraftingHelper.InitialLevel,
                   PersistentCraftingHelper.MainTierSubLevel,
                   0,
                   PersistentCraftingHelper.GetExperienceForNextLevel(PersistentCraftingHelper.InitialLevel));
    }

    private int GetBranchMaxLevel(PersistentCraftBranch branch)
    {
        return _nodes
            .Where(node => node.Branch == branch && PersistentCraftingHelper.IsMainTierNode(node))
            .Select(node => node.Tier)
            .DefaultIfEmpty(PersistentCraftingHelper.InitialLevel)
            .Max();
    }

    private static string FormatBranchLevel(PersistentCraftBranchState branchState)
    {
        return PersistentCraftingHelper.FormatCappedLevel(branchState.Level, branchState.MaxLevel);
    }

    private static string FormatBranchExperience(PersistentCraftBranchState branchState)
    {
        return branchState.ExperienceForNextLevel <= 0
            ? Loc.GetString("persistent-craft-max-label")
            : $"{branchState.Experience}/{branchState.ExperienceForNextLevel}";
    }

    private static PersistentCraftTierState? GetTierState(PersistentCraftState state, PersistentCraftBranch branch, int tier)
    {
        return state.TierStates.FirstOrDefault(item => item.Branch == branch && item.Tier == tier);
    }

    private int GetTierMaxProgressLevel(PersistentCraftBranch branch, int tier)
    {
        var maxSubTier = _nodes
            .Where(node => node.Branch == branch &&
                           node.Tier == tier &&
                           !PersistentCraftingHelper.IsMainTierNode(node) &&
                           node.SubTier > PersistentCraftingHelper.MainTierSubLevel)
            .Select(node => node.SubTier)
            .DefaultIfEmpty(PersistentCraftingHelper.DefaultMaxTierProgressLevel)
            .Max();

        return Math.Max(PersistentCraftingHelper.InitialTierProgressLevel, maxSubTier);
    }

    private PersistentCraftTierState CreateDefaultTierState(PersistentCraftBranch branch, int tier)
    {
        var maxProgressLevel = GetTierMaxProgressLevel(branch, tier);
        return new PersistentCraftTierState(
            branch,
            tier,
            PersistentCraftingHelper.InitialTierProgressLevel,
            maxProgressLevel,
            0,
            0,
            0,
            PersistentCraftingHelper.GetTierExperienceForNextLevel(
                tier,
                PersistentCraftingHelper.InitialTierProgressLevel,
                maxProgressLevel));
    }

    private static bool IsTierProgressRequirementMet(PersistentCraftNodePrototype node, PersistentCraftTierState tierState)
    {
        var requiredProgress = PersistentCraftingHelper.GetNodeRequiredTierProgressLevel(node);
        return tierState.ProgressLevel >= requiredProgress;
    }

    private static float GetTierProgress(PersistentCraftTierState? tierState, bool completed = false)
    {
        if (completed)
            return 1f;

        var state = tierState;
        if (state == null)
            return 0f;

        if (state.ExperienceForNextLevel <= 0)
            return 1f;

        return Math.Clamp(state.Experience / (float) state.ExperienceForNextLevel, 0f, 1f);
    }

    private string BuildTierProgressCompactText(PersistentCraftBranch branch, int tier, PersistentCraftTierState? tierState, bool completed = false)
    {
        var state = tierState ?? CreateDefaultTierState(branch, tier);
        var maxProgressLevel = Math.Max(PersistentCraftingHelper.InitialTierProgressLevel, state.MaxProgressLevel);

        if (completed)
        {
            return Loc.GetString(
                "persistent-craft-node-mastery-max",
                ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, maxProgressLevel)),
                ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, maxProgressLevel)));
        }

        return Loc.GetString(
            "persistent-craft-node-mastery-short",
            ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, state.ProgressLevel)),
            ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, maxProgressLevel)));
    }

    private bool IsTierDisplayComplete(IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        return subNodes.Count > 0 && subNodes.All(node => HasNodeUnlockedOrAutoAvailable(node.ID));
    }

    private int GetCurrentTierEffectValue(
        PersistentCraftTierState? tierState,
        int baseValue)
    {
        if (baseValue <= 0)
            return 0;

        var state = tierState ?? CreateDefaultTierState(PersistentCraftBranch.Weapon, 1);
        var max = Math.Max(PersistentCraftingHelper.InitialTierProgressLevel, state.MaxProgressLevel);
        var normalized = Math.Clamp(
            (state.ProgressLevel - PersistentCraftingHelper.InitialTierProgressLevel) /
            (float) Math.Max(1, max - PersistentCraftingHelper.InitialTierProgressLevel),
            0f,
            1f);
        var multiplier = 0.5f + normalized * 0.5f;
        return Math.Max(1, (int) MathF.Round(baseValue * multiplier));
    }

    private static Color GetBranchAccent(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => WeaponAccent,
            PersistentCraftBranch.Armor => ArmorAccent,
            PersistentCraftBranch.Anomaly => AnomalyAccent,
            _ => CardBorder,
        };
    }
}
