using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client._Stalker.PersistentCrafting.UI.Controls;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftStationWindow : DefaultWindow
{
    private sealed record RecipeEntryControls(ContainerButton Button, PanelContainer IconPanel);

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    private readonly TagSystem _tag;

    private static readonly Color WindowBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardBackground = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color CardMutedBorder = PersistentCraftUiTheme.BorderSoft;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private static readonly Color MutedText = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionText = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color AccentWeapon = PersistentCraftUiTheme.WeaponAccent;
    private static readonly Color AccentArmor = PersistentCraftUiTheme.ArmorAccent;
    private static readonly Color AccentAnomaly = PersistentCraftUiTheme.AnomalyAccent;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color EnoughColor = PersistentCraftUiTheme.Success;
    private static readonly Color MissingColor = PersistentCraftUiTheme.Danger;

    private readonly Dictionary<PersistentCraftBranch, string> _selectedRecipes = new();
    private readonly Dictionary<PersistentCraftBranch, int> _selectedTierFilters = new();
    private readonly Dictionary<PersistentCraftBranch, string> _searchTextByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, bool> _craftableOnlyByBranch = new();
    private readonly Dictionary<string, int> _ownedAmountCache = new();
    private readonly Dictionary<PersistentCraftBranch, Vector2> _listScrollByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, Vector2> _detailScrollByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, ScrollContainer> _activeListScrollByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, ScrollContainer> _activeDetailScrollByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, Dictionary<string, RecipeEntryControls>> _recipeEntryControlsByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, BoxContainer> _detailContentHostsByBranch = new();
    private readonly Dictionary<PersistentCraftBranch, PersistentCraftBranchState> _visibleBranchStatesByBranch = new();
    private readonly HashSet<string> _collapsedCategoryKeys = new();
    private readonly HashSet<string> _collapsedSubCategoryKeys = new();
    private readonly HashSet<string> _initializedCategoryKeys = new();
    private readonly HashSet<string> _initializedSubCategoryKeys = new();
    private bool _selectPreferredBranchOnNextUpdate = true;
    private PersistentCraftBranch _lastVisibleBranch = PersistentCraftBranch.Weapon;

    private PersistentCraftState? _state;
    private List<PersistentCraftRecipePrototype> _recipes = new();
    private string _inventorySignature = string.Empty;

    public event Action<string>? OnCraftPressed;
    public event Action? OnOpenSkillsPressed;

    public PersistentCraftStationWindow()
    {
        IoCManager.InjectDependencies(this);
        _tag = _entityManager.EntitySysManager.GetEntitySystem<TagSystem>();

        RobustXamlLoader.Load(this);

        Branches.SetTabTitle(0, Loc.GetString("persistent-craft-branch-weapon"));
        Branches.SetTabTitle(1, Loc.GetString("persistent-craft-branch-armor"));
        Branches.SetTabTitle(2, Loc.GetString("persistent-craft-branch-anomaly"));
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-menu-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        OpenSkillsButton.OnPressed += _ => OnOpenSkillsPressed?.Invoke();

        Branches.OnTabChanged += _ =>
        {
            if (_state == null)
                return;
            RememberBranchScroll(_lastVisibleBranch);
            _ownedAmountCache.Clear();
            var branch = GetCurrentBranch();
            PopulateBranch(GetBranchContainer(branch), branch);
            _lastVisibleBranch = branch;
        };
    }

    public void UpdateState(PersistentCraftState state, IEnumerable<PersistentCraftRecipePrototype> recipes)
    {
        _state = state;
        _recipes = recipes
            .OrderBy(recipe => recipe.Branch)
            .ThenBy(recipe => recipe.Tier)
            .ThenBy(recipe => recipe.SubTier)
            .ThenBy(recipe => recipe.ID)
            .ToList();
        _ownedAmountCache.Clear();
        _inventorySignature = BuildInventorySignature();

        if (state.Loaded && _selectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _selectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _selectPreferredBranchOnNextUpdate = true;
    }

    public void RefreshLocalInventory()
    {
        if (_state == null)
            return;

        var newSignature = BuildInventorySignature();
        if (newSignature == _inventorySignature)
            return;

        _inventorySignature = newSignature;
        _ownedAmountCache.Clear();

        // Rebuild only the currently visible branch to avoid flickering
        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
        _lastVisibleBranch = branch;
    }

    private void Render()
    {
        if (_state == null)
            return;

        var branch = GetCurrentBranch();
        PopulateBranch(GetBranchContainer(branch), branch);
        _lastVisibleBranch = branch;
    }

    private void PopulateBranch(BoxContainer container, PersistentCraftBranch branch)
    {
        RememberBranchScroll(branch);
        container.RemoveAllChildren();

        if (_state == null)
            return;

        var branchRecipes = _recipes
            .Where(recipe => recipe.Branch == branch)
            .ToList();

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var branchState = GetBranchState(_state, branch);
        _visibleBranchStatesByBranch[branch] = branchState;
        _recipeEntryControlsByBranch[branch] = new Dictionary<string, RecipeEntryControls>();
        var unlockedRecipes = _state.Loaded
            ? branchRecipes.Where(recipe => HasRequirement(_state, recipe)).ToList()
            : new List<PersistentCraftRecipePrototype>();

        container.AddChild(CreateBranchHeader(branch, branchState, unlockedRecipes.Count, branchRecipes.Count));
        container.AddChild(new Control { MinSize = new Vector2(1, 12) });

        if (!_state.Loaded)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-window-loading-points"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (branchRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        if (unlockedRecipes.Count == 0)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-station-no-recipes"),
                FontColorOverride = MutedText,
            });
            return;
        }

        var selectedTier = GetSelectedTierFilter(branch, unlockedRecipes, branchState);

        var filteredRecipes = selectedTier > 0
            ? unlockedRecipes.Where(recipe => recipe.Tier == selectedTier).ToList()
            : unlockedRecipes;
        var searchText = GetSearchText(branch);
        filteredRecipes = ApplyRecipeSearch(filteredRecipes, searchText);
        var craftableOnly = GetCraftableOnly(branch);
        var craftableCount = filteredRecipes.Count(HasLocalMaterials);
        filteredRecipes = ApplyCraftableFilter(filteredRecipes, craftableOnly);

        var workspace = new PersistentCraftRecipeWorkspace();
        workspace.SetAccent(GetAccent(branch));
        workspace.FilterContainer.AddChild(CreateFilterToolbar(branch, searchText, craftableOnly));
        workspace.TierFilterContainer.AddChild(CreateTierFilterRow(branch, unlockedRecipes, selectedTier, GetAccent(branch)));
        workspace.SummaryContainer.AddChild(CreateRecipeListSummary(selectedTier, filteredRecipes.Count, craftableCount, craftableOnly, GetAccent(branch)));
        var listScroll = workspace.RecipeListScroll;

        if (filteredRecipes.Count > 0)
        {
            var selected = ResolveSelectedRecipe(branch, filteredRecipes);
            workspace.ListContainer.AddChild(CreateRecipeList(branch, filteredRecipes, selected, GetAccent(branch)));
            workspace.DetailContainer.AddChild(CreateRecipeDetailsPanel(selected, branchState));
            _detailContentHostsByBranch[branch] = workspace.DetailContainer;
        }
        else
        {
            workspace.ListContainer.AddChild(CreateEmptyRecipeListMessage(searchText, craftableOnly));
            workspace.DetailContainer.AddChild(CreateEmptyDetailPanel(searchText, craftableOnly));
            _detailContentHostsByBranch[branch] = workspace.DetailContainer;
        }

        _activeListScrollByBranch[branch] = listScroll;
        _activeDetailScrollByBranch[branch] = workspace.RecipeDetailScroll;
        container.AddChild(workspace);
        RestoreBranchScroll(branch, listScroll, workspace.RecipeDetailScroll);
    }

    private BoxContainer CreateTierFilterRow(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        int selectedTier,
        Color accent)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        row.AddChild(CreateTierFilterButton(branch, 0, Loc.GetString("persistent-craft-filter-all"), selectedTier == 0, accent));

        foreach (var tier in recipes.Select(recipe => recipe.Tier).Distinct().OrderBy(tier => tier))
        {
            row.AddChild(new Control { MinSize = new Vector2(6, 1) });
            row.AddChild(CreateTierFilterButton(
                branch,
                tier,
                PersistentCraftingHelper.GetTierDisplayLabel(tier),
                selectedTier == tier,
                accent));
        }

        return row;
    }

    private Button CreateTierFilterButton(
        PersistentCraftBranch branch,
        int tier,
        string text,
        bool selected,
        Color accent)
    {
        var button = new Button
        {
            Text = text,
            MinSize = new Vector2(42, 28),
            ModulateSelfOverride = selected ? PersistentCraftUiTheme.TextPrimary : PersistentCraftUiTheme.TextSecondary,
            StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = selected ? accent.WithAlpha(0.12f) : PersistentCraftUiTheme.SurfacePanelSoft,
                BorderColor = selected ? accent.WithAlpha(0.72f) : CardMutedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            }
        };

        button.OnPressed += _ => SelectTierFilter(branch, tier);
        return button;
    }

    private Control CreateBranchHeader(
        PersistentCraftBranch branch,
        PersistentCraftBranchState branchState,
        int unlockedRecipes,
        int totalRecipes)
    {
        var accent = GetAccent(branch);
        var xpProgress = PersistentCraftingHelper.GetProgressRatio(
            branchState.Experience,
            branchState.ExperienceForNextLevel);
        var control = new PersistentCraftBranchSummaryBlock();
        control.SetData(
            Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(branch)),
            $"{Loc.GetString("persistent-craft-branch-level-label")}: {FormatBranchLevel(branchState)} | " +
            $"{Loc.GetString("persistent-craft-recipes-short")}: {unlockedRecipes}/{totalRecipes}",
            $"{Loc.GetString("persistent-craft-experience-label")}: {FormatBranchExperience(branchState)}",
            xpProgress,
            accent,
            null);
        return control;
    }

    private Control CreateFilterToolbar(PersistentCraftBranch branch, string searchText, bool craftableOnly)
    {
        var accent = GetAccent(branch);
        var toolbar = new PersistentCraftRecipeToolbar();
        toolbar.SetData(
            Loc.GetString("persistent-craft-search-placeholder"),
            searchText,
            Loc.GetString("persistent-craft-filter-craftable"),
            craftableOnly,
            accent);
        toolbar.SearchInput.OnTextChanged += args => UpdateSearch(branch, args.Text);
        toolbar.CraftableToggleButton.OnPressed += _ => ToggleCraftableOnly(branch);
        return toolbar;
    }

    private Control CreateRecipeListSummary(int selectedTier, int visibleRecipes, int craftableCount, bool craftableOnly, Color accent)
    {
        var tierText = selectedTier > 0
            ? $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(selectedTier)}"
            : Loc.GetString("persistent-craft-filter-all");
        var craftableText = $"{Loc.GetString("persistent-craft-craftable-short")}: {craftableCount}";
        var filterText = craftableOnly ? $" | {Loc.GetString("persistent-craft-filter-craftable")}" : string.Empty;

        var summary = new PersistentCraftRecipeListSummary();
        summary.SetData(
            $"{tierText} | {Loc.GetString("persistent-craft-recipes-short")}: {visibleRecipes} | {craftableText}{filterText}",
            accent);
        return summary;
    }

    private Control CreateEmptyRecipeListMessage(string searchText, bool craftableOnly)
    {
        var text = craftableOnly
            ? string.IsNullOrWhiteSpace(searchText)
                ? Loc.GetString("persistent-craft-empty-craftable")
                : Loc.GetString("persistent-craft-search-empty-craftable")
            : string.IsNullOrWhiteSpace(searchText)
                ? Loc.GetString("persistent-craft-station-no-recipes")
                : Loc.GetString("persistent-craft-search-empty");

        return new Label
        {
            Text = text,
            FontColorOverride = MutedText,
        };
    }

    private PanelContainer CreateEmptyDetailPanel(string searchText, bool craftableOnly)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = WindowBackground,
                BorderColor = CardMutedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 18,
                ContentMarginRightOverride = 18,
                ContentMarginTopOverride = 18,
                ContentMarginBottomOverride = 18,
            }
        };

        var text = craftableOnly
            ? string.IsNullOrWhiteSpace(searchText)
                ? Loc.GetString("persistent-craft-empty-craftable-detail")
                : Loc.GetString("persistent-craft-search-empty-craftable-detail")
            : string.IsNullOrWhiteSpace(searchText)
                ? Loc.GetString("persistent-craft-empty-detail")
                : Loc.GetString("persistent-craft-search-empty-detail");

        panel.AddChild(new Label
        {
            Text = text,
            FontColorOverride = MutedText,
        });

        return panel;
    }

    private BoxContainer CreateRecipeList(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        PersistentCraftRecipePrototype selected,
        Color accent)
    {
        var list = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        foreach (var tierGroup in recipes.GroupBy(recipe => recipe.Tier).OrderBy(group => group.Key))
        {
            list.AddChild(CreateTierHeader(tierGroup.Key, accent));
            list.AddChild(new Control { MinSize = new Vector2(1, 6) });

            foreach (var categoryGroup in tierGroup
                         .GroupBy(GetRecipeCategoryId)
                         .OrderBy(group => GetCategoryOrder(group.Key)))
            {
                var categoryKey = BuildCategoryGroupKey(branch, tierGroup.Key, categoryGroup.Key);
                EnsureCategoryCollapsedByDefault(categoryKey);
                var categoryCollapsed = _collapsedCategoryKeys.Contains(categoryKey);
                list.AddChild(CreateCategoryHeader(GetCategoryName(categoryGroup.Key), accent, categoryGroup.Count(), categoryCollapsed, categoryKey));
                list.AddChild(new Control { MinSize = new Vector2(1, 4) });

                if (categoryCollapsed)
                    continue;

                foreach (var subCategoryGroup in categoryGroup
                             .GroupBy(GetRecipeSubCategoryId)
                             .OrderBy(group => GetSubCategoryOrder(group.Key)))
                {
                    var subCategoryId = subCategoryGroup.Key;
                    if (!string.IsNullOrWhiteSpace(subCategoryId))
                    {
                        var subCategoryKey = BuildSubCategoryGroupKey(branch, tierGroup.Key, categoryGroup.Key, subCategoryId);
                        EnsureSubCategoryCollapsedByDefault(subCategoryKey);
                        var subCategoryCollapsed = _collapsedSubCategoryKeys.Contains(subCategoryKey);
                        list.AddChild(CreateSubCategoryHeader(GetSubCategoryName(subCategoryId), subCategoryGroup.Count(), subCategoryCollapsed, subCategoryKey));
                        list.AddChild(new Control { MinSize = new Vector2(1, 4) });

                        if (subCategoryCollapsed)
                            continue;
                    }

                    foreach (var recipe in subCategoryGroup.OrderBy(item => item.Tier).ThenBy(item => item.SubTier).ThenBy(item => item.ID))
                    {
                        list.AddChild(CreateRecipeListEntry(branch, recipe, selected.ID == recipe.ID));
                    }
                }
            }
        }

        return list;
    }

    private Control CreateTierHeader(int tier, Color accent)
    {
        var header = new PersistentCraftTierHeader();
        header.SetData(
            $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(tier)}",
            accent);
        return header;
    }

    private Control CreateCategoryHeader(string text, Color accent, int count, bool collapsed, string categoryKey)
    {
        var header = new PersistentCraftCollapsibleHeader();
        header.SetData(
            text,
            count,
            collapsed,
            accent,
            PersistentCraftUiTheme.SurfacePanelAlt,
            accent.WithAlpha(0.28f),
            new Thickness(0, 0, 0, 6),
            5);
        header.Button.OnPressed += _ => ToggleCategoryCollapse(categoryKey);
        return header;
    }

    private Control CreateSubCategoryHeader(string text, int count, bool collapsed, string subCategoryKey)
    {
        var header = new PersistentCraftCollapsibleHeader();
        header.SetData(
            text,
            count,
            collapsed,
            MutedText,
            PersistentCraftUiTheme.SurfacePanelSoft,
            CardMutedBorder,
            new Thickness(0),
            4);
        header.Button.OnPressed += _ => ToggleSubCategoryCollapse(subCategoryKey);
        return header;
    }

    private Control CreateRecipeListEntry(PersistentCraftBranch branch, PersistentCraftRecipePrototype recipe, bool selected)
    {
        var accent = GetAccent(recipe.Branch);
        var card = new PersistentCraftRecipeCard();
        card.Margin = new Thickness(0, 0, 0, 6);
        card.SetData(
            ResolveRecipeName(recipe),
            BuildRecipeSecondaryLine(recipe),
            CanViewRecipe(recipe) ? Color.White : MutedText,
            MutedText);
        card.Button.OnPressed += _ => SelectRecipe(recipe.Branch, recipe.ID);
        card.StatusContainer.AddChild(CreateRecipeStatusBadge(recipe));
        card.IconHost.AddChild(CreateRecipeIconContent(recipe, new Vector2(48, 48)));

        ApplyRecipeEntryVisuals(card.Button, card.IconHost, recipe, selected);
        _recipeEntryControlsByBranch[branch][recipe.ID] = new RecipeEntryControls(card.Button, card.IconHost);

        return card;
    }

    private PanelContainer CreateRecipeDetailsPanel(
        PersistentCraftRecipePrototype recipe,
        PersistentCraftBranchState branchState)
    {
        var loaded = _state?.Loaded == true;
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var hasMaterials = HasLocalMaterials(recipe);
        var canCraft = loaded && requirementMet && hasMaterials;
        var accent = GetAccent(recipe.Branch);

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PersistentCraftUiTheme.SurfacePanel,
                BorderColor = accent.WithAlpha(0.5f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 18,
                ContentMarginRightOverride = 18,
                ContentMarginTopOverride = 18,
                ContentMarginBottomOverride = 18,
            }
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        body.AddChild(CreateRecipeDetailHeader(recipe, branchState, canCraft, loaded, requirementMet, hasMaterials, accent));
        body.AddChild(new Control { MinSize = new Vector2(1, 12) });

        body.AddChild(CreateSection(
            Loc.GetString("persistent-craft-description-label"),
            $"[color={DescriptionText.ToHex()}]{FormattedMessage.EscapeText(ResolveRecipeDescription(recipe))}[/color]",
            10));
        body.AddChild(new Control { MinSize = new Vector2(1, 10) });

        body.AddChild(CreateSection(
            Loc.GetString("persistent-craft-recipe-ingredients"),
            BuildIngredientMarkup(recipe),
            10));
        body.AddChild(new Control { VerticalExpand = true });
        panel.AddChild(body);

        return panel;
    }

    private Control CreateSection(string title, string markupText, int padding)
    {
        var section = new PersistentCraftTextSection();
        section.SetData(title, markupText, CardMutedBorder, padding);
        return section;
    }

    private Control CreateRecipeDetailHeader(
        PersistentCraftRecipePrototype recipe,
        PersistentCraftBranchState branchState,
        bool canCraft,
        bool loaded,
        bool requirementMet,
        bool hasMaterials,
        Color accent)
    {
        var header = new PersistentCraftRecipeDetailHeader();
        header.SetData(
            ResolveRecipeName(recipe),
            Color.White,
            Loc.GetString("persistent-craft-recipe-action"),
            !canCraft);
        header.ActionButton.OnPressed += _ => OnCraftPressed?.Invoke(recipe.ID);
        header.InfoText.SetMessage(FormattedMessage.FromMarkupPermissive(BuildHeaderInfoMarkup(recipe)));
        header.IconHost.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = IconBackground,
            BorderColor = accent,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
        header.IconHost.AddChild(CreateRecipeIconContent(recipe, new Vector2(116, 116)));

        header.MetaContainer.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-branch-level-label")}: {FormatBranchLevel(branchState)}",
            PersistentCraftUiTheme.SurfacePanelAlt,
            PersistentCraftUiTheme.TextPrimary));
        header.MetaContainer.AddChild(new Control { MinSize = new Vector2(1, 6) });
        header.MetaContainer.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(recipe.Tier)} | {PersistentCraftingHelper.GetRecipeLevelText(recipe)}",
            PersistentCraftUiTheme.SurfacePanelAlt,
            accent));
        header.MetaContainer.AddChild(new Control { MinSize = new Vector2(1, 6) });
        header.MetaContainer.AddChild(CreateMetaBadge(
            GetRecipeCategoryPath(recipe),
            PersistentCraftUiTheme.SurfacePanelAlt,
            PersistentCraftUiTheme.TextMuted));
        header.MetaContainer.AddChild(new Control { MinSize = new Vector2(1, 6) });
        header.MetaContainer.AddChild(CreateMetaBadge(
            $"{Loc.GetString("persistent-craft-recipe-experience")}: +{PersistentCraftingHelper.GetExperienceReward(recipe)}",
            PersistentCraftUiTheme.SurfacePanelAlt,
            accent));

        return header;
    }

    private PanelContainer CreateRecipeIcon(PersistentCraftRecipePrototype recipe, Color accent, Vector2 size)
    {
        var panel = new PanelContainer
        {
            MinSize = size,
            RectClipContent = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = IconBackground,
                BorderColor = accent,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            },
        };

        panel.AddChild(CreateRecipeIconContent(recipe, size));

        return panel;
    }

    private Control CreateRecipeIconContent(PersistentCraftRecipePrototype recipe, Vector2 size)
    {
        if (TryGetRecipeTexture(recipe, out var texture))
        {
            return new TextureRect
            {
                Texture = texture,
                TextureScale = size.X >= 90 ? new Vector2(2.1f, 2.1f) : new Vector2(1.15f, 1.15f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
        }

        return new Label
        {
            Text = PersistentCraftingHelper.GetRecipeLevelText(recipe),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
    }

    private PanelContainer CreateMetaBadge(string text, Color background, Color foreground)
    {
        var badge = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderColor = PersistentCraftUiTheme.BorderSoft,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            }
        };

        badge.AddChild(new Label
        {
            Text = text,
            FontColorOverride = foreground,
            ClipText = true,
        });

        return badge;
    }

    private void SelectRecipe(PersistentCraftBranch branch, string recipeId)
    {
        RememberListScroll(branch);
        _detailScrollByBranch[branch] = Vector2.Zero;

        _selectedRecipes.TryGetValue(branch, out var previousRecipeId);
        _selectedRecipes[branch] = recipeId;

        if (branch == GetCurrentBranch() &&
            _recipeEntryControlsByBranch.TryGetValue(branch, out var entries) &&
            _detailContentHostsByBranch.ContainsKey(branch) &&
            _visibleBranchStatesByBranch.ContainsKey(branch))
        {
            if (!string.IsNullOrWhiteSpace(previousRecipeId) &&
                entries.TryGetValue(previousRecipeId, out var previousControls) &&
                _recipes.FirstOrDefault(recipe => recipe.ID == previousRecipeId) is { } previousRecipe)
            {
                ApplyRecipeEntryVisuals(previousControls.Button, previousControls.IconPanel, previousRecipe, false);
            }

            if (entries.TryGetValue(recipeId, out var selectedControls) &&
                _recipes.FirstOrDefault(recipe => recipe.ID == recipeId) is { } selectedRecipe)
            {
                ApplyRecipeEntryVisuals(selectedControls.Button, selectedControls.IconPanel, selectedRecipe, true);
                UpdateRecipeDetails(branch, selectedRecipe);
                return;
            }
        }

        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void SelectTierFilter(PersistentCraftBranch branch, int tier)
    {
        RememberListScroll(branch);
        _detailScrollByBranch[branch] = Vector2.Zero;
        _selectedTierFilters[branch] = tier;
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void UpdateSearch(PersistentCraftBranch branch, string text)
    {
        var normalized = text.Trim();
        if (GetSearchText(branch) == normalized)
            return;

        _searchTextByBranch[branch] = normalized;
        _listScrollByBranch[branch] = Vector2.Zero;
        _detailScrollByBranch[branch] = Vector2.Zero;
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void ToggleCraftableOnly(PersistentCraftBranch branch)
    {
        _craftableOnlyByBranch[branch] = !GetCraftableOnly(branch);
        _listScrollByBranch[branch] = Vector2.Zero;
        _detailScrollByBranch[branch] = Vector2.Zero;
        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void ToggleCategoryCollapse(string categoryKey)
    {
        var branch = GetCurrentBranch();
        RememberListScroll(branch);

        if (!_collapsedCategoryKeys.Add(categoryKey))
            _collapsedCategoryKeys.Remove(categoryKey);

        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void ToggleSubCategoryCollapse(string subCategoryKey)
    {
        var branch = GetCurrentBranch();
        RememberListScroll(branch);

        if (!_collapsedSubCategoryKeys.Add(subCategoryKey))
            _collapsedSubCategoryKeys.Remove(subCategoryKey);

        PopulateBranch(GetBranchContainer(branch), branch);
    }

    private void EnsureCategoryCollapsedByDefault(string categoryKey)
    {
        if (_initializedCategoryKeys.Add(categoryKey))
            _collapsedCategoryKeys.Add(categoryKey);
    }

    private void EnsureSubCategoryCollapsedByDefault(string subCategoryKey)
    {
        if (_initializedSubCategoryKeys.Add(subCategoryKey))
            _collapsedSubCategoryKeys.Add(subCategoryKey);
    }

    private void RememberBranchScroll(PersistentCraftBranch branch)
    {
        RememberListScroll(branch);

        if (_activeDetailScrollByBranch.TryGetValue(branch, out var detailScroll))
            _detailScrollByBranch[branch] = detailScroll.GetScrollValue(true);
    }

    private void RememberListScroll(PersistentCraftBranch branch)
    {
        if (_activeListScrollByBranch.TryGetValue(branch, out var listScroll))
            _listScrollByBranch[branch] = listScroll.GetScrollValue(true);
    }

    private void RestoreBranchScroll(PersistentCraftBranch branch, ScrollContainer listScroll, ScrollContainer detailScroll)
    {
        if (_listScrollByBranch.TryGetValue(branch, out var listScrollValue))
            listScroll.SetScrollValue(listScrollValue);

        if (_detailScrollByBranch.TryGetValue(branch, out var detailScrollValue))
            detailScroll.SetScrollValue(detailScrollValue);
    }

    private void UpdateRecipeDetails(PersistentCraftBranch branch, PersistentCraftRecipePrototype recipe)
    {
        if (!_detailContentHostsByBranch.TryGetValue(branch, out var detailHost) ||
            !_visibleBranchStatesByBranch.TryGetValue(branch, out var branchState))
        {
            PopulateBranch(GetBranchContainer(branch), branch);
            return;
        }

        detailHost.RemoveAllChildren();
        detailHost.AddChild(CreateRecipeDetailsPanel(recipe, branchState));

        if (_activeDetailScrollByBranch.TryGetValue(branch, out var detailScroll))
            detailScroll.SetScrollValue(Vector2.Zero);
    }

    private static string BuildCategoryGroupKey(PersistentCraftBranch branch, int tier, string categoryId)
    {
        return $"{branch}|{tier}|{categoryId}";
    }

    private static string BuildSubCategoryGroupKey(PersistentCraftBranch branch, int tier, string categoryId, string subCategoryId)
    {
        return $"{branch}|{tier}|{categoryId}|{subCategoryId}";
    }

    private string GetSearchText(PersistentCraftBranch branch)
    {
        return _searchTextByBranch.TryGetValue(branch, out var text) ? text : string.Empty;
    }

    private bool GetCraftableOnly(PersistentCraftBranch branch)
    {
        return _craftableOnlyByBranch.TryGetValue(branch, out var value) && value;
    }

    private List<PersistentCraftRecipePrototype> ApplyRecipeSearch(
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        string searchText)
    {
        if (string.IsNullOrWhiteSpace(searchText))
            return recipes.ToList();

        return recipes.Where(recipe => MatchesSearch(recipe, searchText)).ToList();
    }

    private List<PersistentCraftRecipePrototype> ApplyCraftableFilter(
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        bool craftableOnly)
    {
        if (!craftableOnly)
            return recipes.ToList();

        return recipes.Where(HasLocalMaterials).ToList();
    }

    private bool MatchesSearch(PersistentCraftRecipePrototype recipe, string searchText)
    {
        var query = searchText.Trim().ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(query))
            return true;

        return ResolveRecipeName(recipe).ToLowerInvariant().Contains(query) ||
               GetRecipeCategoryPath(recipe).ToLowerInvariant().Contains(query) ||
               PersistentCraftingHelper.GetRecipeLevelText(recipe).ToLowerInvariant().Contains(query) ||
               ResolveRecipeDescription(recipe).ToLowerInvariant().Contains(query);
    }

    private BoxContainer GetBranchContainer(PersistentCraftBranch branch) => branch switch
    {
        PersistentCraftBranch.Armor => ArmorBranch,
        PersistentCraftBranch.Anomaly => AnomalyBranch,
        _ => WeaponBranch,
    };

    private PersistentCraftBranch GetCurrentBranch() => Branches.CurrentTab switch
    {
        1 => PersistentCraftBranch.Armor,
        2 => PersistentCraftBranch.Anomaly,
        _ => PersistentCraftBranch.Weapon,
    };

    private PersistentCraftRecipePrototype ResolveSelectedRecipe(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes)
    {
        if (_selectedRecipes.TryGetValue(branch, out var selectedId))
        {
            var existing = recipes.FirstOrDefault(recipe => recipe.ID == selectedId);
            if (existing != null)
                return existing;
        }

        var fallback = _state == null
            ? recipes[0]
            : recipes.FirstOrDefault(recipe => HasRequirement(_state, recipe)) ?? recipes[0];

        _selectedRecipes[branch] = fallback.ID;
        return fallback;
    }

    private int GetSelectedTierFilter(
        PersistentCraftBranch branch,
        IReadOnlyList<PersistentCraftRecipePrototype> recipes,
        PersistentCraftBranchState branchState)
    {
        if (_selectedTierFilters.TryGetValue(branch, out var selectedTier) &&
            (selectedTier == 0 || recipes.Any(recipe => recipe.Tier == selectedTier)))
        {
            return selectedTier;
        }

        var preferredTier = 0;
        if (_state?.Loaded == true)
        {
            preferredTier = recipes
                .Where(recipe => HasRequirement(_state, recipe))
                .Select(recipe => recipe.Tier)
                .DefaultIfEmpty(Math.Min(branchState.Level, recipes.Max(recipe => recipe.Tier)))
                .Max();
        }

        _selectedTierFilters[branch] = preferredTier;
        return preferredTier;
    }

    private bool TryGetRecipeTexture(PersistentCraftRecipePrototype recipe, out Texture? texture)
    {
        texture = null;
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private bool HasRequirement(PersistentCraftState state, PersistentCraftRecipePrototype recipe)
    {
        var requiredNode = string.IsNullOrWhiteSpace(recipe.RequiredNode)
            ? PersistentCraftingHelper.BuildNodeId(recipe.Branch, recipe.Tier, recipe.SubTier)
            : recipe.RequiredNode;

        return !string.IsNullOrWhiteSpace(requiredNode) && HasNodeUnlockedOrAutoAvailable(state, requiredNode);
    }

    private string GetRequirementText(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            return $"{ResolveNodeName(node)} [{PersistentCraftingHelper.GetNodeLevelText(node)}]";
        }

        return $"{Loc.GetString(PersistentCraftingHelper.GetBranchLocKey(recipe.Branch))} {PersistentCraftingHelper.GetRecipeLevelText(recipe)}";
    }

    private bool CanViewRecipe(PersistentCraftRecipePrototype recipe)
    {
        return _state != null && HasRequirement(_state, recipe);
    }

    private Color GetRecipeMetaColor(PersistentCraftRecipePrototype recipe)
    {
        var loaded = _state?.Loaded == true;
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var hasMaterials = HasLocalMaterials(recipe);
        var canCraft = loaded && requirementMet && hasMaterials;
        var accent = GetAccent(recipe.Branch);

        return !requirementMet
            ? MissingColor
            : canCraft
                ? accent
                : hasMaterials
                    ? MutedText
                    : MissingColor;
    }

    private string BuildRecipeSecondaryLine(PersistentCraftRecipePrototype recipe)
    {
        var category = GetSubCategoryName(GetRecipeSubCategoryId(recipe));
        if (string.IsNullOrWhiteSpace(category))
            category = GetCategoryName(GetRecipeCategoryId(recipe));

        return $"{PersistentCraftingHelper.GetRecipeLevelText(recipe)} | {category}";
    }

    private Control CreateRecipeStatusBadge(PersistentCraftRecipePrototype recipe)
    {
        var statusKey = GetStatusKey(_state?.Loaded == true, _state != null && HasRequirement(_state, recipe), HasLocalMaterials(recipe));
        var foreground = GetRecipeMetaColor(recipe);
        var background = foreground.WithAlpha(0.16f);

        var badge = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = background.WithAlpha(0.9f),
                BorderColor = foreground.WithAlpha(0.45f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            }
        };
        badge.AddChild(new Label
        {
            Text = Loc.GetString(statusKey),
            FontColorOverride = foreground,
            ClipText = true,
        });

        return badge;
    }

    private void ApplyRecipeEntryVisuals(
        ContainerButton button,
        PanelContainer iconPanel,
        PersistentCraftRecipePrototype recipe,
        bool selected)
    {
        var requirementMet = _state != null && HasRequirement(_state, recipe);
        var accent = GetAccent(recipe.Branch);
        var background = requirementMet ? PersistentCraftUiTheme.SurfacePanel : PersistentCraftUiTheme.SurfacePanelSoft;
        var border = selected ? SelectedBorder : requirementMet ? accent.WithAlpha(0.55f) : CardBorder;

        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(selected ? 2 : 1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 10,
            ContentMarginBottomOverride = 10,
        };

        iconPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = IconBackground,
            BorderColor = selected ? SelectedBorder : accent.WithAlpha(0.65f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    private string BuildRecipeMasteryBadge(PersistentCraftRecipePrototype recipe)
    {
        return BuildTierProgressText(recipe.Branch, recipe.Tier);
    }

    private string BuildHeaderInfoMarkup(PersistentCraftRecipePrototype recipe)
    {
        var result = recipe.Results.FirstOrDefault();
        var resultText = result == null
            ? Loc.GetString("persistent-craft-none")
            : FormatResult(result);

        return $"[color={DescriptionText.ToHex()}]{FormattedMessage.EscapeText(resultText)}[/color]\n" +
               $"[color={MutedText.ToHex()}]{Loc.GetString("persistent-craft-recipe-time")}: {GetEffectiveCraftTime(recipe):0.#} {Loc.GetString("persistent-craft-recipe-seconds")}[/color]";
    }

    private string BuildRequirementMarkup(PersistentCraftRecipePrototype recipe)
    {
        if (TryResolveRequirementNode(recipe, out var node))
        {
            var mastery = BuildTierProgressText(node.Branch, node.Tier);
            var lines = new List<string>
            {
                $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(ResolveNodeName(node))} ({FormattedMessage.EscapeText(PersistentCraftingHelper.GetNodeLevelText(node))})[/color]",
                $"[color={MutedText.ToHex()}]- {FormattedMessage.EscapeText(mastery)}[/color]"
            };

            var requiredProgress = PersistentCraftingHelper.GetNodeRequiredTierProgressLevel(node);
            if (!PersistentCraftingHelper.IsMainTierNode(node) &&
                requiredProgress > PersistentCraftingHelper.InitialTierProgressLevel)
            {
                lines.Add($"[color={MutedText.ToHex()}]- {Loc.GetString("persistent-craft-tier-progress-required", ("subLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(node.Tier, requiredProgress)))}[/color]");
            }

            return string.Join("\n", lines);
        }

        return $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(GetRequirementText(recipe))}[/color]";
    }

    private string BuildTierProgressText(PersistentCraftBranch branch, int tier)
    {
        var tierState = GetTierState(branch, tier);
        if (tierState == null)
        {
            return Loc.GetString(
                "persistent-craft-node-mastery-short",
                ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(
                    tier,
                    PersistentCraftingHelper.InitialTierProgressLevel)),
                ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(
                    tier,
                    PersistentCraftingHelper.DefaultMaxTierProgressLevel)));
        }

        if (tierState.ExperienceForNextLevel <= 0)
        {
            return Loc.GetString(
                "persistent-craft-node-mastery-max",
                ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, tierState.ProgressLevel)),
                ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, tierState.MaxProgressLevel)));
        }

        return Loc.GetString(
            "persistent-craft-node-mastery-progress",
            ("currentSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, tierState.ProgressLevel)),
            ("targetSubLevel", PersistentCraftingHelper.FormatTierProgressSubLevel(tier, tierState.MaxProgressLevel)),
            ("experience", tierState.Experience),
            ("next", tierState.ExperienceForNextLevel));
    }

    private bool TryResolveRequirementNode(PersistentCraftRecipePrototype recipe, out PersistentCraftNodePrototype node)
    {
        var requiredNode = string.IsNullOrWhiteSpace(recipe.RequiredNode)
            ? PersistentCraftingHelper.BuildNodeId(recipe.Branch, recipe.Tier, recipe.SubTier)
            : recipe.RequiredNode;

        PersistentCraftNodePrototype? resolvedNode;
        if (!string.IsNullOrWhiteSpace(requiredNode) &&
            _prototype.TryIndex<PersistentCraftNodePrototype>(requiredNode, out resolvedNode) &&
            resolvedNode != null)
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private void SelectPreferredBranchTab()
    {
        if (_state == null)
            return;

        var preferred = PersistentCraftingHelper.EnumerateBranches()
            .Select(branch => new
            {
                Branch = branch,
                Recipes = _recipes.Count(recipe => recipe.Branch == branch && HasRequirement(_state, recipe)),
                Points = GetBranchState(_state, branch).AvailablePoints,
            })
            .OrderByDescending(entry => entry.Recipes)
            .ThenByDescending(entry => entry.Points)
            .FirstOrDefault(entry => entry.Recipes > 0 || entry.Points > 0);

        if (preferred != null)
            Branches.CurrentTab = GetBranchTabIndex(preferred.Branch);
    }

    private static int GetBranchTabIndex(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => 0,
            PersistentCraftBranch.Armor => 1,
            PersistentCraftBranch.Anomaly => 2,
            _ => 0,
        };
    }

    private string GetRecipeCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.Category))
            return recipe.Category!;

        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe) ?? string.Empty;

        return recipe.Branch switch
        {
            PersistentCraftBranch.Weapon when displayProto.Contains("Mag") => "magazines",
            PersistentCraftBranch.Weapon when displayProto.Contains("Box") => "ammo",
            PersistentCraftBranch.Weapon => "weapons",

            PersistentCraftBranch.Armor when displayProto.StartsWith("Medkit") => "medicine",
            PersistentCraftBranch.Armor when displayProto.StartsWith("ClothingBackpack") => "bags",
            PersistentCraftBranch.Armor when displayProto.StartsWith("ClothingHeadHelmet") || displayProto.StartsWith("ClothingMask") => "headgear",
            PersistentCraftBranch.Armor => "armor",

            PersistentCraftBranch.Anomaly when displayProto.Contains("ArtifactContainer") => "containers",
            PersistentCraftBranch.Anomaly when displayProto.StartsWith("ZoneAnomalyDetector") => "anomaly-detectors",
            PersistentCraftBranch.Anomaly when displayProto.StartsWith("ZoneArtifactDetector") => "artifact-detectors",
            _ => "special",
        };
    }

    private string GetRecipeSubCategoryId(PersistentCraftRecipePrototype recipe)
    {
        if (!string.IsNullOrWhiteSpace(recipe.SubCategory))
            return recipe.SubCategory!;

        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe) ?? string.Empty;
        var category = GetRecipeCategoryId(recipe);

        if (recipe.Branch == PersistentCraftBranch.Weapon)
        {
            if (displayProto.Contains("545") || displayProto.Contains("AKS74") || displayProto.Contains("AK74") || displayProto.Contains("A545") || displayProto.Contains("AK12") || displayProto.Contains("RPK16"))
                return "caliber-545";

            if (displayProto.Contains("556") || displayProto.Contains("M16") || displayProto.Contains("M4") || displayProto.Contains("G36") || displayProto.Contains("HK416") || displayProto.Contains("SCARL") || displayProto.Contains("F2000"))
                return "caliber-556";
        }

        if (recipe.Branch == PersistentCraftBranch.Armor)
        {
            if (category == "headgear")
                return displayProto.StartsWith("ClothingMask") ? "masks" : "helmets";

            if (category == "bags")
                return "backpacks";

            if (category == "medicine")
                return "medkits";
        }

        if (recipe.Branch == PersistentCraftBranch.Anomaly)
        {
            return category switch
            {
                "anomaly-detectors" => "scanner-line",
                "artifact-detectors" => "artifact-line",
                "containers" => "containers-line",
                _ => $"tier-{recipe.Tier}",
            };
        }

        return string.Empty;
    }

    private string GetCategoryName(string categoryId)
    {
        var locKey = $"persistent-craft-category-{categoryId}";
        return TryLoc(locKey) ?? categoryId;
    }

    private string GetSubCategoryName(string subCategoryId)
    {
        if (string.IsNullOrWhiteSpace(subCategoryId))
            return string.Empty;

        if (subCategoryId.StartsWith("tier-") && int.TryParse(subCategoryId["tier-".Length..], out var tier))
            return $"{Loc.GetString("persistent-craft-level-label")} {PersistentCraftingHelper.GetTierDisplayLabel(tier)}";

        var locKey = $"persistent-craft-subcategory-{subCategoryId}";
        return TryLoc(locKey) ?? subCategoryId;
    }

    private static int GetCategoryOrder(string categoryId)
    {
        return categoryId switch
        {
            "ammo" => 0,
            "magazines" => 1,
            "weapons" => 2,
            "armor" => 0,
            "headgear" => 1,
            "bags" => 2,
            "medicine" => 3,
            "anomaly-detectors" => 0,
            "artifact-detectors" => 1,
            "containers" => 2,
            _ => 99,
        };
    }

    private static int GetSubCategoryOrder(string subCategoryId)
    {
        return subCategoryId switch
        {
            "caliber-545" => 0,
            "caliber-556" => 1,
            "helmets" => 0,
            "masks" => 1,
            "backpacks" => 0,
            "medkits" => 1,
            "scanner-line" => 0,
            "artifact-line" => 1,
            "containers-line" => 2,
            _ => 99,
        };
    }

    private static string? TryLoc(string locKey)
    {
        try
        {
            return Loc.GetString(locKey);
        }
        catch
        {
            return null;
        }
    }

    private string GetRecipeCategoryPath(PersistentCraftRecipePrototype recipe)
    {
        var category = GetCategoryName(GetRecipeCategoryId(recipe));
        var subCategory = GetSubCategoryName(GetRecipeSubCategoryId(recipe));

        return string.IsNullOrWhiteSpace(subCategory)
            ? category
            : $"{category} / {subCategory}";
    }

    private bool HasNodeUnlockedOrAutoAvailable(PersistentCraftState state, string nodeId)
    {
        return HasNodeUnlockedOrAutoAvailable(state, nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(PersistentCraftState state, string nodeId, HashSet<string> path)
    {
        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
            return false;

        if (!PersistentCraftingHelper.IsStarterSubTierNode(node) && node.Cost > 0)
            return false;

        var branchState = GetBranchState(state, node.Branch);
        if (branchState.Level < PersistentCraftingHelper.GetNodeRequiredBranchLevel(node))
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(state, prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private string BuildIngredientMarkup(PersistentCraftRecipePrototype recipe)
    {
        return string.Join("\n", recipe.Ingredients.Select(ingredient => FormatIngredientLine(recipe, ingredient)));
    }

    private string BuildResultMarkup(PersistentCraftRecipePrototype recipe)
    {
        return string.Join("\n", recipe.Results.Select(result =>
            $"[color={DescriptionText.ToHex()}]- {FormattedMessage.EscapeText(FormatResult(result))}[/color]"));
    }

    private string FormatIngredient(PersistentCraftIngredient ingredient)
    {
        var name = !string.IsNullOrWhiteSpace(ingredient.Proto)
            ? ResolveEntityName(ingredient.Proto)
            : $"#{ingredient.Tag}";

        return $"{name} x{ingredient.Amount}";
    }

    private string FormatResult(PersistentCraftResult result)
    {
        return $"{ResolveEntityName(result.Proto)} x{result.Amount}";
    }

    private string FormatIngredientLine(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var requiredAmount = GetEffectiveIngredientAmount(recipe, ingredient);
        var owned = GetOwnedAmount(ingredient);
        var enough = owned >= requiredAmount;
        var color = enough ? EnoughColor : MissingColor;
        return $"[color={color.ToHex()}]- {FormattedMessage.EscapeText(FormatIngredient(ingredient))} ({owned}/{requiredAmount})[/color]";
    }

    private bool HasLocalMaterials(PersistentCraftRecipePrototype recipe)
    {
        return recipe.Ingredients.All(ingredient => GetOwnedAmount(ingredient) >= GetEffectiveIngredientAmount(recipe, ingredient));
    }

    private int GetOwnedAmount(PersistentCraftIngredient ingredient)
    {
        var cacheKey = GetIngredientCacheKey(ingredient);
        if (_ownedAmountCache.TryGetValue(cacheKey, out var cached))
            return cached;

        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return 0;

        var amount = PersistentCraftInventoryHelper.CountIngredientAmount(
            _entityManager,
            _prototype,
            _tag,
            user,
            ingredient);
        _ownedAmountCache[cacheKey] = amount;
        return amount;
    }

    private string ResolveEntityName(string prototypeId)
    {
        return _prototype.TryIndex<EntityPrototype>(prototypeId, out var prototype)
            ? prototype.Name
            : prototypeId;
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveRecipeDescription(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype) &&
            !string.IsNullOrWhiteSpace(prototype.Description))
        {
            return prototype.Description;
        }

        return Loc.GetString(recipe.Description);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        return string.IsNullOrWhiteSpace(node.Name)
            ? PersistentCraftingHelper.GetNodeLevelText(node)
            : Loc.GetString(node.Name);
    }

    private PersistentCraftBranchState GetBranchState(PersistentCraftState state, PersistentCraftBranch branch)
    {
        return state.BranchStates.FirstOrDefault(item => item.Branch == branch) ??
               new PersistentCraftBranchState(
                   branch,
                   GetBranchMaxLevel(branch),
                   0,
                   0,
                   PersistentCraftingHelper.InitialLevel,
                   PersistentCraftingHelper.MainTierSubLevel,
                   0,
                   PersistentCraftingHelper.GetExperienceForNextLevel(PersistentCraftingHelper.InitialLevel));
    }

    private int GetBranchMaxLevel(PersistentCraftBranch branch)
    {
        return _recipes
            .Where(recipe => recipe.Branch == branch)
            .Select(recipe => recipe.Tier)
            .DefaultIfEmpty(PersistentCraftingHelper.InitialLevel)
            .Max();
    }

    private static string FormatBranchLevel(PersistentCraftBranchState branchState)
    {
        return PersistentCraftingHelper.FormatCappedLevel(branchState.Level, branchState.MaxLevel);
    }

    private static string FormatBranchExperience(PersistentCraftBranchState branchState)
    {
        return branchState.ExperienceForNextLevel <= 0
            ? Loc.GetString("persistent-craft-max-label")
            : $"{branchState.Experience}/{branchState.ExperienceForNextLevel}";
    }

    private PersistentCraftTierState? GetTierState(PersistentCraftBranch branch, int tier)
    {
        return _state?.TierStates.FirstOrDefault(item => item.Branch == branch && item.Tier == tier);
    }

    private static string GetStatusKey(bool loaded, bool requirementMet, bool hasMaterials)
    {
        if (!loaded)
            return "persistent-craft-station-status-loading";

        if (!requirementMet)
            return "persistent-craft-station-status-locked";

        return hasMaterials
            ? "persistent-craft-station-status-available"
            : "persistent-craft-station-status-missing-materials";
    }

    private static Color GetAccent(PersistentCraftBranch branch)
    {
        return branch switch
        {
            PersistentCraftBranch.Weapon => AccentWeapon,
            PersistentCraftBranch.Armor => AccentArmor,
            PersistentCraftBranch.Anomaly => AccentAnomaly,
            _ => CardBorder,
        };
    }

    private static string GetIngredientCacheKey(PersistentCraftIngredient ingredient)
    {
        return $"{ingredient.Proto ?? string.Empty}|{ingredient.Tag ?? string.Empty}";
    }

    private string BuildInventorySignature()
    {
        if (_player.LocalEntity is not { Valid: true } user || !_entityManager.EntityExists(user))
            return string.Empty;

        var builder = new StringBuilder();
        var accessibleEntities = PersistentCraftInventoryHelper.CollectAccessibleEntities(_entityManager, user)
            .OrderBy(entity => entity.Id);

        foreach (var entity in accessibleEntities)
        {
            builder.Append(entity.Id);
            builder.Append(':');
            builder.Append(PersistentCraftInventoryHelper.GetUsableAmount(_entityManager, entity));
            builder.Append(';');
        }

        return builder.ToString();
    }

    private float GetEffectiveCraftTime(PersistentCraftRecipePrototype recipe)
    {
        var reduction = GetUnlockedNodeEffects(recipe)
            .Where(entry => entry.Node.CraftTimeReductionPercent > 0)
            .Sum(entry => entry.Node.CraftTimeReductionPercent * GetTierEffectMultiplier(entry.TierState));

        var multiplier = Math.Max(0.25f, 1f - reduction / 100f);
        return MathF.Max(0.25f, recipe.CraftTime * multiplier);
    }

    private int GetEffectiveIngredientAmount(PersistentCraftRecipePrototype recipe, PersistentCraftIngredient ingredient)
    {
        var reduction = GetUnlockedNodeEffects(recipe)
            .Where(entry => entry.Node.MaterialCostReductionPercent > 0)
            .Sum(entry => entry.Node.MaterialCostReductionPercent * GetTierEffectMultiplier(entry.TierState));

        var multiplier = Math.Max(0.25f, 1f - reduction / 100f);
        return Math.Max(1, (int) MathF.Ceiling(ingredient.Amount * multiplier));
    }

    private IEnumerable<(PersistentCraftNodePrototype Node, PersistentCraftTierState? TierState)> GetUnlockedNodeEffects(PersistentCraftRecipePrototype recipe)
    {
        if (_state == null)
            yield break;

        var tierState = GetTierState(recipe.Branch, recipe.Tier);

        foreach (var nodeId in _state.UnlockedNodes)
        {
            if (!_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var node))
                continue;

            if (node.Branch != recipe.Branch)
                continue;

            if (PersistentCraftingHelper.GetAffectedTier(node) != recipe.Tier)
                continue;

            yield return (node, tierState);
        }
    }

    private static float GetTierEffectMultiplier(PersistentCraftTierState? tierState)
    {
        if (tierState == null)
            return 0.5f;

        var max = Math.Max(PersistentCraftingHelper.InitialTierProgressLevel, tierState.MaxProgressLevel);
        var level = Math.Clamp(tierState.ProgressLevel, PersistentCraftingHelper.InitialTierProgressLevel, max);
        if (max <= PersistentCraftingHelper.InitialTierProgressLevel)
            return 1f;

        var normalized = (level - PersistentCraftingHelper.InitialTierProgressLevel) /
                         (float) (max - PersistentCraftingHelper.InitialTierProgressLevel);
        return 0.5f + normalized * 0.5f;
    }
}
