using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting;
using Content.Client._Stalker.PersistentCrafting.UI.Coordinators;
using Content.Client._Stalker.PersistentCrafting.UI.Indexes;
using Content.Client._Stalker.PersistentCrafting.UI.ViewModels;
using Content.Client._Stalker.PersistentCrafting.UI.Services;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IClyde _clyde = default!;

    private static readonly Color PanelBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardUnlockedBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardLockedBackground = PersistentCraftUiTheme.SurfacePanelSoft;
    private static readonly Color CardAvailableBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color UnlockedBorder = PersistentCraftUiTheme.Success;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color HeaderTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color MutedTextColor = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private const float WindowMinWidth = 1620f;
    private const float WindowMinHeight = 940f;
    private const float WindowOpenMargin = 56f;
    private const float BaseTierTreeNodeWidth = 176f;
    private const float BaseTierTreeNodeHeight = 178f;
    private const float BaseTierTreeHorizontalGap = 56f;
    private const float BaseTierTreeVerticalGap = 36f;
    private const float BaseTierTreePadding = 24f;
    private const float BaseTierTreeLineThickness = 3f;
    private const float TreeZoomMin = 0.65f;
    private const float TreeZoomMax = 1.6f;
    private const float TreeZoomStep = 0.1f;
    private const float NodeDetailsWindowWidth = 560f;
    private const float NodeDetailsWindowHeight = 430f;
    private const float NodeDetailsWindowMinWidth = 420f;
    private const float NodeDetailsWindowMinHeight = 300f;
    private const float NodeDetailsWindowMargin = 24f;
    private const float NodeIconScaleLarge = 2.1f;
    private const float NodeIconScaleSmall = 1.25f;
    private const int NodeIconLargeThreshold = 100;
    private static readonly ISawmill Sawmill = Logger.GetSawmill("persistent-craft.ui.skilltree");

    private readonly Dictionary<string, BoxContainer> _branchHosts = new();
    private readonly Dictionary<string, PersistentCraftTreeScrollContainer> _branchTreeScrolls = new();
    private readonly Dictionary<string, Dictionary<string, UIBox2>> _nodeBoundsByBranch = new();
    private readonly HashSet<string> _reusablePath = new();
    private readonly PersistentCraftSkillTreeViewModel _viewModel = new();
    private readonly PersistentCraftBranchCoordinator _branchCoordinator;
    private readonly PersistentCraftNodeSelectionCoordinator _selectionCoordinator;
    private readonly PersistentCraftNodeDetailsWindowCoordinator _detailsCoordinator;
    private PersistentCraftTextResolver _textResolver = default!;

    private PersistentCraftRecipeIndex? _recipeIndex;
    private PersistentCraftState? _state;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private IReadOnlyList<PersistentCraftNodePrototype> _nodes = Array.Empty<PersistentCraftNodePrototype>();
    private IReadOnlyList<PersistentCraftRecipePrototype> _recipes = Array.Empty<PersistentCraftRecipePrototype>();
    private Action<string>? _onUnlock;
    private string? _detailsNodeId;
    private int _detailsAvailablePoints = int.MinValue;
    private int _detailsSpentPoints = int.MinValue;
    private bool _detailsDirty;
    private float _treeZoom = 1f;
    private (string Branch, string NodeId)? _pendingNodeFocus;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);
        _selectionCoordinator = new PersistentCraftNodeSelectionCoordinator(_viewModel);
        _detailsCoordinator = new PersistentCraftNodeDetailsWindowCoordinator(
            _clyde,
            NodeDetailsWindowWidth,
            NodeDetailsWindowHeight,
            NodeDetailsWindowMinWidth,
            NodeDetailsWindowMinHeight,
            NodeDetailsWindowMargin);
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);
        _branchCoordinator = new PersistentCraftBranchCoordinator(_branchRegistry, _branchHosts);
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);

        RobustXamlLoader.Load(this);

        CloseTreeWindowButton.OnPressed += _ => Close();
        TreeZoomOutButton.OnPressed += _ => ChangeTreeZoom(-TreeZoomStep);
        TreeZoomInButton.OnPressed += _ => ChangeTreeZoom(TreeZoomStep);
        TreeZoomResetButton.OnPressed += _ => ResetTreeZoom();
        TreeFitSelectedButton.OnPressed += _ => FocusSelectedNode(fitZoom: true);

        InitializeBranchHosts();
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-skill-tabs", PersistentCraftUiTheme.Selection, _uiManager);
        RefreshZoomLabel();

        Branches.OnTabChanged += _ =>
        {
            CloseNodeDetailsWindow();
            var branch = _branchCoordinator.GetCurrentBranch(Branches);
            RenderBranch(branch);
            FocusSelectedNode(fitZoom: false);
        };
    }

    public PersistentCraftingWindow(PersistentCraftClientPrototypeCache prototypeCache) : this()
    {
        _prototypeCache = prototypeCache;
        _branchRegistry = prototypeCache.BranchRegistry;
        _branchCoordinator.SetBranchRegistry(_branchRegistry);
        _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
        InitializeBranchHosts();
    }

    private void InitializeBranchHosts()
    {
        Branches.RemoveAllChildren();
        _branchHosts.Clear();
        _branchTreeScrolls.Clear();
        _nodeBoundsByBranch.Clear();

        for (var index = 0; index < _branchRegistry.OrderedBranches.Count; index++)
        {
            var definition = _branchRegistry.OrderedBranches[index];
            var branchId = definition.ID;
            var host = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(12, 12, 12, 12),
            };

            var scroll = new PersistentCraftTreeScrollContainer
            {
                MinSize = new Vector2(980, 0),
                HorizontalExpand = true,
                HScrollEnabled = true,
                VerticalExpand = true,
            };
            scroll.ZoomRequested += delta => ChangeTreeZoom(delta > 0f ? TreeZoomStep : -TreeZoomStep);
            scroll.AddChild(host);
            Branches.AddChild(scroll);

            _branchHosts[branchId] = host;
            _branchTreeScrolls[branchId] = scroll;
            Branches.SetTabTitle(index, _textResolver.ResolveBranchTitle(definition));
        }
    }

    public void ApplyFullscreenLayout()
    {
        var uiScale = MathF.Max(_uiManager.RootControl.UIScale, 0.01f);
        var screenSize = new Vector2(_clyde.ScreenSize.X, _clyde.ScreenSize.Y) / uiScale;
        var targetWidth = MathF.Max(360f, screenSize.X - WindowOpenMargin);
        var targetHeight = MathF.Max(260f, screenSize.Y - WindowOpenMargin);

        MinSize = new Vector2(
            MathF.Min(WindowMinWidth, targetWidth),
            MathF.Min(WindowMinHeight, targetHeight));
        SetSize = new Vector2(targetWidth, targetHeight);
    }

    public override void Close()
    {
        CloseNodeDetailsWindow();
        _pendingNodeFocus = null;
        base.Close();
    }

    public void UpdateState(
        PersistentCraftState state,
        PersistentCraftClientPrototypeCache prototypeCache,
        Action<string> onUnlock)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _recipeIndex = PersistentCraftRecipeIndex.Create(prototypeCache);
            _branchRegistry = prototypeCache.BranchRegistry;
            _branchCoordinator.SetBranchRegistry(_branchRegistry);
            _textResolver = new PersistentCraftTextResolver(_prototype, _branchRegistry, PersistentCraftRecipeMetadataIndex.Empty);
            InitializeBranchHosts();
        }

        _state = state;
        _branchCoordinator.RebuildBranchStateIndex(state);
        _nodes = prototypeCache.AllNodes;
        _recipes = prototypeCache.AllRecipes;
        _onUnlock = onUnlock;
        _detailsDirty = true;

        if (state.Loaded && _viewModel.SelectPreferredBranchOnNextUpdate)
        {
            _branchCoordinator.SelectPreferredBranchTab(Branches);
            _viewModel.SelectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _viewModel.SelectPreferredBranchOnNextUpdate = true;
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderBranch(_branchCoordinator.GetCurrentBranch(Branches));
    }

    private void RenderBranch(string branch)
    {
        var subNodeHost = _branchCoordinator.GetBranchHost(branch);
        subNodeHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchSubNodes = GetNodesForBranch(branch);

        if (branchSubNodes.Count == 0)
        {
            _nodeBoundsByBranch.Remove(branch);
            CloseNodeDetailsWindow();
            return;
        }

        var branchState = _branchCoordinator.GetBranchState(branch);
        var selectedNode = _selectionCoordinator.ResolveSelectedNode(branch, branchSubNodes);

        subNodeHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-tree-label")));
        subNodeHost.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}",
            FontColorOverride = GetBranchAccent(branch),
        });
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        subNodeHost.AddChild(CreateSubNodeTree(branch, branchSubNodes, selectedNode?.ID));

        if (selectedNode == null)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_detailsCoordinator.IsOpen)
        {
            RefreshNodeDetailsIfNeeded(branchState, selectedNode);
        }
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private void SelectNode(string branch, string nodeId)
    {
        var selectionDecision = _selectionCoordinator.OnNodePressed(branch, nodeId, _detailsCoordinator.IsOpen);
        if (selectionDecision.ShouldCloseDetails)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_state == null)
            return;

        if (selectionDecision.SelectedNodeId is not { } selectedNodeId)
            return;

        if (!TryGetNodePrototype(selectedNodeId, out var node) ||
            !string.Equals(node.Branch, branch, StringComparison.Ordinal))
        {
            return;
        }

        var branchState = _branchCoordinator.GetBranchState(branch);
        ShowNodeDetailsWindow(branchState, node);
        ScheduleNodeFocus(branch, node.ID);
    }

    private void RefreshNodeDetailsIfNeeded(PersistentCraftBranchState branchState, PersistentCraftNodePrototype node)
    {
        if (!_detailsCoordinator.IsOpen)
            return;

        if (!_detailsDirty &&
            _detailsNodeId == node.ID &&
            _detailsAvailablePoints == branchState.AvailablePoints &&
            _detailsSpentPoints == branchState.SpentPoints)
        {
            return;
        }

        ShowNodeDetailsWindow(branchState, node);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled ||
            !_detailsCoordinator.IsOpen ||
            args.Function != EngineKeyFunctions.UIClick)
        {
            return;
        }

        CloseNodeDetailsWindow();
        args.Handle();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_pendingNodeFocus is not { } pending)
            return;

        if (TryCenterNode(pending.Branch, pending.NodeId))
            _pendingNodeFocus = null;
    }

    private void MarkDetailsShown(PersistentCraftBranchState branchState, PersistentCraftNodePrototype node)
    {
        _detailsNodeId = node.ID;
        _detailsAvailablePoints = branchState.AvailablePoints;
        _detailsSpentPoints = branchState.SpentPoints;
        _detailsDirty = false;
    }

    private void ResetDetailsCache()
    {
        _detailsNodeId = null;
        _detailsAvailablePoints = int.MinValue;
        _detailsSpentPoints = int.MinValue;
        _detailsDirty = false;
    }

    private void ChangeTreeZoom(float delta)
    {
        var newZoom = Math.Clamp(_treeZoom + delta, TreeZoomMin, TreeZoomMax);
        if (Math.Abs(newZoom - _treeZoom) < 0.001f)
            return;

        _treeZoom = newZoom;
        RefreshZoomLabel();
        Render();
        FocusSelectedNode(fitZoom: false);
    }

    private void ResetTreeZoom()
    {
        _treeZoom = 1f;
        RefreshZoomLabel();
        Render();
        FocusSelectedNode(fitZoom: false);
    }

    private void RefreshZoomLabel()
    {
        TreeZoomResetButton.Text = $"{MathF.Round(_treeZoom * 100f):0}%";
    }

    private void FocusSelectedNode(bool fitZoom)
    {
        var branch = _branchCoordinator.GetCurrentBranch(Branches);
        if (!_viewModel.TryGetSelectedNode(branch, out var nodeId))
            return;

        if (fitZoom && Math.Abs(_treeZoom - 1f) > 0.001f)
        {
            _treeZoom = 1f;
            RefreshZoomLabel();
            Render();
        }

        ScheduleNodeFocus(branch, nodeId);
    }

    private void ScheduleNodeFocus(string branch, string nodeId)
    {
        _pendingNodeFocus = (branch, nodeId);
        TryCenterNode(branch, nodeId);
    }

    private bool TryCenterNode(string branch, string nodeId)
    {
        if (!_branchTreeScrolls.TryGetValue(branch, out var scroll) ||
            !_nodeBoundsByBranch.TryGetValue(branch, out var nodeBoundsById) ||
            !nodeBoundsById.TryGetValue(nodeId, out var nodeBounds) ||
            scroll.Size.X <= 1f ||
            scroll.Size.Y <= 1f)
        {
            return false;
        }

        var target = new Vector2(
            MathF.Max(0f, ((nodeBounds.Left + nodeBounds.Right) * 0.5f) - scroll.Size.X / 2f),
            MathF.Max(0f, ((nodeBounds.Top + nodeBounds.Bottom) * 0.5f) - scroll.Size.Y / 2f));

        scroll.SetScrollValue(target);
        return true;
    }

    private sealed class PersistentCraftTreeScrollContainer : ScrollContainer
    {
        private bool _dragging;
        private Vector2 _dragStartMouse;
        private Vector2 _dragStartScroll;

        public event Action<float>? ZoomRequested;

        public PersistentCraftTreeScrollContainer()
        {
            MouseFilter = MouseFilterMode.Stop;
        }

        protected override void KeyBindDown(GUIBoundKeyEventArgs args)
        {
            base.KeyBindDown(args);

            if (args.Function != EngineKeyFunctions.UIRightClick)
                return;

            _dragging = true;
            _dragStartMouse = (Vector2) args.PointerLocation.Position;
            _dragStartScroll = GetScrollValue(true);
            args.Handle();
        }

        protected override void KeyBindUp(GUIBoundKeyEventArgs args)
        {
            base.KeyBindUp(args);

            if (args.Function != EngineKeyFunctions.UIRightClick)
                return;

            _dragging = false;
            args.Handle();
        }

        protected override void MouseMove(GUIMouseMoveEventArgs args)
        {
            base.MouseMove(args);

            if (!_dragging)
                return;

            var mousePosition = (Vector2) args.GlobalPixelPosition.Position;
            var delta = mousePosition - _dragStartMouse;
            SetScrollValue(_dragStartScroll - delta);
            args.Handle();
        }

        protected override void MouseWheel(GUIMouseWheelEventArgs args)
        {
            if (ZoomRequested == null)
            {
                base.MouseWheel(args);
                return;
            }

            ZoomRequested.Invoke(args.Delta.Y);
            args.Handle();
        }
    }
}
