using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Roles;

[GenerateTypedNameReferences]
public sealed partial class RoleRulesWindow : DefaultWindow
{
    public RoleRulesWindow(string jobName, string rules)
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("role-rules-window-title", ("job", jobName));
        RulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive(rules));
    }
}
