using Content.Shared._Stalker_EN.BulletinBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.BulletinBoard;

/// <summary>
/// Post form page for creating a new offer on a bulletin board.
/// Display text is driven by <see cref="STBulletinBoardConfig"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STBulletinPostPage : BoxContainer
{
    private const int DefaultMaxDescriptionLength = 300;
    private int _maxDescriptionLength = DefaultMaxDescriptionLength;

    /// <summary>Raised when the user presses the back button.</summary>
    public event Action? OnBack;

    /// <summary>Raised when the user submits a new offer. Args: category, description.</summary>
    public event Action<STBulletinCategory, string>? OnSubmit;

    private STBulletinCategory _category;

    public STBulletinPostPage()
    {
        RobustXamlLoader.Load(this);

        BackButton.OnPressed += _ => OnBack?.Invoke();

        SubmitButton.OnPressed += _ =>
        {
            var description = Rope.Collapse(DescriptionInput.TextRope).Trim();

            if (string.IsNullOrEmpty(description))
                return;

            if (description.Length > _maxDescriptionLength)
                description = description[.._maxDescriptionLength];

            OnSubmit?.Invoke(_category, description);
            ClearForm();
        };

        DescriptionInput.OnTextChanged += _ => UpdateCharCounter();
        UpdateCharCounter();
    }

    /// <summary>
    /// Configures the form for the given category using config from the board.
    /// </summary>
    public void SetCategory(STBulletinCategory category, STBulletinBoardConfig? config)
    {
        _category = category;

        if (config != null)
        {
            _maxDescriptionLength = config.MaxDescriptionLength;

            TitleLabel.Text = category == STBulletinCategory.Primary
                ? Loc.GetString(config.NewPrimaryTitle)
                : Loc.GetString(config.NewSecondaryTitle);

            BackButton.Text = Loc.GetString("st-bulletin-back");
            SubmitButton.Text = Loc.GetString("st-bulletin-post-submit");
            DescriptionFieldLabel.Text = Loc.GetString("st-bulletin-description-label");
        }

        ClearForm();
    }

    private void ClearForm()
    {
        DescriptionInput.TextRope = Rope.Leaf.Empty;
        UpdateCharCounter();
    }

    private void UpdateCharCounter()
    {
        var length = (int) Rope.CalcTotalLength(DescriptionInput.TextRope);
        var remaining = _maxDescriptionLength - length;
        CharCounter.Text = Loc.GetString("st-bulletin-char-counter",
            ("remaining", remaining), ("max", _maxDescriptionLength));
        CharCounter.FontColorOverride = remaining < 0 ? Color.Red : null;
    }
}
