using Content.Shared._Stalker_EN.BulletinBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.BulletinBoard;

/// <summary>
/// Main page of a bulletin board with Primary and Secondary tabs.
/// All display text is driven by <see cref="STBulletinBoardConfig"/> from the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STBulletinMainPage : BoxContainer
{
    /// <summary>Raised when the user presses the Post button. Arg = category to post.</summary>
    public event Action<STBulletinCategory>? OnPostPressed;

    /// <summary>Raised when the user presses Withdraw on their own offer. Arg = offer ID.</summary>
    public event Action<uint>? OnWithdrawPressed;

    /// <summary>Raised when the user presses Contact on another player's offer. Args: (posterMessengerId, offerId).</summary>
    public event Action<string, uint>? OnContactPressed;

    /// <summary>Raised when the user presses the Mute/Unmute button.</summary>
    public event Action? OnMuteToggled;

    /// <summary>The last config received from the server. Exposed for the post page to read.</summary>
    public STBulletinBoardConfig? LastConfig => _lastState?.Config;

    private readonly BoxContainer _cardContainer;
    private STBulletinUiState? _lastState;
    private bool _showingPrimary = true;

    private const float SearchDebounceSeconds = 0.25f;

    private string _searchQuery = string.Empty;
    private bool _searchDirty;
    private float _searchDebounceAccumulator;

    public STBulletinMainPage()
    {
        RobustXamlLoader.Load(this);

        _cardContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 4,
            Margin = new Thickness(0, 0, 0, 4),
        };
        CardScroll.AddChild(_cardContainer);

        PrimaryTabButton.OnPressed += _ => SwitchTab(true);
        SecondaryTabButton.OnPressed += _ => SwitchTab(false);
        PostButton.OnPressed += _ =>
        {
            var category = _showingPrimary ? STBulletinCategory.Primary : STBulletinCategory.Secondary;
            OnPostPressed?.Invoke(category);
        };

        MuteButton.OnPressed += _ => OnMuteToggled?.Invoke();

        SearchBar.OnTextChanged += _ =>
        {
            _searchDirty = true;
            _searchDebounceAccumulator = SearchDebounceSeconds;
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_searchDirty)
            return;

        _searchDebounceAccumulator -= args.DeltaSeconds;
        if (_searchDebounceAccumulator > 0)
            return;

        _searchDirty = false;
        _searchQuery = SearchBar.Text.Trim();
        RebuildCards();
    }

    /// <summary>
    /// Updates the page with new state from the server.
    /// </summary>
    public void UpdateState(STBulletinUiState state)
    {
        _lastState = state;
        var config = state.Config;

        // One-shot tab switch from server (e.g. offer link navigation)
        if (state.ActiveCategory is { } activeCategory)
            _showingPrimary = activeCategory == STBulletinCategory.Primary;

        HeaderLabel.Text = Loc.GetString(config.HeaderTitle);
        MuteButton.Text = Loc.GetString(state.IsMuted ? "st-bulletin-unmute" : "st-bulletin-mute");
        SearchBar.PlaceHolder = Loc.GetString(config.SearchPlaceholder);

        var primaryCount = state.PrimaryOffers.Count;
        if (primaryCount > 0)
            PrimaryTabButton.Text = Loc.GetString("st-bulletin-tab-count",
                ("name", Loc.GetString(config.PrimaryTabName)), ("count", primaryCount));
        else
            PrimaryTabButton.Text = Loc.GetString(config.PrimaryTabName);

        var secondaryCount = state.SecondaryOffers.Count;
        if (config.ShowSecondaryCountBadge && secondaryCount > 0)
            SecondaryTabButton.Text = Loc.GetString("st-bulletin-tab-count",
                ("name", Loc.GetString(config.SecondaryTabName)), ("count", secondaryCount));
        else
            SecondaryTabButton.Text = Loc.GetString(config.SecondaryTabName);

        RebuildCards();
    }

    /// <summary>
    /// Sets the search bar text and triggers an immediate rebuild (no debounce).
    /// </summary>
    public void SetSearchQuery(string query)
    {
        SearchBar.Text = query;
        _searchQuery = query.Trim();
        _searchDirty = false;
        RebuildCards();
    }

    /// <summary>
    /// Clears the search bar and rebuilds cards.
    /// </summary>
    public void ClearSearch()
    {
        SetSearchQuery(string.Empty);
    }

    /// <summary>
    /// Returns true if the player has reached the post limit for the given category.
    /// </summary>
    public bool IsAtPostLimit(STBulletinCategory category)
    {
        if (_lastState is null)
            return true;

        var count = category == STBulletinCategory.Primary
            ? _lastState.MyPrimaryCount
            : _lastState.MySecondaryCount;

        return count >= _lastState.Config.MaxOffersPerPlayer;
    }

    private void SwitchTab(bool showPrimary)
    {
        _showingPrimary = showPrimary;
        RebuildCards();
    }

    private void RebuildCards()
    {
        _cardContainer.RemoveAllChildren();

        if (_lastState is null)
            return;

        var config = _lastState.Config;
        var offers = _showingPrimary ? _lastState.PrimaryOffers : _lastState.SecondaryOffers;
        var ownerName = _lastState.OwnerCharacterName;

        PrimaryTabButton.Disabled = _showingPrimary;
        SecondaryTabButton.Disabled = !_showingPrimary;

        var hasSearch = !string.IsNullOrEmpty(_searchQuery);

        if (_showingPrimary)
        {
            SetInfoLabel(Loc.GetString(config.PrimaryInfoLabel, ("count", offers.Count)));
            InfoLabel.Visible = true;
        }
        else if (!string.IsNullOrEmpty(config.SecondaryHint) && !config.ShowSecondaryCountBadge)
        {
            // Show hint text for restricted users (e.g. non-mercs on jobs tab)
            SetInfoLabel(Loc.GetString(config.SecondaryHint));
            InfoLabel.Visible = true;
        }
        else
        {
            SetInfoLabel(Loc.GetString(config.SecondaryInfoLabel, ("count", offers.Count)));
            InfoLabel.Visible = true;
        }

        foreach (var offer in offers)
        {
            if (hasSearch && !MatchesSearch(offer))
                continue;

            var isOwn = offer.PosterName == ownerName;
            var card = new STBulletinOfferCard(offer, isOwn, config);

            card.OnWithdraw += offerId => OnWithdrawPressed?.Invoke(offerId);
            card.OnContact += (mid, oid) => OnContactPressed?.Invoke(mid, oid);

            _cardContainer.AddChild(card);
        }

        if (_showingPrimary)
        {
            PostButton.Visible = config.CanPostPrimary;
            PostButton.Text = Loc.GetString(config.PrimaryPostButton);
            PostButton.Disabled = _lastState.MyPrimaryCount >= config.MaxOffersPerPlayer;
        }
        else
        {
            PostButton.Visible = config.CanPostSecondary;
            PostButton.Text = Loc.GetString(config.SecondaryPostButton);
            PostButton.Disabled = _lastState.MySecondaryCount >= config.MaxOffersPerPlayer;
        }
    }

    private void SetInfoLabel(string text)
    {
        var msg = new FormattedMessage();
        msg.AddText(text);
        InfoLabel.SetMessage(msg);
    }

    /// <summary>
    /// Checks whether an offer matches the current search query (case-insensitive).
    /// Matches against offer ID (with # prefix), description, and poster name.
    /// </summary>
    private bool MatchesSearch(STBulletinOffer offer)
    {
        var q = _searchQuery;

        if (q.Length > 0 && q[0] == '#'
            && uint.TryParse(q.AsSpan(1), out var searchId)
            && offer.Id == searchId)
        {
            return true;
        }

        return offer.Description.Contains(q, StringComparison.OrdinalIgnoreCase)
               || offer.PosterName.Contains(q, StringComparison.OrdinalIgnoreCase);
    }
}
