using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared._Stalker_EN.BulletinBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.BulletinBoard;

/// <summary>
/// A single offer card on a bulletin board.
/// Displays poster info, description, and action button.
/// Updates elapsed time live via FrameUpdate. Colors come from the board config.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STBulletinOfferCard : PanelContainer
{
    [Dependency] private readonly IClipboardManager _clipboard = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    /// <summary>Raised when the owner presses Withdraw on their own card.</summary>
    public event Action<uint>? OnWithdraw;

    /// <summary>Raised when a player presses Contact on another player's card. Args: (posterMessengerId, offerId).</summary>
    public event Action<string, uint>? OnContact;

    private static readonly Color CardBackgroundColor = Color.FromHex("#2A2A2E");

    private readonly TimeSpan _offerTimestamp;
    private float _timeUpdateAccumulator;

    public STBulletinOfferCard(STBulletinOffer offer, bool isOwn, STBulletinBoardConfig config)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _offerTimestamp = offer.Timestamp;

        Color borderColor;
        if (offer.Category == STBulletinCategory.Primary)
            borderColor = isOwn ? config.PrimaryOwnBorderColor : config.PrimaryBorderColor;
        else
            borderColor = isOwn ? config.SecondaryOwnBorderColor : config.SecondaryBorderColor;

        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = CardBackgroundColor,
            BorderColor = borderColor,
            BorderThickness = new Thickness(2),
        };

        if (offer.PosterFaction is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(offer.PosterFaction, out var patch))
        {
            var spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();
            var specifier = new SpriteSpecifier.Rsi(patch.Rsi, patch.State);
            FactionIcon.Texture = spriteSystem.Frame0(specifier);
            FactionIcon.Visible = true;
        }

        if (isOwn)
            PosterNameLabel.Text = Loc.GetString("st-bulletin-poster-you", ("name", offer.PosterName));
        else
            PosterNameLabel.Text = offer.PosterName;

        OfferIdLabel.Text = $"#{offer.Id}";

        // AddText escapes markup to prevent injection
        var descMsg = new FormattedMessage();
        descMsg.AddText(offer.Description);
        DescriptionLabel.SetMessage(descMsg);

        if (isOwn)
        {
            ActionButton.Text = Loc.GetString("st-bulletin-withdraw");
            ActionButton.OnPressed += _ => OnWithdraw?.Invoke(offer.Id);
        }
        else
        {
            ActionButton.Text = Loc.GetString("st-bulletin-contact");
            ActionButton.Disabled = offer.PosterMessengerId is null;
            ActionButton.OnPressed += _ =>
            {
                if (offer.PosterMessengerId is not null)
                    OnContact?.Invoke(offer.PosterMessengerId, offer.Id);
            };
        }

        CopyButton.Text = Loc.GetString("st-bulletin-copy-ref");
        CopyButton.OnPressed += _ =>
        {
            _clipboard.SetText(STBulletinOffer.FormatRef(offer.OfferRefPrefix, offer.Id));
        };

        UpdateTimeLabel();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _timeUpdateAccumulator += args.DeltaSeconds;
        if (_timeUpdateAccumulator < 1f)
            return;
        _timeUpdateAccumulator -= 1f;
        UpdateTimeLabel();
    }

    private void UpdateTimeLabel()
    {
        var elapsed = _timing.CurTime - _offerTimestamp;
        if (elapsed < TimeSpan.Zero)
            elapsed = TimeSpan.Zero;

        TimeLabel.Text = $"{(int) elapsed.TotalHours:D2}:{elapsed.Minutes:D2}:{elapsed.Seconds:D2}";
    }
}
