using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.PDA;

/// <summary>
/// Window for the PDA password lock system.
/// Shows a password entry form for non-owners, or password settings for the PDA owner.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STPdaPasswordWindow : FancyWindow
{
    public event Action<string>? OnPasswordSubmit;
    public event Action<string?>? OnPasswordSet;

    public STPdaPasswordWindow()
    {
        RobustXamlLoader.Load(this);

        PasswordInput.IsValid = s => s.Length <= 16;
        NewPasswordInput.IsValid = s => s.Length <= 16;

        SubmitButton.OnPressed += _ =>
        {
            var password = PasswordInput.Text.Trim();
            if (!string.IsNullOrEmpty(password))
            {
                OnPasswordSubmit?.Invoke(password);
                PasswordInput.Text = string.Empty;
            }
        };

        SetPasswordButton.OnPressed += _ =>
        {
            var password = NewPasswordInput.Text.Trim();
            if (!string.IsNullOrEmpty(password))
            {
                OnPasswordSet?.Invoke(password);
                NewPasswordInput.Text = string.Empty;
            }
        };

        RemovePasswordButton.OnPressed += _ =>
        {
            OnPasswordSet?.Invoke(null);
        };
    }

    public void UpdateState(STPdaPasswordUiState state)
    {
        if (state.IsOwner)
        {
            PasswordEntryPanel.Visible = false;
            OwnerSettingsPanel.Visible = true;

            CurrentStatusLabel.Text = state.HasPassword
                ? Loc.GetString("st-pda-password-status-locked")
                : Loc.GetString("st-pda-password-status-unlocked");

            RemovePasswordButton.Disabled = !state.HasPassword;
        }
        else
        {
            PasswordEntryPanel.Visible = true;
            OwnerSettingsPanel.Visible = false;

            ErrorLabel.Visible = state.WrongPassword;
            ErrorLabel.Text = Loc.GetString("st-pda-password-wrong");
        }
    }
}
