- type: soundCollection
  id: AudioProjectSounds
  files:
  - /Audio/_Stalker/SoundTriggers/audioproject/allpointsdowntarget.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/Ascensionaza.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/Ascensionnotdeciphed.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/Ascensionproceedtotarget.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/Ascensiontarget.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/broadcaststation.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/cuban.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/directiveprogramming1.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/directiveprogramming2.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/gulfofmexico.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/kennedy.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed2.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed3.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed4.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed5.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed6.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed7.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed8.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphed9.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/notdeciphered.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/novamutation.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/oswald.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/pentagonone.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/pentagontwo.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/preparedowntarget.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/proceedtotarget.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/projectnova.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/rusalka.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/rusalkamexico.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/schoolbook.ogg
  - /Audio/_Stalker/SoundTriggers/audioproject/threesycorax.ogg
