using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker.Bands;
using Content.Client._Stalker_EN.FactionRelations; // stalker-en-changes
using Content.Shared._Stalker_EN.FactionRelations; // stalker-en-changes
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Shared.Timing;

namespace Content.Client._Stalker.Bands.UI;

[GenerateTypedNameReferences]
public sealed partial class BandsManagingWindow : FancyWindow
{
    public event Action<string>? OnAddMemberButtonPressed;
    public event Action<Guid>? OnRemoveMemberButtonPressed;
    public event Action<string>? OnBuyItemButtonPressed;
    // stalker-en-changes start
    public event Action<string, int, string?, bool>? OnProposeRelationPressed;
    public event Action<string, bool>? OnRespondProposalPressed;
    public event Action<string>? OnCancelProposalPressed;
    // stalker-en-changes end

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    // stalker-en-changes start
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    private SpriteSystem? _spriteSystem;

    private const int RelationsTabIndex = 3;
    private const int MaxCustomMessageLength = 250;

    /// <summary>
    /// Custom message line edit, stored between state updates so the user's input persists.
    /// </summary>
    private LineEdit? _customMessageLineEdit;

    /// <summary>
    /// Tracks the user's uncommitted dropdown selections per faction.
    /// Persists across UI state rebuilds so the user doesn't lose their choice.
    /// </summary>
    private readonly Dictionary<string, STFactionRelationType> _pendingSelections = new();

    /// <summary>
    /// Cooldown tracking for live countdown display.
    /// </summary>
    private readonly Dictionary<string, TimeSpan> _cooldownExpiries = new();
    private readonly Dictionary<string, Label> _cooldownLabels = new();
    private readonly Dictionary<string, OptionButton> _cooldownDropdowns = new();
    private bool _lastCanManage;
    // stalker-en-changes end

    public BandsManagingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("bands-managing-window-members-tab-title"));
        Tabs.SetTabTitle(1, Loc.GetString("bands-managing-window-warzone-tab-title"));
        Tabs.SetTabTitle(2, Loc.GetString("bands-managing-window-shop-tab-title"));
        Tabs.SetTabTitle(3, Loc.GetString("bands-managing-window-relations-tab-title")); // stalker-en-changes

        AddMemberButton.OnPressed += OnAddMemberPressed;
    }

    private void OnAddMemberPressed(BaseButton.ButtonEventArgs args)
    {
        OnAddMemberButtonPressed?.Invoke(AddMemberLineEdit.Text);
        AddMemberLineEdit.Text = string.Empty;
    }

    public void UpdateState(BandsManagingBoundUserInterfaceState state)
    {
        BandNameLabel.Text = state.BandName ?? Loc.GetString("bands-managing-window-band-name-unknown");
        BandMemberCountLabel.Text = $"{state.Members.Count} / {state.MaxMembers}";

        // --- Clear Lists ---
        MembersList.Children.Clear();
        WarZoneList.Children.Clear();
        BandPointsList.Children.Clear();
        ShopItemList.Children.Clear(); // Clear shop items list

        // --- Update Members Tab ---
        var canManage = state.CanManage;
        if (state.Members.Count == 0)
        {
            MembersList.Children.Add(NoMembersLabel);
            NoMembersLabel.Visible = true;
        }
        else
        {
            NoMembersLabel.Visible = false;
            foreach (var member in state.Members)
            {
                var memberBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2)
                };

                var nameLabel = new Label
                {
                    Text = member.CharacterName, // Display CharacterName instead of PlayerName (ckey)
                    HorizontalExpand = true,
                };

                var removeButton = new Button
                {
                    Text = Loc.GetString("bands-managing-window-remove-button"),
                    MinWidth = 80,
                    HorizontalAlignment = HAlignment.Right,
                    Disabled = !canManage
                };

                var memberId = member.UserId;
                removeButton.OnPressed += _ => OnRemoveMemberButtonPressed?.Invoke(memberId);

                memberBox.AddChild(nameLabel);
                memberBox.AddChild(removeButton);

                MembersList.AddChild(memberBox);
            }
        }
        AddMemberLineEdit.Editable = canManage;
        AddMemberButton.Disabled = !canManage;

        // --- Update War Zone Tab ---

        // Populate War Zones List
        if (state.WarZones.Count == 0)
        {
            WarZoneList.Children.Add(NoWarZonesLabel);
            NoWarZonesLabel.Visible = true;
        }
        else
        {
            NoWarZonesLabel.Visible = false;
            foreach (var wz in state.WarZones)
            {
                var wzBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 4)
                };

                wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-zone", ("zoneId", wz.ZoneId)) });
                wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-owner", ("owner", wz.Owner)), StyleClasses = { "LabelSecondaryColor" } });
                wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-cooldown", ("seconds", $"{wz.Cooldown:F0}")), StyleClasses = { "LabelSecondaryColor" } });
                wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-attacker", ("attacker", wz.Attacker)), StyleClasses = { "LabelSecondaryColor" } });
                wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-defender", ("defender", wz.Defender)), StyleClasses = { "LabelSecondaryColor" } });
                // wzBox.AddChild(new Label { Text = Loc.GetString("bands-managing-window-warzone-progress", ("progress", $"{wz.Progress * 100:F1}")), StyleClasses = { "LabelSecondaryColor" } });

                WarZoneList.AddChild(wzBox);
                // Add a separator for readability, except after the last item
                if (state.WarZones.IndexOf(wz) < state.WarZones.Count - 1)
                {
                    WarZoneList.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
                }
            }
        }

        // Populate Band Points List
        if (state.BandPoints.Count == 0)
        {
            BandPointsList.Children.Add(NoBandPointsLabel);
            NoBandPointsLabel.Visible = true;
        }
        else
        {
            NoBandPointsLabel.Visible = false;
            foreach (var bp in state.BandPoints)
            {
                var bpBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2)
                };

                var nameLabel = new Label
                {
                    Text = Loc.GetString("bands-managing-window-band-points-entry", ("bandName", bp.BandName), ("points", bp.Points)),
                    HorizontalExpand = true,
                };

                bpBox.AddChild(nameLabel);
                BandPointsList.AddChild(bpBox);
            }
        }

        // --- Update Shop Tab ---
        if (state.ShopItems.Count == 0)
        {
            ShopItemList.Children.Add(NoShopItemsLabel);
            NoShopItemsLabel.Visible = true;
        }
        else
        {
            NoShopItemsLabel.Visible = false;
            foreach (var item in state.ShopItems)
            {
                // Try to get the entity prototype for the name and icon
                string itemName = item.ProductEntity; // Default to ID
                Texture? itemTexture = null;
                if (_prototypeManager.TryIndex<EntityPrototype>(item.ProductEntity, out var itemProto))
                {
                    itemName = itemProto.Name; // Use prototype name if available
                    itemTexture = _entityManager.System<SpriteSystem>().GetPrototypeIcon(itemProto).Default;
                }


                var itemBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 4),
                    SeparationOverride = 5
                };

                // Icon
                if (itemTexture != null)
                {
                    itemBox.AddChild(new TextureRect
                    {
                        Texture = itemTexture,
                        MinSize = new System.Numerics.Vector2(32, 32), // Corrected to use Vector2 constructor
                        Stretch = TextureRect.StretchMode.KeepAspectCentered
                    });
                }

                // Name and Price Label
                var namePriceLabel = new Label
                {
                    Text = Loc.GetString("bands-managing-window-shop-item-entry", ("itemName", itemName), ("price", item.Price)),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                // Buy Button
                var buyButton = new Button
                {
                    Text = Loc.GetString("bands-managing-window-buy-button"), // Use "Buy" for the band shop
                    MinWidth = 80,
                    HorizontalAlignment = HAlignment.Right,
                    Disabled = !state.CanManage // Only allow managing members to buy for the band
                };

                var itemId = item.ProductEntity; // Capture item ID for the button action
                buyButton.OnPressed += _ => OnBuyItemButtonPressed?.Invoke(itemId);

                itemBox.AddChild(namePriceLabel);
                itemBox.AddChild(buyButton);

                ShopItemList.AddChild(itemBox);
            }
        }

        // stalker-en-changes start - Update Relations Tab
        UpdateRelationsTab(state);
    }

    private void UpdateRelationsTab(BandsManagingBoundUserInterfaceState state)
    {
        // Hide entire Relations tab for restricted faction players
        if (state.HideRelationsTab)
        {
            RelationsTab.Visible = false;
            if (Tabs.CurrentTab == RelationsTabIndex)
                Tabs.CurrentTab = 0;
            return;
        }

        RelationsTab.Visible = true;
        RelationsList.Children.Clear();

        // Clear cooldown tracking for rebuild
        _cooldownExpiries.Clear();
        _cooldownLabels.Clear();
        _cooldownDropdowns.Clear();
        _lastCanManage = state.CanManage;

        if (string.IsNullOrEmpty(state.PlayerFaction) || state.AllFactions.Count == 0)
        {
            RelationsList.AddChild(NoRelationsLabel);
            NoRelationsLabel.Visible = true;
            return;
        }

        NoRelationsLabel.Visible = false;

        _spriteSystem ??= _entityManager.System<SpriteSystem>();

        // Build relation lookup
        var relationLookup = new Dictionary<(string, string), STFactionRelationType>();
        foreach (var entry in state.FactionRelations)
        {
            relationLookup[(entry.FactionA, entry.FactionB)] = entry.Relation;
        }

        // --- Custom message input ---
        var msgContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
            SeparationOverride = 6,
        };
        msgContainer.AddChild(new Label
        {
            Text = Loc.GetString("bands-managing-window-custom-message-label"),
            VerticalAlignment = VAlignment.Center,
        });

        // Preserve the user's typed text between UI state refreshes
        var savedText = _customMessageLineEdit?.Text ?? "";
        _customMessageLineEdit = new LineEdit
        {
            PlaceHolder = Loc.GetString("bands-managing-window-custom-message-placeholder"),
            HorizontalExpand = true,
            Text = savedText,
            IsValid = s => s.Length <= MaxCustomMessageLength,
        };
        msgContainer.AddChild(_customMessageLineEdit);
        RelationsList.AddChild(msgContainer);

        // --- Incoming proposals ---
        if (state.IncomingProposals.Count > 0)
        {
            RelationsList.AddChild(new Label
            {
                Text = Loc.GetString("bands-managing-window-incoming-proposals-header"),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 4, 0, 2),
            });

            foreach (var proposal in state.IncomingProposals)
            {
                var proposalRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2),
                    SeparationOverride = 6,
                };

                AddFactionIcon(proposalRow, proposal.InitiatingFaction);

                var relationName = GetRelationDisplayName(proposal.ProposedRelation);
                var labelText = Loc.GetString("bands-managing-window-incoming-proposal",
                    ("faction", STFactionRelationHelpers.GetDisplayName(proposal.InitiatingFaction, state.FactionDisplayNames)),
                    ("relation", relationName));

                proposalRow.AddChild(new Label
                {
                    Text = labelText,
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                });

                var initiating = proposal.InitiatingFaction;

                var acceptBtn = new Button
                {
                    Text = Loc.GetString("bands-managing-window-accept-button"),
                    MinWidth = 60,
                    VerticalAlignment = VAlignment.Center,
                };
                acceptBtn.OnPressed += _ => OnRespondProposalPressed?.Invoke(initiating, true);
                proposalRow.AddChild(acceptBtn);

                var rejectBtn = new Button
                {
                    Text = Loc.GetString("bands-managing-window-reject-button"),
                    MinWidth = 60,
                    VerticalAlignment = VAlignment.Center,
                };
                rejectBtn.OnPressed += _ => OnRespondProposalPressed?.Invoke(initiating, false);
                proposalRow.AddChild(rejectBtn);

                RelationsList.AddChild(proposalRow);

                // Show custom message if present
                if (!string.IsNullOrWhiteSpace(proposal.CustomMessage))
                {
                    RelationsList.AddChild(new Label
                    {
                        Text = $"  \"{proposal.CustomMessage}\"",
                        StyleClasses = { "LabelSecondaryColor" },
                        Margin = new Thickness(32, 0, 0, 2),
                    });
                }
            }
        }

        // --- Outgoing proposals ---
        if (state.OutgoingProposals.Count > 0)
        {
            RelationsList.AddChild(new Label
            {
                Text = Loc.GetString("bands-managing-window-outgoing-proposals-header"),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 4, 0, 2),
            });

            foreach (var proposal in state.OutgoingProposals)
            {
                var proposalRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(0, 2),
                    SeparationOverride = 6,
                };

                AddFactionIcon(proposalRow, proposal.TargetFaction);

                var relationName = GetRelationDisplayName(proposal.ProposedRelation);
                var labelText = Loc.GetString("bands-managing-window-outgoing-proposal",
                    ("faction", STFactionRelationHelpers.GetDisplayName(proposal.TargetFaction, state.FactionDisplayNames)),
                    ("relation", relationName));

                proposalRow.AddChild(new Label
                {
                    Text = labelText,
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                });

                var target = proposal.TargetFaction;
                var cancelBtn = new Button
                {
                    Text = Loc.GetString("bands-managing-window-cancel-button"),
                    MinWidth = 60,
                    VerticalAlignment = VAlignment.Center,
                };
                cancelBtn.OnPressed += _ => OnCancelProposalPressed?.Invoke(target);
                proposalRow.AddChild(cancelBtn);

                RelationsList.AddChild(proposalRow);
            }
        }

        // --- Relations grid header ---
        RelationsList.AddChild(new Label
        {
            Text = Loc.GetString("bands-managing-window-relations-header"),
            StyleClasses = { "LabelHeading" },
            Margin = new Thickness(0, 4, 0, 2),
        });

        // --- Faction relation rows ---
        foreach (var faction in state.AllFactions)
        {
            if (faction == state.PlayerFaction)
                continue;

            // Vertical container: main row + detail row
            var factionContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            // --- Main row ---
            var mainRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
                SeparationOverride = 6,
            };

            AddFactionIcon(mainRow, faction);

            mainRow.AddChild(new Label
            {
                Text = STFactionRelationHelpers.GetDisplayName(faction, state.FactionDisplayNames),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            var key = STFactionRelationHelpers.NormalizePair(state.PlayerFaction, faction);
            var currentRelation = relationLookup.GetValueOrDefault(key, STFactionRelationType.Neutral);
            var isOnCooldown = state.CooldownsRemaining.TryGetValue(faction, out var cooldownSecs) && cooldownSecs > 0;

            var dropdown = new OptionButton
            {
                MinWidth = 100,
                VerticalAlignment = VAlignment.Center,
            };

            dropdown.AddItem(Loc.GetString("bands-managing-window-relation-alliance"), (int) STFactionRelationType.Alliance);
            dropdown.AddItem(Loc.GetString("bands-managing-window-relation-neutral"), (int) STFactionRelationType.Neutral);
            dropdown.AddItem(Loc.GetString("bands-managing-window-relation-hostile"), (int) STFactionRelationType.Hostile);
            dropdown.AddItem(Loc.GetString("bands-managing-window-relation-war"), (int) STFactionRelationType.War);
            dropdown.SelectId((int) currentRelation);
            dropdown.Disabled = !state.CanManage || isOnCooldown;

            // --- Detail row (hidden by default) ---
            var detailRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(32, 0, 0, 2),
                SeparationOverride = 6,
                Visible = false,
            };

            var typeLabel = new Label
            {
                StyleClasses = { "LabelSecondaryColor" },
                VerticalAlignment = VAlignment.Center,
            };
            detailRow.AddChild(typeLabel);

            // Broadcast toggle checkbox (only relevant for bilateral proposals)
            var broadcastCheckBox = new CheckBox
            {
                Text = Loc.GetString("bands-managing-window-relation-broadcast"),
                Pressed = true,
                VerticalAlignment = VAlignment.Center,
                Visible = false,
            };
            detailRow.AddChild(broadcastCheckBox);

            // --- Confirm button (hidden by default) ---
            var confirmButton = new ConfirmButton
            {
                MinWidth = 80,
                VerticalAlignment = VAlignment.Center,
                Visible = false,
            };

            var targetFaction = faction;

            confirmButton.OnPressed += _ =>
            {
                if (!_pendingSelections.TryGetValue(targetFaction, out var selected))
                    return;

                var msg = string.IsNullOrWhiteSpace(_customMessageLineEdit?.Text)
                    ? null
                    : _customMessageLineEdit.Text;

                var broadcast = broadcastCheckBox.Pressed;
                OnProposeRelationPressed?.Invoke(targetFaction, (int) selected, msg, broadcast);
                _pendingSelections.Remove(targetFaction);
            };

            dropdown.OnItemSelected += args =>
            {
                dropdown.SelectId(args.Id);
                var selectedRelation = (STFactionRelationType) args.Id;

                if (selectedRelation == currentRelation)
                {
                    _pendingSelections.Remove(targetFaction);
                    detailRow.Visible = false;
                    confirmButton.Visible = false;
                }
                else
                {
                    _pendingSelections[targetFaction] = selectedRelation;
                    UpdateDetailRow(typeLabel, broadcastCheckBox, confirmButton,
                        currentRelation, selectedRelation);
                    detailRow.Visible = true;
                }
            };

            mainRow.AddChild(dropdown);
            mainRow.AddChild(confirmButton);

            // --- Live cooldown label ---
            if (isOnCooldown)
            {
                var cooldownLabel = new Label
                {
                    Text = Loc.GetString("bands-managing-window-cooldown", ("seconds", (int) cooldownSecs)),
                    StyleClasses = { "LabelSecondaryColor" },
                    VerticalAlignment = VAlignment.Center,
                };
                mainRow.AddChild(cooldownLabel);

                // Track for live countdown updates in FrameUpdate
                var expiryTime = _gameTiming.CurTime + TimeSpan.FromSeconds(cooldownSecs);
                _cooldownExpiries[targetFaction] = expiryTime;
                _cooldownLabels[targetFaction] = cooldownLabel;
                _cooldownDropdowns[targetFaction] = dropdown;
            }

            factionContainer.AddChild(mainRow);
            factionContainer.AddChild(detailRow);

            // Restore pending selection if the user had one before the UI rebuilt
            if (_pendingSelections.TryGetValue(faction, out var pendingSelection) && pendingSelection != currentRelation)
            {
                dropdown.SelectId((int) pendingSelection);
                UpdateDetailRow(typeLabel, broadcastCheckBox, confirmButton,
                    currentRelation, pendingSelection);
                detailRow.Visible = true;
            }
            else
            {
                _pendingSelections.Remove(faction);
            }

            RelationsList.AddChild(factionContainer);
        }
    }

    private void UpdateDetailRow(
        Label typeLabel,
        CheckBox broadcastCheckBox,
        ConfirmButton confirmButton,
        STFactionRelationType current,
        STFactionRelationType selected)
    {
        var requiresConfirmation = STFactionRelationHelpers.RequiresConfirmation(current, selected);
        var isEscalation = STFactionRelationHelpers.IsEscalation(current, selected);

        // Change type indicator
        typeLabel.Text = requiresConfirmation
            ? Loc.GetString("bands-managing-window-relation-requires-approval")
            : Loc.GetString("bands-managing-window-relation-instant");

        typeLabel.FontColorOverride = GetRelationColor(selected);

        // Show broadcast toggle only for bilateral proposals
        broadcastCheckBox.Visible = requiresConfirmation;

        confirmButton.Text = isEscalation
            ? Loc.GetString("bands-managing-window-relation-declare-button")
            : Loc.GetString("bands-managing-window-relation-propose-button");

        confirmButton.ConfirmationText = Loc.GetString("bands-managing-window-relation-confirm-free");
        confirmButton.Visible = true;
    }

    private static Color? GetRelationColor(STFactionRelationType type)
    {
        return STFactionRelationColors.GetColor(type);
    }

    private void AddFactionIcon(BoxContainer row, string faction)
    {
        if (STFactionPatchIcons.PatchStates.TryGetValue(faction, out var patch))
        {
            _spriteSystem ??= _entityManager.System<SpriteSystem>();
            var specifier = new SpriteSpecifier.Rsi(patch.Rsi, patch.State);
            row.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(specifier),
                TextureScale = new Vector2(1.5f, 1.5f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(32, 32),
                VerticalAlignment = VAlignment.Center,
            });
        }
    }

    private static string GetRelationDisplayName(STFactionRelationType type)
    {
        return type switch
        {
            STFactionRelationType.Alliance => Loc.GetString("bands-managing-window-relation-alliance"),
            STFactionRelationType.Neutral => Loc.GetString("bands-managing-window-relation-neutral"),
            STFactionRelationType.Hostile => Loc.GetString("bands-managing-window-relation-hostile"),
            STFactionRelationType.War => Loc.GetString("bands-managing-window-relation-war"),
            _ => Loc.GetString("bands-managing-window-relation-neutral"),
        };
    }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        List<string>? expired = null;
        foreach (var (faction, expiry) in _cooldownExpiries)
        {
            var remaining = (expiry - _gameTiming.CurTime).TotalSeconds;
            if (remaining <= 0)
            {
                expired ??= new();
                expired.Add(faction);

                if (_cooldownLabels.TryGetValue(faction, out var label))
                    label.Visible = false;

                if (_lastCanManage && _cooldownDropdowns.TryGetValue(faction, out var dd))
                    dd.Disabled = false;
            }
            else if (_cooldownLabels.TryGetValue(faction, out var label))
            {
                label.Text = Loc.GetString("bands-managing-window-cooldown", ("seconds", (int) remaining));
            }
        }

        if (expired != null)
        {
            foreach (var f in expired)
            {
                _cooldownExpiries.Remove(f);
                _cooldownLabels.Remove(f);
                _cooldownDropdowns.Remove(f);
            }
        }
    }
    // stalker-en-changes end

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            AddMemberButton.OnPressed -= OnAddMemberPressed;
        }
    }
}
