- type: job
  id: StalkerMonolith
  name: job-monolith
  icon: monolith
  description: job-monolith-desc
  playTimeTracker: JobMonolith
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMonolith
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: MonolithGear
  supervisors: job-monolith-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Monolith
      - type: Bands
        band: Stalker
        bandIcon: monolith
        bandProto: STMonolithBand
        bandRankId: 2
      - type: NpcFactionMember
        factions:
          - Mutated
      - type: Hunger
        baseDecayRate: 0
      - type: Thirst
        baseDecayRate: 0
      - type: PersonalDamageBlock
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: StalkerMonolithFree
  name: job-monolith-free
  icon: monolithfree
  description: job-monolith-free-desc
  playTimeTracker: JobMonolithFree
  whitelisted: false
  requirements:
   - !type:DepartmentTimeRequirement
     department: Stalker
     time: 15h
   - !type:DepartmentTimeRequirement
     department: StalkerAdvanced
     time: 1h
     inverted: true
   - !type:DepartmentTimeRequirement
     department: StalkerBrigands
     time: 1h
     inverted: true
   - !type:DepartmentTimeRequirement
     department: StalkerOfficials
     time: 1h
     inverted: true
   - !type:DepartmentTimeRequirement
     department: StalkerReligius
     time: 1h
     inverted: true
   - !type:SpeciesRequirement
     species:
     - Human
  startingGear: MonolithGearFre
  supervisors: job-monolith-free-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Monolith
          - MonolithFree
      - type: Bands
        band: Stalker
        bandIcon: monolithfree
        bandProto: STMonolithBand
        bandRankId: 2
      - type: NpcFactionMember
        factions:
          - Mutated
      - type: Hunger
        baseDecayRate: 0
      - type: Thirst
        baseDecayRate: 0
      - type: PersonalDamageBlock
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: STAnomalyTipsViewing

- type: startingGear
  id: MonolithGear
  equipment:
    id: MonolithPDA
    ears: STClothingChip
    torso: ClothingTorsoTurtlenecksMonolithCamouflage
    legs: ClothingLegsJeansMonolithCamouflage
    shoes: STClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: MonolithGearFre
  equipment:
    id: MonolithPDA
    ears: STClothingChip
    torso: ClothingTorsoTurtlenecksMonolithCamouflage
    legs: ClothingLegsJeansMonolithCamouflage
    shoes: STClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesFingerless

- type: stBand
  id: STMonolithBand
  name: Monolith
  factionId: Monolith
  maxMembers: 11
  managingRankId: 1
  hierarchy:
    1: StalkerMonolith

