using System.Numerics;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Message;
using Content.Client._Stalker_EN.FactionRelations;
using Content.Client._Stalker_EN.UI.Controls;
using Content.Shared._Stalker_EN.News;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.News;

[GenerateTypedNameReferences]
public sealed partial class STNewsUiFragment : BoxContainer, INewsLinkClickHandler
{
    /// <summary>Fired when the journalist publishes an article.</summary>
    public event Action<string, string, int>? OnPublishArticle;

    /// <summary>Fired when the user requests full article content.</summary>
    public event Action<int>? OnRequestArticle;

    /// <summary>Fired when the journalist deletes their own article.</summary>
    public event Action<int>? OnDeleteArticle;

    /// <summary>Fired when the user posts a comment (articleId, content).</summary>
    public event Action<int, string>? OnPostComment;

    /// <summary>Fired when the user navigates back from article detail to list view.</summary>
    public event Action? OnCloseArticle;

    /// <summary>Fired when the user toggles a reaction (articleId, reactionId).</summary>
    public event Action<int, string>? OnToggleReaction;

    private readonly IClipboardManager _clipboard = IoCManager.Resolve<IClipboardManager>();
    private readonly SpriteSystem _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

    private static readonly Color CardBackground = Color.FromHex("#1a1a2e");
    private static readonly Color CardBorder = Color.FromHex("#333355");
    private static readonly Color MetaColor = Color.FromHex("#888888");
    private static readonly Color PreviewColor = Color.FromHex("#AAAAAA");
    private static readonly Color NewIndicatorColor = Color.FromHex("#00CC00");
    private static readonly Color ReactionActiveColor = Color.FromHex("#334466");
    private static readonly Color ReactionInactiveColor = Color.Transparent;
    private static readonly Color ReactionHoverColor = Color.FromHex("#2a2a4a");

    private const float CardColorBlendFactor = 0.18f;
    private const float CardBorderBlendFactor = 0.30f;

    private static readonly Vector2 FactionIconSize = new(20, 20);
    private static readonly Vector2 ColorSwatchSize = new(24, 24);
    private static readonly Vector2 ReactionIconSize = new(20, 20);
    private static readonly Vector2 PickerIconSize = new(20, 20);
    private static readonly Color PickerBackdropColor = Color.FromHex("#1a1a2eEE");

    private const int PickerColumnsPerRow = 7;

    private static readonly (string LocKey, int Color)[] ColorPresets =
    {
        ("st-news-color-military-green", 0x5B7A3A),
        ("st-news-color-rust",           0xB85C38),
        ("st-news-color-amber",          0xC99A2E),
        ("st-news-color-slate",          0x6B7B8D),
        ("st-news-color-dried-blood",    0x8B3A3A),
        ("st-news-color-anomaly-teal",   0x3A8B7A),
        ("st-news-color-psy-purple",     0x6B4A8B),
        ("st-news-color-ash",            0x9B9B8B),
    };

    private int _selectedColor = ColorPresets[0].Color;

    /// <summary>ID of the article currently shown in the detail view, for the copy-link button.</summary>
    private int? _detailArticleId;

    /// <summary>Latest article summaries from server, cached for client-side filtering.</summary>
    private List<STNewsArticleSummary> _lastArticles = new();

    /// <summary>Latest new article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastNewIds = new();

    /// <summary>Latest deletable article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastDeletableIds = new();

    /// <summary>Latest new-comment article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastNewCommentIds = new();

    /// <summary>Latest article reactions from server, cached for re-render.</summary>
    private Dictionary<int, List<STReactionSummary>> _lastArticleReactions = new();

    private readonly List<PanelContainer> _colorPanels = new();

    private static string FormatNewsLink(int id) => $"[NEWS#{id}]";

    public STNewsUiFragment()
    {
        RobustXamlLoader.Load(this);

        HeaderLabel.Text = Loc.GetString("st-news-header");
        WriteButton.Text = Loc.GetString("st-news-write-button");
        NoArticlesLabel.Text = Loc.GetString("st-news-no-articles");
        BackButton.Text = Loc.GetString("st-news-back-button");
        WriterHeaderLabel.Text = Loc.GetString("st-news-writer-header");
        TitleLabel.Text = Loc.GetString("st-news-title-label");
        TitleEdit.PlaceHolder = Loc.GetString("st-news-title-placeholder");
        ContentLabel.Text = Loc.GetString("st-news-content-label");
        ContentEdit.Placeholder = new Rope.Leaf(Loc.GetString("st-news-content-placeholder"));
        EmbedColorLabel.Text = Loc.GetString("st-news-embed-color-label");
        CancelButton.Text = Loc.GetString("st-news-cancel-button");
        PreviewButton.Text = Loc.GetString("st-news-preview-button");
        PublishButton.Text = Loc.GetString("st-news-publish-button");
        PreviewHeaderLabel.Text = Loc.GetString("st-news-preview-header");
        PreviewCancelButton.Text = Loc.GetString("st-news-cancel-button");
        EditButton.Text = Loc.GetString("st-news-edit-button");
        PreviewPublishButton.Text = Loc.GetString("st-news-publish-button");

        DeleteArticleButton.Text = Loc.GetString("st-news-delete-button");
        PostCommentButton.Text = Loc.GetString("st-news-comment-post");
        CommentEdit.Placeholder = new Rope.Leaf(Loc.GetString("st-news-comment-placeholder"));

        WriteButton.OnPressed += _ => ShowWriter();
        BackButton.OnPressed += _ =>
        {
            OnCloseArticle?.Invoke();
            ShowArticleList();
            RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
        };
        DeleteArticleButton.OnPressed += _ =>
        {
            if (_detailArticleId is { } id)
            {
                OnDeleteArticle?.Invoke(id);
                ShowArticleList();
                RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
            }
        };
        PostCommentButton.OnPressed += _ =>
        {
            if (_detailArticleId is not { } id)
                return;

            var content = Rope.Collapse(CommentEdit.TextRope).Trim();
            if (string.IsNullOrEmpty(content))
                return;

            OnPostComment?.Invoke(id, content);
            CommentEdit.TextRope = Rope.Leaf.Empty;
            UpdateCommentCounter();
        };
        CancelButton.OnPressed += _ => ShowArticleList();
        PreviewButton.OnPressed += _ => ShowPreview();
        PublishButton.OnPressed += _ => DoPublish();
        PreviewCancelButton.OnPressed += _ => ShowWriter();
        EditButton.OnPressed += _ => ShowWriter();
        PreviewPublishButton.OnPressed += _ => DoPublish();

        TitleEdit.OnTextChanged += _ => UpdateTitleCounter();
        ContentEdit.OnTextChanged += _ => UpdateContentCounter();
        CommentEdit.OnTextChanged += _ => UpdateCommentCounter();

        BuildColorPicker();
        UpdateTitleCounter();
        UpdateContentCounter();
        UpdateCommentCounter();

        SearchBar.OnSearchTextChanged += _ => RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
    }

    /// <summary>Updates the fragment from the server-provided news UI state.</summary>
    public void UpdateState(STNewsUiState state)
    {
        WriteButton.Visible = state.CanWrite;

        if (state.OpenArticle != null)
        {
            // If already viewing this article, just refresh comments and reactions (preserves scroll/input)
            if (ArticleDetailView.Visible && _detailArticleId == state.OpenArticle.Id)
            {
                DeleteArticleButton.Visible = state.CanDeleteOpenArticle;
                RebuildCommentList(state.OpenArticleComments);
                RebuildDetailReactionBar(state.OpenArticle.Id, state.ArticleReactions);
            }
            else
            {
                ShowArticleDetail(state);
            }

            // Still update the cached article list for when user goes back
            _lastArticles = state.Articles;
            _lastNewIds = state.NewArticleIds;
            _lastDeletableIds = state.DeletableArticleIds;
            _lastNewCommentIds = state.NewCommentArticleIds;
            _lastArticleReactions = state.ArticleReactions;
            return;
        }

        if (state.OpenArticleId != null && state.OpenArticle == null)
            ShowArticleList();

        _lastArticles = state.Articles;
        _lastNewIds = state.NewArticleIds;
        _lastDeletableIds = state.DeletableArticleIds;
        _lastNewCommentIds = state.NewCommentArticleIds;
        _lastArticleReactions = state.ArticleReactions;
        RebuildArticleList(state.Articles, state.NewArticleIds, state.DeletableArticleIds, state.NewCommentArticleIds);

        if (!WriterView.Visible && !PreviewView.Visible
            && !ArticleDetailView.Visible)
        {
            ShowArticleList();
        }
    }

    #region View Switching

    private void ShowArticleList()
    {
        ArticleListView.Visible = true;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = false;
    }

    private void ShowArticleDetail(STNewsUiState state)
    {
        var article = state.OpenArticle!;

        ArticleListView.Visible = false;
        ArticleDetailView.Visible = true;
        WriterView.Visible = false;
        PreviewView.Visible = false;

        _detailArticleId = article.Id;
        DetailTitle.Text = article.Title;
        DetailAuthor.Text = Loc.GetString(
            "st-news-detail-author", ("author", article.Author));
        DetailMeta.Text = Loc.GetString(
            "st-news-detail-meta",
            ("round", article.RoundId),
            ("time", article.PublishTime.ToString(@"hh\:mm\:ss")));
        DetailContent.SetMarkupPermissive(article.Content);

        DeleteArticleButton.Visible = state.CanDeleteOpenArticle;
        RebuildDetailReactionBar(article.Id, state.ArticleReactions);
        RebuildCommentList(state.OpenArticleComments);
        CommentEdit.TextRope = Rope.Leaf.Empty;
        UpdateCommentCounter();
    }

    private void ShowWriter()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = true;
        PreviewView.Visible = false;
        UpdateTitleCounter();
        UpdateContentCounter();
    }

    private void ShowPreview()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = true;

        PreviewTitle.Text = TitleEdit.Text;
        PreviewContent.SetMarkupPermissive(
            Rope.Collapse(ContentEdit.TextRope));
    }

    #endregion

    #region Article List

    private void RebuildArticleList(
        List<STNewsArticleSummary> articles,
        HashSet<int> newArticleIds,
        HashSet<int> deletableIds,
        HashSet<int> newCommentIds)
    {
        ArticleList.RemoveAllChildren();

        var query = SearchBar.SearchText;
        var hasResults = false;

        foreach (var article in articles)
        {
            if (!STSearchFilter.Matches(query, article.Title, article.Author)
                && !STSearchFilter.Matches(query, article.Preview))
            {
                continue;
            }

            var isNew = newArticleIds.Contains(article.Id);
            var canDelete = deletableIds.Contains(article.Id);
            var hasNewComments = newCommentIds.Contains(article.Id);
            ArticleList.AddChild(BuildArticleCard(article, isNew, canDelete, hasNewComments));
            hasResults = true;
        }

        NoArticlesLabel.Visible = !hasResults;
        ArticleScroll.Visible = hasResults;
    }

    private static Color DeriveCardBackground(int embedColor)
    {
        var accent = Color.FromHex($"#{embedColor:X6}");
        return Color.InterpolateBetween(CardBackground, accent, CardColorBlendFactor);
    }

    private static Color DeriveCardBorder(int embedColor)
    {
        var accent = Color.FromHex($"#{embedColor:X6}");
        return Color.InterpolateBetween(CardBackground, accent, CardBorderBlendFactor);
    }

    private Control BuildArticleCard(STNewsArticleSummary article, bool isNew, bool canDelete, bool hasNewComments)
    {
        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = DeriveCardBackground(article.EmbedColor),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
                BorderColor = DeriveCardBorder(article.EmbedColor),
                BorderThickness = new Thickness(0, 0, 0, 1),
            },
            HorizontalExpand = true,
            Margin = new Thickness(4, 2, 4, 2),
        };

        var vbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var titleRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        if (isNew)
        {
            var newLabel = new Label
            {
                Text = Loc.GetString("st-news-new-indicator"),
                FontColorOverride = NewIndicatorColor,
                Margin = new Thickness(0, 0, 6, 0),
            };
            titleRow.AddChild(newLabel);
        }

        var titleLabel = new Label
        {
            Text = article.Title,
            StyleClasses = { "LabelHeading" },
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            ClipText = false,
        };
        titleRow.AddChild(titleLabel);
        vbox.AddChild(titleRow);

        var metaLabel = new Label
        {
            Text = Loc.GetString("st-news-card-meta",
                ("author", article.Author),
                ("round", article.RoundId),
                ("time", article.PublishTime.ToString(@"hh\:mm\:ss"))),
            FontColorOverride = MetaColor,
        };
        vbox.AddChild(metaLabel);

        // Comment count
        if (article.CommentCount > 0)
        {
            var commentText = hasNewComments
                ? Loc.GetString("st-news-card-comments-new", ("count", article.CommentCount))
                : Loc.GetString("st-news-card-comments", ("count", article.CommentCount));

            var commentLabel = new Label
            {
                Text = commentText,
                FontColorOverride = hasNewComments ? NewIndicatorColor : MetaColor,
            };
            vbox.AddChild(commentLabel);
        }

        if (!string.IsNullOrEmpty(article.Preview))
        {
            var previewLabel = new RichTextLabel
            {
                HorizontalExpand = true,
            };
            var previewMsg = new FormattedMessage();
            previewMsg.PushColor(PreviewColor);
            previewMsg.AddText(article.Preview);
            previewMsg.Pop();
            previewLabel.SetMessage(previewMsg);
            vbox.AddChild(previewLabel);
        }

        var articleId = article.Id;

        // Separate row prevents reaction wrapping from stretching action buttons
        if (_lastArticleReactions.TryGetValue(article.Id, out var reactions) && reactions.Count > 0)
        {
            vbox.AddChild(BuildCompactReactionBar(article.Id, reactions));
        }

        var actionRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Right,
            SeparationOverride = 4,
            Margin = new Thickness(0, 4, 0, 0),
        };

        if (canDelete)
        {
            var deleteButton = new Button
            {
                Text = Loc.GetString("st-news-delete-button"),
            };
            deleteButton.OnPressed += _ => OnDeleteArticle?.Invoke(articleId);
            actionRow.AddChild(deleteButton);
        }

        var copyButton = new Button
        {
            Text = Loc.GetString("st-news-copy-link-button"),
        };
        copyButton.OnPressed += _ =>
            _clipboard.SetText(FormatNewsLink(articleId));
        actionRow.AddChild(copyButton);

        var readButton = new Button
        {
            Text = Loc.GetString("st-news-read-button"),
        };
        readButton.OnPressed += _ => OnRequestArticle?.Invoke(articleId);
        actionRow.AddChild(readButton);

        vbox.AddChild(actionRow);

        card.AddChild(vbox);
        return card;
    }

    #endregion

    #region Comments

    private void RebuildCommentList(List<STNewsComment>? comments)
    {
        CommentList.RemoveAllChildren();

        var count = comments?.Count ?? 0;
        CommentsHeaderLabel.Text = Loc.GetString("st-news-comments-header", ("count", count));

        if (comments == null || comments.Count == 0)
            return;

        foreach (var comment in comments)
        {
            CommentList.AddChild(BuildCommentCard(comment));
        }
    }

    private Control BuildCommentCard(STNewsComment comment)
    {
        var vbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2),
        };

        // Header row: faction icon + author + timestamp
        var header = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
        };

        var factionIcon = new TextureRect
        {
            MinSize = FactionIconSize,
            MaxSize = FactionIconSize,
            Visible = false,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Margin = new Thickness(0, 0, 4, 0),
        };

        if (comment.AuthorFaction is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(comment.AuthorFaction, out var patch))
        {
            factionIcon.Texture = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(patch.Rsi, patch.State));
            factionIcon.Visible = true;
        }

        header.AddChild(factionIcon);

        var authorLabel = new Label
        {
            Text = comment.Author,
            StyleClasses = { "LabelKeyText" },
        };
        header.AddChild(authorLabel);

        var timestampLabel = new Label
        {
            Text = Loc.GetString("st-news-comment-timestamp",
                ("round", comment.RoundId),
                ("time", comment.PostedTime.ToString(@"hh\:mm\:ss"))),
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(8, 0, 0, 0),
        };
        header.AddChild(timestampLabel);

        vbox.AddChild(header);

        var contentLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(4, 2, 0, 0),
        };
        var contentMsg = new FormattedMessage();
        contentMsg.AddText(comment.Content);
        contentLabel.SetMessage(contentMsg);
        vbox.AddChild(contentLabel);

        var separator = new HSeparator
        {
            Margin = new Thickness(0, 4, 0, 0),
        };
        vbox.AddChild(separator);

        return vbox;
    }

    private void UpdateCommentCounter()
    {
        var len = (int) Rope.CalcTotalLength(CommentEdit.TextRope);
        var remaining = STNewsConstants.MaxCommentLength - len;
        CommentCounter.Text = $"{remaining}/{STNewsConstants.MaxCommentLength}";
        CommentCounter.FontColorOverride = remaining < 0 ? Color.Red : MetaColor;
        PostCommentButton.Disabled = remaining < 0;
    }

    #endregion

    #region Reactions

    /// <summary>
    /// Creates a TextureRect displaying a faction band patch sprite.
    /// </summary>
    private TextureRect CreatePatchIcon(string reactionId, Vector2 size)
    {
        var (rsi, state) = STFactionPatchIcons.PatchStates[reactionId];
        return new TextureRect
        {
            Texture = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(rsi, state)),
            MinSize = size,
            MaxSize = size,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
        };
    }

    /// <summary>
    /// Creates a single reaction toggle button showing a faction patch icon and count.
    /// </summary>
    private Button BuildReactionButton(
        int articleId,
        STReactionSummary reaction,
        int separationOverride = 2,
        float? minWidth = null)
    {
        var baseColor = reaction.UserReacted ? ReactionActiveColor : ReactionInactiveColor;
        var btn = new Button
        {
            ModulateSelfOverride = baseColor,
            ToolTip = STReactionDefinitions.LocKeys.TryGetValue(reaction.ReactionId, out var locKey)
                ? Loc.GetString(locKey)
                : reaction.ReactionId,
        };

        if (minWidth is { } w)
            btn.MinWidth = w;

        var content = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = separationOverride,
        };

        content.AddChild(CreatePatchIcon(reaction.ReactionId, ReactionIconSize));
        content.AddChild(new Label
        {
            Text = reaction.Count.ToString(),
            FontColorOverride = reaction.UserReacted ? Color.White : MetaColor,
            VerticalAlignment = VAlignment.Center,
        });

        btn.AddChild(content);

        var capturedReactionId = reaction.ReactionId;
        btn.OnPressed += _ =>
        {
            ApplyOptimisticReaction(articleId, capturedReactionId);
            OnToggleReaction?.Invoke(articleId, capturedReactionId);
        };

        btn.OnMouseEntered += _ => btn.ModulateSelfOverride = reaction.UserReacted
            ? Color.InterpolateBetween(ReactionActiveColor, Color.White, 0.15f)
            : ReactionHoverColor;
        btn.OnMouseExited += _ => btn.ModulateSelfOverride = baseColor;

        return btn;
    }

    /// <summary>
    /// Optimistically updates the local reaction cache and rebuilds the reaction UI
    /// so the user sees immediate feedback without waiting for the server broadcast.
    /// </summary>
    private void ApplyOptimisticReaction(int articleId, string reactionId)
    {
        if (!_lastArticleReactions.TryGetValue(articleId, out var summaries))
        {
            summaries = new List<STReactionSummary>();
            _lastArticleReactions[articleId] = summaries;
        }

        var idx = summaries.FindIndex(s => s.ReactionId == reactionId);
        if (idx >= 0)
        {
            var old = summaries[idx];
            if (old.UserReacted)
            {
                if (old.Count <= 1)
                    summaries.RemoveAt(idx);
                else
                    summaries[idx] = new STReactionSummary(reactionId, old.Count - 1, false);
            }
            else
            {
                summaries[idx] = new STReactionSummary(reactionId, old.Count + 1, true);
            }
        }
        else
        {
            summaries.Add(new STReactionSummary(reactionId, 1, true));
        }

        if (ArticleDetailView.Visible && _detailArticleId == articleId)
            RebuildDetailReactionBar(articleId, _lastArticleReactions);
        else
            RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
    }

    /// <summary>
    /// Builds a compact reaction bar for article list cards with clickable toggle buttons.
    /// </summary>
    private Control BuildCompactReactionBar(int articleId, List<STReactionSummary> reactions)
    {
        var row = new WrapContainer
        {
            LayoutAxis = Axis.Horizontal,
            SeparationOverride = 6,
            CrossSeparationOverride = 4,
        };

        foreach (var reaction in reactions)
        {
            if (reaction.Count <= 0)
                continue;

            if (!STFactionPatchIcons.PatchStates.ContainsKey(reaction.ReactionId))
                continue;

            row.AddChild(BuildReactionButton(articleId, reaction));
        }

        return row;
    }

    /// <summary>
    /// Rebuilds the clickable reaction bar in the article detail view.
    /// Shows only reactions with count > 0 as toggle buttons, plus a "+" button to open the picker.
    /// </summary>
    private void RebuildDetailReactionBar(
        int articleId,
        Dictionary<int, List<STReactionSummary>> articleReactions)
    {
        DetailReactionBar.RemoveAllChildren();

        // Show existing reactions as toggle buttons
        if (articleReactions.TryGetValue(articleId, out var summaries))
        {
            foreach (var summary in summaries)
            {
                if (summary.Count <= 0)
                    continue;

                if (!STFactionPatchIcons.PatchStates.ContainsKey(summary.ReactionId))
                    continue;

                DetailReactionBar.AddChild(BuildReactionButton(articleId, summary, separationOverride: 3, minWidth: 42));
            }
        }

        // "+" button to open faction patch picker
        var addButton = new Button
        {
            Text = Loc.GetString("st-news-reaction-add"),
            MinWidth = 28,
        };

        var capturedArticle = articleId;
        addButton.OnPressed += _ => ShowPatchPicker(capturedArticle, addButton);

        DetailReactionBar.AddChild(addButton);

        // Copy-link button in its own right-aligned row
        DetailActionRow.RemoveAllChildren();
        var copyLinkBtn = new Button
        {
            Text = Loc.GetString("st-news-copy-link-button"),
        };
        copyLinkBtn.OnPressed += _ =>
        {
            if (_detailArticleId is { } id)
                _clipboard.SetText(FormatNewsLink(id));
        };
        DetailActionRow.AddChild(copyLinkBtn);
    }

    /// <summary>
    /// Shows a popup grid of all 14 faction patch icons for the user to pick a reaction.
    /// </summary>
    private void ShowPatchPicker(int articleId, Control anchor)
    {
        var popup = new Popup();

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PickerBackdropColor,
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
                BorderColor = CardBorder,
                BorderThickness = new Thickness(1),
            },
        };

        var grid = new GridContainer
        {
            Columns = PickerColumnsPerRow,
            HSeparationOverride = 3,
            VSeparationOverride = 3,
        };

        foreach (var reactionId in STReactionDefinitions.Available)
        {
            if (!STFactionPatchIcons.PatchStates.ContainsKey(reactionId))
                continue;

            var btn = new Button
            {
                MinSize = new Vector2(28, 28),
                MaxSize = new Vector2(28, 28),
                ToolTip = STReactionDefinitions.LocKeys.TryGetValue(reactionId, out var pickerLocKey)
                    ? Loc.GetString(pickerLocKey)
                    : reactionId,
            };

            btn.AddChild(CreatePatchIcon(reactionId, PickerIconSize));

            var capturedId = reactionId;
            btn.OnPressed += _ =>
            {
                ApplyOptimisticReaction(articleId, capturedId);
                OnToggleReaction?.Invoke(articleId, capturedId);
                popup.Close();
            };

            grid.AddChild(btn);
        }

        panel.AddChild(grid);
        popup.AddChild(panel);

        popup.OnPopupHide += popup.Orphan;

        UserInterfaceManager.ModalRoot.AddChild(popup);
        popup.Open(UIBox2.FromDimensions(
            anchor.GlobalPosition + new Vector2(0, anchor.Height),
            new Vector2(1, 1)));
    }

    #endregion

    #region Writer

    private void BuildColorPicker()
    {
        foreach (var (locKey, color) in ColorPresets)
        {
            var panel = new PanelContainer
            {
                MinSize = ColorSwatchSize,
                MaxSize = ColorSwatchSize,
                ToolTip = Loc.GetString(locKey),
                MouseFilter = MouseFilterMode.Stop,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex($"#{color:X6}"),
                    BorderColor = Color.Transparent,
                    BorderThickness = new Thickness(2),
                },
            };

            var colorValue = color;
            var panelRef = panel;
            panel.OnKeyBindDown += args =>
            {
                if (args.Function != Robust.Shared.Input.EngineKeyFunctions.UIClick)
                    return;

                _selectedColor = colorValue;
                UpdateColorSelection(panelRef);
            };

            _colorPanels.Add(panel);
            ColorPicker.AddChild(panel);
        }

        UpdateColorSelection(_colorPanels[0]);
    }

    private void UpdateColorSelection(PanelContainer? selected)
    {
        foreach (var panel in _colorPanels)
        {
            if (panel.PanelOverride is StyleBoxFlat flat)
                flat.BorderColor = panel == selected ? Color.White : Color.Transparent;
        }
    }

    private void DoPublish()
    {
        var title = TitleEdit.Text.Trim();
        var content = Rope.Collapse(ContentEdit.TextRope).Trim();

        if (string.IsNullOrEmpty(title) || string.IsNullOrEmpty(content))
            return;

        OnPublishArticle?.Invoke(title, content, _selectedColor);

        TitleEdit.Text = string.Empty;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        _selectedColor = ColorPresets[0].Color;
        UpdateColorSelection(_colorPanels[0]);

        ShowArticleList();
    }

    private void UpdateTitleCounter()
    {
        var remaining = STNewsConstants.MaxTitleLength - TitleEdit.Text.Length;
        TitleCounter.Text = $"{remaining}/{STNewsConstants.MaxTitleLength}";
        TitleCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    private void UpdateContentCounter()
    {
        var len = (int) Rope.CalcTotalLength(ContentEdit.TextRope);
        var remaining = STNewsConstants.MaxContentLength - len;
        ContentCounter.Text = $"{remaining}/{STNewsConstants.MaxContentLength}";
        ContentCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    #endregion

    #region News Link Handler

    public void HandleNewsLinkClick(int articleId)
    {
        OnRequestArticle?.Invoke(articleId);
    }

    #endregion
}
