using Content.Shared._NC.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcContractCard : PanelContainer
{
    private const float DescriptionHorizontalBudget = 40f;
    private const int DescriptionMaxChars = 240;
    private const int TargetIconPx = 56;
    private const int RewardIconPx = 26;
    private const float ProgressFillMinVisibleWidth = 8f;
    private const bool HideContractRewards = true;

    private ContractClientData _data;
    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprites;
    private int _presentationHash;
    private int _skipCost;
    private string _skipCurrency;
    private int _skipBalance;
    private float _lastDescriptionMaxWidth = -1f;
    private float _progressRatio;

    public NcContractCard(
        ContractClientData data,
        IPrototypeManager protoMan,
        SpriteSystem sprites,
        int skipCost = 0,
        string skipCurrency = "",
        int skipBalance = 0)
    {
        RobustXamlLoader.Load(this);

        _data = data;
        _proto = protoMan;
        _sprites = sprites;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        _presentationHash = ComputePresentationHash(data, skipCost, skipCurrency, skipBalance);
        PrimaryActionButton.OnPressed += OnPrimaryActionPressed;

        PopulateUi();
    }

    public event Action<string>? OnClaim;
    public event Action<string>? OnTake;
    public event Action<string>? OnSkip;
    public event Action<string>? OnRequestPinpointer;

    private void PopulateUi()
    {
        ApplyDifficultyChrome();
        PopulateHeader();
        PopulateDescription();
        PopulateStatus();
        PopulateStage();
        PopulateGoals();
        PopulateTurnIn();
        PopulateProgress();
        PopulateRewardsSection();
        PopulateActionsSection();
        SyncDescriptionWidth(Size.X);
    }

    private void ApplyDifficultyChrome()
    {
        var borderColor = DifficultyColor(_data.Difficulty, _data.Completed);

        AccentStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = borderColor
        };

        CardFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1B1B20"),
            BorderColor = Color.FromHex("#7A6338"),
            BorderThickness = new(2),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 7,
            ContentMarginBottomOverride = 7
        };

        TitleLabel.Modulate = _data.Completed
            ? Color.FromHex("#E4D4A5")
            : Color.FromHex("#D9C187");
    }

    private void PopulateHeader()
    {
        var title = BuildPrettyTitle(_data);
        TitleLabel.Text = title;
        TitleLabel.ToolTip = title;

        BadgesRow.DisposeAllChildren();
        BadgesRow.RemoveAllChildren();

        var objectiveTypeText = ObjectiveTypeName(_data.ExecutionKind);
        var objectiveTypeTip = ObjectiveTypeTooltip(_data.ExecutionKind);
        BadgesRow.AddChild(
            BuildBadge(
                objectiveTypeText,
                objectiveTypeTip,
                Color.FromHex("#232127"),
                Color.FromHex("#8A7442")));

        if (!_data.Repeatable)
        {
            var tip = Loc.GetString("nc-store-contract-badge-single-tooltip");
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-single"),
                    tip,
                    Color.FromHex("#2A2627"),
                    Color.FromHex("#6B5A3A")));
        }

        if (_data.FlowStatus is ContractFlowStatus.AwaitingActivation or ContractFlowStatus.InProgress)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-taken"),
                    Loc.GetString("nc-store-contract-badge-taken-tooltip"),
                    Color.FromHex("#2A313B"),
                    Color.FromHex("#8A7442")));

            if (IsGhostRoleAwaitingAcceptance(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role"),
                        Loc.GetString("nc-store-contract-badge-awaiting-ghost-role-tooltip"),
                        Color.FromHex("#3A2E19"),
                        Color.FromHex("#C69A46")));
            }
            else if (IsGhostRoleActive(_data))
            {
                BadgesRow.AddChild(
                    BuildBadge(
                        Loc.GetString("nc-store-contract-badge-ghost-role-active"),
                        Loc.GetString("nc-store-contract-badge-ghost-role-active-tooltip"),
                        Color.FromHex("#243040"),
                        Color.FromHex("#8FA8C5")));
            }
        }

        if (_data.FlowStatus == ContractFlowStatus.ReadyToTurnIn)
        {
            BadgesRow.AddChild(
                BuildBadge(
                    Loc.GetString("nc-store-contract-badge-completed"),
                    Loc.GetString("nc-store-contract-badge-completed-tooltip"),
                    Color.FromHex("#243125"),
                    Color.FromHex("#8AA05D")));
        }
    }

    private void PopulateDescription()
    {
        var fullText = BuildPrettyDescription(_data);
        if (string.IsNullOrWhiteSpace(fullText))
        {
            DescriptionLabel.Visible = false;
            DescriptionLabel.ToolTip = null;
            DescriptionLabel.SetMessage(string.Empty, null, Color.FromHex("#D5CDC0"));
            return;
        }

        var displayText = BuildDisplayDescription(_data, DescriptionMaxChars);
        DescriptionLabel.Visible = true;
        DescriptionLabel.ToolTip = fullText;
        DescriptionLabel.SetMessage(displayText, null, Color.FromHex("#D5CDC0"));
    }

    private void PopulateStatus()
    {
        var ghostRoleStatus = BuildGhostRoleStatusText(_data);
        if (string.IsNullOrWhiteSpace(ghostRoleStatus))
        {
            StatusLabel.Visible = false;
            StatusLabel.Text = string.Empty;
            StatusLabel.ToolTip = null;
            return;
        }

        StatusLabel.Visible = true;
        StatusLabel.Text = ghostRoleStatus;
        StatusLabel.ToolTip = ghostRoleStatus;
        StatusLabel.Modulate = IsGhostRoleAwaitingAcceptance(_data)
            ? Color.FromHex("#D3B06A")
            : _data.FlowStatus == ContractFlowStatus.Failed
                ? Color.FromHex("#D97575")
                : Color.FromHex("#8DB7E8");
    }

    private void PopulateStage()
    {
        var hasStage = (_data.ExecutionKind is ContractExecutionKind.HuntObjective or ContractExecutionKind.RepairObjective or ContractExecutionKind.GhostRoleObjective) &&
            _data.Runtime.StageGoal > 1;

        StageLabel.Visible = hasStage;
        if (!hasStage)
            return;

        var stage = Math.Clamp(_data.Runtime.Stage, 0, _data.Runtime.StageGoal);
        StageLabel.Text = Loc.GetString("nc-store-contract-runtime-stage", ("stage", stage), ("goal", _data.Runtime.StageGoal));
    }

    private void PopulateGoals()
    {
        GoalsHost.DisposeAllChildren();
        GoalsHost.RemoveAllChildren();

        if (_data.Targets is { Count: > 0 })
        {
            foreach (var target in _data.Targets)
                GoalsHost.AddChild(BuildTargetRow(target.TargetItem, target.Required));
        }
        else if (!string.IsNullOrWhiteSpace(_data.TargetItem))
        {
            GoalsHost.AddChild(BuildTargetRow(_data.TargetItem, _data.Required));
        }
    }

    private void PopulateTurnIn()
    {
        var turnInNote = BuildTurnInNoteText(_data);
        TurnInNoteLabel.Visible = !string.IsNullOrWhiteSpace(turnInNote);
        TurnInNoteLabel.Text = turnInNote;
        TurnInNoteLabel.ToolTip = turnInNote;

        TurnInSection.Visible = ShouldShowTurnInItem(_data);
        TurnInHost.DisposeAllChildren();
        TurnInHost.RemoveAllChildren();

        if (TurnInSection.Visible)
            TurnInHost.AddChild(BuildTargetRow(_data.TurnInItem, 1));
    }

    private void PopulateProgress()
    {
        ProgressSection.Visible = !_data.Completed;
        if (!ProgressSection.Visible)
            return;

        var max = CalculateRequiredTotal(_data);
        var val = Math.Clamp(_data.Progress, 0, max);
        _progressRatio = max > 0 ? (float) val / max : 0f;

        ProgressLabel.Text = Loc.GetString("nc-store-contract-progress-caption");
        ProgressValueLabel.Text = Loc.GetString("nc-store-contract-progress-value", ("progress", val), ("required", max));
        UpdateProgressFillWidth();
    }

    private void PopulateRewardsSection()
    {
        RewardsSection.Visible = !HideContractRewards;
        if (HideContractRewards)
            return;

        RewardsHost.DisposeAllChildren();
        RewardsHost.RemoveAllChildren();
        PopulateRewards(RewardsHost, _data.Rewards);
    }

    private void PopulateActionsSection()
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;
        var canRequestPinpointer = CanRequestPinpointer(_data);

        var actionHint = BuildActionHintText(_data);
        ActionHintLabel.Text = actionHint;
        ActionHintLabel.ToolTip = actionHint;
        ActionHintLabel.Modulate = canClaim
            ? Color.FromHex("#D1C4A8")
            : Color.FromHex("#B8AD98");

        PrimaryActionButton.Text = canTake
            ? Loc.GetString("nc-store-contract-action-take")
            : canClaim
                ? Loc.GetString("nc-store-contract-action-claim")
                : Loc.GetString(
                    "nc-store-contract-action-claim-progress",
                    ("progress", _data.Progress),
                    ("required", CalculateRequiredTotal(_data)));

        PrimaryActionButton.Disabled = !(canTake || canClaim);
        PrimaryActionButton.StyleBoxOverride = canTake
            ? BuildButtonStyle(Color.FromHex("#233350"), Color.FromHex("#8A7442"))
            : canClaim
                ? BuildButtonStyle(Color.FromHex("#2A4530"), Color.FromHex("#8AA05D"))
                : BuildButtonStyle(Color.FromHex("#25262B"), Color.FromHex("#5E523E"));
        PrimaryActionButton.ModulateSelfOverride = canTake
            ? Color.FromHex("#E7DAB7")
            : canClaim
                ? Color.FromHex("#E5E1D2")
                : Color.FromHex("#B0B0B0");

        PrimaryActionButton.ToolTip = canTake
            ? Loc.GetString("nc-store-contract-take-tooltip")
            : canClaim
                ? !_data.Repeatable
                    ? Loc.GetString("nc-store-contract-claim-tooltip-single")
                    : Loc.GetString("nc-store-contract-claim-tooltip-repeatable")
                : Loc.GetString("nc-store-contract-claim-tooltip-not-done");

        SecondaryButtonsRow.DisposeAllChildren();
        SecondaryButtonsRow.RemoveAllChildren();

        if (canRequestPinpointer)
        {
            var pointerBtn = new Button
            {
                Text = Loc.GetString("nc-store-contract-action-pinpointer"),
                HorizontalExpand = true,
                MinSize = new(0, 26),
                ToolTip = Loc.GetString("nc-store-contract-action-pinpointer-tooltip")
            };
            pointerBtn.StyleBoxOverride = BuildButtonStyle(Color.FromHex("#2A2C32"), Color.FromHex("#6E5B34"));
            pointerBtn.ModulateSelfOverride = Color.FromHex("#D6C9A5");

            pointerBtn.OnPressed += _ => OnRequestPinpointer?.Invoke(_data.Id);
            SecondaryButtonsRow.AddChild(pointerBtn);
        }

        if (_skipCost > 0 && !string.IsNullOrWhiteSpace(_skipCurrency))
        {
            var skipCurrencyName = CurrencyName(_skipCurrency);
            var canSkip = _data.FlowStatus == ContractFlowStatus.Available && _skipBalance >= _skipCost;
            var skipBtn = new Button
            {
                Text = Loc.GetString("nc-store-contract-action-skip", ("cost", _skipCost), ("currency", skipCurrencyName)),
                HorizontalExpand = true,
                MinSize = new(0, 26),
                Disabled = !canSkip
            };

            skipBtn.StyleBoxOverride = canSkip
                ? BuildButtonStyle(Color.FromHex("#2A2C32"), Color.FromHex("#6E5B34"))
                : BuildButtonStyle(Color.FromHex("#24252A"), Color.FromHex("#4F4638"));
            skipBtn.ModulateSelfOverride = canSkip
                ? Color.FromHex("#CEC3A4")
                : Color.FromHex("#8A8A8A");

            var baseTip = Loc.GetString("nc-store-contract-skip-tooltip", ("cost", _skipCost), ("currency", skipCurrencyName));
            skipBtn.ToolTip = _data.FlowStatus != ContractFlowStatus.Available
                ? Loc.GetString("nc-store-contract-skip-locked")
                : canSkip
                    ? baseTip
                    : $"{baseTip}\n{Loc.GetString("nc-store-contract-skip-failed")}";

            skipBtn.OnPressed += _ =>
            {
                if (canSkip)
                    OnSkip?.Invoke(_data.Id);
            };

            SecondaryButtonsRow.AddChild(skipBtn);
        }

        SecondaryButtonsRow.Visible = SecondaryButtonsRow.ChildCount > 0;
    }

    private void OnPrimaryActionPressed(BaseButton.ButtonEventArgs args)
    {
        var canTake = _data.FlowStatus == ContractFlowStatus.Available;
        var canClaim = _data.FlowStatus == ContractFlowStatus.ReadyToTurnIn;

        if (canTake)
        {
            OnTake?.Invoke(_data.Id);
            return;
        }

        if (canClaim)
            OnClaim?.Invoke(_data.Id);
    }

    private static PanelContainer BuildBadge(string text, string? tooltip, Color bg, Color border)
    {
        var badge = new PanelContainer
        {
            VerticalAlignment = VAlignment.Center,
            Margin = new(0, 0, 5, 0),
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = tooltip,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bg,
                BorderColor = border,
                BorderThickness = new(1),
                ContentMarginLeftOverride = 7,
                ContentMarginRightOverride = 7,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 2
            }
        };

        var badgeText = new Label
        {
            Text = text,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
            ToolTip = tooltip
        };
        badgeText.StyleClasses.Add("LabelSubText");
        badge.AddChild(badgeText);
        return badge;
    }

    private static StyleBoxFlat BuildButtonStyle(Color background, Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4
        };
    }

    public void UpdateData(ContractClientData data, int skipCost, string skipCurrency, int skipBalance)
    {
        var presentationHash = ComputePresentationHash(data, skipCost, skipCurrency, skipBalance);
        if (_presentationHash == presentationHash)
            return;

        _presentationHash = presentationHash;
        _data = data;
        _skipCost = skipCost;
        _skipCurrency = skipCurrency;
        _skipBalance = skipBalance;
        _lastDescriptionMaxWidth = -1f;

        PopulateUi();
    }

    protected override void Resized()
    {
        base.Resized();
        SyncDescriptionWidth(Size.X);
        UpdateProgressFillWidth();
    }

    private void SyncDescriptionWidth(float candidateWidth)
    {
        if (candidateWidth <= 0 || !float.IsFinite(candidateWidth))
            return;

        var maxWidth = System.MathF.Max(0, candidateWidth - DescriptionHorizontalBudget);
        if (System.MathF.Abs(_lastDescriptionMaxWidth - maxWidth) < 0.5f)
            return;

        _lastDescriptionMaxWidth = maxWidth;
        DescriptionLabel.MaxWidth = maxWidth;
    }

    private void UpdateProgressFillWidth()
    {
        var trackWidth = ProgressTrack.Width;
        if (trackWidth <= 0 || !float.IsFinite(trackWidth))
            return;

        var fillWidth = _progressRatio <= 0f
            ? 0f
            : MathF.Max(ProgressFillMinVisibleWidth, trackWidth * _progressRatio);

        ProgressFill.MinSize = new(fillWidth, ProgressFill.MinSize.Y);
        ProgressFill.Visible = fillWidth > 0f;
    }
}
