using Content.Shared._Stalker_EN.CCVar;
using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// Compose page for writing a new message or reply in a channel or DM conversation.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerComposePage : BoxContainer
{
    /// <summary>Raised when the user presses the back button to return to the channel view.</summary>
    public event Action? OnBack;

    /// <summary>Raised when the user dismisses the reply-to context.</summary>
    public event Action? OnDismissReply;

    /// <summary>
    /// Raised when the user sends a message. Args: (chatId, content, isAnonymous).
    /// </summary>
    public event Action<string, string, bool>? OnSend;

    private readonly IConfigurationManager _config;
    private readonly IPrototypeManager _protoManager;

    private int _maxLength;
    private string _chatId = string.Empty;
    private bool _isDmChat;

    public STMessengerComposePage()
    {
        _config = IoCManager.Resolve<IConfigurationManager>();
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        RobustXamlLoader.Load(this);

        BackButton.OnPressed += _ => OnBack?.Invoke();

        SendButton.OnPressed += _ =>
        {
            var content = Rope.Collapse(ContentInput.TextRope).Trim();
            if (!string.IsNullOrEmpty(content))
            {
                OnSend?.Invoke(_chatId, content, AnonymousToggle.Pressed);
                ContentInput.TextRope = Rope.Leaf.Empty;
            }
        };

        DismissReply.OnPressed += _ =>
        {
            ReplyContext.Visible = false;
            OnDismissReply?.Invoke();
        };

        ContentInput.OnTextChanged += args =>
        {
            var length = (int) Rope.CalcTotalLength(args.TextRope);
            var remaining = _maxLength - length;
            CharCounter.Text = Loc.GetString("st-messenger-char-counter",
                ("remaining", remaining), ("max", _maxLength));
            CharCounter.FontColorOverride = remaining < 0 ? Color.Red : null;
            SendButton.Disabled = remaining < 0;
        };
    }

    public void Setup(string chatId, uint? replyToId, string? replySnippet, string? displayName = null, string? initialContent = null)
    {
        _chatId = chatId;
        _isDmChat = chatId.StartsWith(STMessengerChat.DmChatPrefix, StringComparison.Ordinal);
        ContentInput.TextRope = initialContent is not null ? new Rope.Leaf(initialContent) : Rope.Leaf.Empty;
        AnonymousToggle.Pressed = false;

        _maxLength = _config.GetCVar(STCCVars.MessengerMaxMessageLength);
        var initialLength = initialContent?.Length ?? 0;
        var remaining = _maxLength - initialLength;
        CharCounter.Text = Loc.GetString("st-messenger-char-counter",
            ("remaining", remaining), ("max", _maxLength));
        CharCounter.FontColorOverride = remaining < 0 ? Color.Red : null;
        SendButton.Disabled = remaining < 0;

        if (_isDmChat)
        {
            // Use the display name (character name) if available, otherwise fall back to messenger ID from chat ID
            RecipientLabel.Text = displayName ?? chatId[STMessengerChat.DmChatPrefix.Length..];
            AnonymousToggle.Visible = false;
        }
        else
        {
            var hasProto = _protoManager.TryIndex<STMessengerChannelPrototype>(chatId, out var proto);
            RecipientLabel.Text = hasProto ? Loc.GetString(proto!.Name) : chatId;
            AnonymousToggle.Visible = hasProto && proto!.AllowAnonymous;
        }

        if (replyToId is not null && replySnippet is not null)
        {
            ReplyContext.Visible = true;
            ReplySnippetLabel.Text = $"\"{replySnippet}\"";
        }
        else
        {
            ReplyContext.Visible = false;
        }
    }
}
