using System.Text.RegularExpressions;
using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A single message row in a channel or DM view, showing sender, timestamp, content, and a reply button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerMessageEntry : BoxContainer
{
    /// <summary>Raised when the user clicks reply; args are (messageId, snippetPreview).</summary>
    public event Action<uint, string>? OnReply;

    private const string NewsLinkPrefix = "NEWS#";

    private static readonly Regex LinkRefPattern = new(@"\[([A-Z]+#)(\d+)\]", RegexOptions.Compiled);

    public STMessengerMessageEntry(STMessengerMessage message)
    {
        RobustXamlLoader.Load(this);

        SenderLabel.Text = message.Sender;

        if (message.SenderFaction is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(message.SenderFaction, out var patch))
        {
            var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
            FactionIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(patch.Rsi, patch.State));
            FactionIcon.Visible = true;
        }

        var hours = (int)message.Timestamp.TotalHours;
        var minutes = message.Timestamp.Minutes;
        var seconds = message.Timestamp.Seconds;
        TimestampLabel.Text = $"{hours:D2}:{minutes:D2}:{seconds:D2}";

        if (message.ReplySnippet is not null)
        {
            ReplyQuote.Visible = true;
            ReplyQuote.Text = $"> {message.ReplySnippet}";
        }

        ContentLabel.SetMessage(BuildMessageContent(message.Content));

        var snippet = message.Content.Length > STMessengerChat.MaxReplySnippetLength
            ? message.Content[..STMessengerChat.MaxReplySnippetLength] + "..."
            : message.Content;

        ReplyButton.OnPressed += _ => OnReply?.Invoke(message.Id, snippet);
    }

    /// <summary>
    /// Builds a <see cref="FormattedMessage"/> from message content, replacing
    /// <c>[XX#N]</c> patterns with clickable link markup: <c>[NEWS#N]</c> becomes a news link,
    /// while other prefixes (e.g. [MB#3], [TB#5]) become offer links.
    /// Non-matching text is escaped via <see cref="FormattedMessage.AddText"/> to prevent injection.
    /// </summary>
    private static FormattedMessage BuildMessageContent(string content)
    {
        var msg = new FormattedMessage();
        var lastIndex = 0;

        foreach (Match match in LinkRefPattern.Matches(content))
        {
            // Add escaped text before the match
            if (match.Index > lastIndex)
                msg.AddText(content[lastIndex..match.Index]);

            // Add clickable link markup — controlled markup, not user input
            var prefix = match.Groups[1].Value;
            var id = match.Groups[2].Value;

            if (prefix == NewsLinkPrefix)
                msg.AddMarkupPermissive($"[newslink={id}][/newslink]");
            else
                msg.AddMarkupPermissive($"[offerlink={id} prefix=\"{prefix}\"][/offerlink]");

            lastIndex = match.Index + match.Length;
        }

        // Add any remaining text after the last match
        if (lastIndex < content.Length)
            msg.AddText(content[lastIndex..]);

        return msg;
    }
}
