using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// Main page of the messenger UI, listing channels and contacts with unread badges.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerMainPage : BoxContainer
{
    /// <summary>Raised when a channel row is clicked; arg is the channel prototype ID.</summary>
    public event Action<string>? OnChannelSelected;

    /// <summary>Raised when a contact row is clicked; arg is the DM chat ID.</summary>
    public event Action<string>? OnContactSelected;

    /// <summary>Raised when the user submits a messenger ID to add; arg is the messenger ID string.</summary>
    public event Action<string>? OnAddContact;

    /// <summary>Raised when the user removes a contact; arg is the contact's messenger ID.</summary>
    public event Action<string>? OnRemoveContact;

    /// <summary>Raised when the user toggles mute on a channel; arg is the channel prototype ID.</summary>
    public event Action<ProtoId<STMessengerChannelPrototype>>? OnToggleMute;

    public STMessengerMainPage()
    {
        RobustXamlLoader.Load(this);

        AddContactButton.OnPressed += _ =>
        {
            var id = AddContactInput.Text.Trim();
            if (!string.IsNullOrEmpty(id))
            {
                OnAddContact?.Invoke(id);
                AddContactInput.Text = string.Empty;
            }
        };
    }

    public void UpdateState(STMessengerUiState state)
    {
        MessengerIdLabel.Text = Loc.GetString("st-messenger-id-label", ("id", state.MessengerId));

        ChannelList.RemoveAllChildren();
        foreach (var channel in state.Channels)
        {
            var row = new STMessengerChannelRow(channel);
            row.OnSelected += () => OnChannelSelected?.Invoke(channel.Id);
            row.OnToggleMute += () => OnToggleMute?.Invoke(channel.Id);
            ChannelList.AddChild(row);
        }

        // Build O(1) lookup for DM data by messenger ID (from the DM chat ID)
        var dmByMessengerId = new Dictionary<string, STMessengerChat>(state.DirectMessages.Count);
        foreach (var dm in state.DirectMessages)
        {
            // DM chat IDs are "dm:{messengerId}" — extract the messenger ID
            if (dm.Id.StartsWith(STMessengerChat.DmChatPrefix, StringComparison.Ordinal))
            {
                var msgId = dm.Id[STMessengerChat.DmChatPrefix.Length..];
                dmByMessengerId[msgId] = dm;
            }
        }

        ContactList.RemoveAllChildren();
        foreach (var contactInfo in state.Contacts)
        {
            STMessengerChat? dm = null;
            if (contactInfo.MessengerId is not null)
                dmByMessengerId.TryGetValue(contactInfo.MessengerId, out dm);

            var unread = dm?.UnreadCount ?? 0;
            var chatId = dm?.Id ?? STMessengerChat.DmChatPrefix + (contactInfo.MessengerId ?? contactInfo.CharacterName);

            var row = new STMessengerContactRow(
                contactInfo.CharacterName, unread, contactInfo.MessengerId, contactInfo.FactionName);
            row.OnSelected += () => OnContactSelected?.Invoke(chatId);
            row.OnRemove += () =>
            {
                if (contactInfo.MessengerId is not null)
                    OnRemoveContact?.Invoke(contactInfo.MessengerId);
            };
            ContactList.AddChild(row);
        }
    }
}
