using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A channel row in the main page's channel list, showing name, unread badge, and mute toggle.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerChannelRow : BoxContainer
{
    /// <summary>Raised when the user clicks the channel row to open it.</summary>
    public event Action? OnSelected;

    /// <summary>Raised when the user clicks the mute/unmute button.</summary>
    public event Action? OnToggleMute;

    public STMessengerChannelRow(STMessengerChat chat)
    {
        RobustXamlLoader.Load(this);

        ChannelNameLabel.Text = $"# {chat.DisplayName}";

        UnreadLabel.Text = chat.UnreadCount > 0
            ? Loc.GetString("st-messenger-unread-count", ("count", chat.UnreadCount))
            : string.Empty;
        UnreadLabel.Visible = chat.UnreadCount > 0;

        MuteButton.Text = chat.IsMuted
            ? Loc.GetString("st-messenger-unmute-button")
            : Loc.GetString("st-messenger-mute-button");

        SelectButton.OnPressed += _ => OnSelected?.Invoke();
        MuteButton.OnPressed += _ => OnToggleMute?.Invoke();
    }
}
