using System.Numerics;
using Content.Shared._Stalker_EN.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// Channel/DM conversation page showing messages and compose/reply controls.
/// Implements <see cref="IOfferLinkClickHandler"/> to handle offer reference clicks from message entries.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerChannelPage : BoxContainer, IOfferLinkClickHandler
{
    /// <summary>Raised when the user presses the back button to return to the main page.</summary>
    public event Action? OnBack;

    /// <summary>Raised when the user presses compose; arg is the current chat ID.</summary>
    public event Action<string>? OnCompose;

    /// <summary>Raised when the user presses reply on a message; args are (chatId, messageId, snippet).</summary>
    public event Action<string, uint, string>? OnReply;

    /// <summary>Raised when the user clicks an offer reference link in a message.</summary>
    public event Action<uint>? OnOfferLinkClicked;

    private string _chatId = string.Empty;
    private string _lastChatId = string.Empty;
    private int _lastMessageCount;
    private bool _scrollToBottom;

    public STMessengerChannelPage()
    {
        RobustXamlLoader.Load(this);

        BackButton.OnPressed += _ => OnBack?.Invoke();
        ComposeButton.OnPressed += _ => OnCompose?.Invoke(_chatId);
    }

    public void SetChatId(string chatId)
    {
        _chatId = chatId;
    }

    public void UpdateState(STMessengerChat chat)
    {
        ChatTitle.Text = chat.DisplayName;

        // Full rebuild only if chat changed or messages were reset
        if (chat.Id != _lastChatId || chat.Messages.Count < _lastMessageCount)
        {
            MessageList.RemoveAllChildren();
            _lastMessageCount = 0;
            _lastChatId = chat.Id;
        }

        // Append only new messages
        for (var i = _lastMessageCount; i < chat.Messages.Count; i++)
        {
            var entry = new STMessengerMessageEntry(chat.Messages[i]);
            entry.OnReply += (msgId, snippet) => OnReply?.Invoke(_chatId, msgId, snippet);
            MessageList.AddChild(entry);
        }

        _lastMessageCount = chat.Messages.Count;
        _scrollToBottom = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_scrollToBottom)
            return;

        _scrollToBottom = false;
        MessageScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    /// <inheritdoc />
    public void HandleOfferLinkClick(uint offerId)
    {
        OnOfferLinkClicked?.Invoke(offerId);
    }
}
